### ISSUE TITLE
Conversion issues from 1.12.0 to 1.13.0

### ISSUE THREAD

**Issue by ethankheil** [NREL/OpenStudio#2372] opened 2016-10-11 23:02 UTC
Several projects created in OpenStudio 1.12.0 exhibit significantly higher heating and cooling loads after being converted to OpenStudio 1.13.0. Additionally, the "Gross Wall Area" output for each and every space drops to 0.0 after the conversion process.

**Comment by DavidGoldwasser** [comment] 2016-10-12 15:57
I wasn't able to reproduce the energy or gross wall area differences with my own model. Took Small Office made with prototype measure in 1.12.0. Then version translated to 1.13.0 and ran again.

I have requested model from user on UnmetHours
https://unmethours.com/question/20551/openstudio-1120-to-1130-conversion-issues/

**Comment by DavidGoldwasser** [comment] 2016-10-13 17:55
So the Gross Wall Area mystery has been solved. At some point EnergyPlus split the "Gross Wall Area" column to "Above Ground Gross Wall Area" and "Underground Gross Wall Area", but I didn't know that and didn't change the query. The query doesn't find a value and just return 0. The measure doesn't know anything was wrong it accepts the 0 as a real value and moves on.

I see I already added code to catch the change of "Multiplier" to "Multipliers" which must have happened a version or two ago. @asparke2 unless you have another preference I'll just add a new column and list above and underground vs. trying to sum them together to mimic old look.

@kbenne any thoughts on the performance change? I'm still not sure why he gets different value on 1.13 run vs. EnergyPlus 8.6 run?

	
I removed the references to older versions of EnergyPlus, but still get the same output. After digging into the output, it seems like some of the overall variation might be driven by differences in sensible heat gain components between the 1.13 and 1.12 versions. In particular, the "Infiltration heat removal" and "Opaque surface conduction and other heat removal" losses are greater in the 1.13 run than the 1.12 version. Here's a summary of total energy use for different runs of the same input file:
OS 1.12 - 8322.34 GJ
OS 1.13 - 8932.34 GJ
EP 8.5 - 8326.02 GJ
EP 8.6 - 8327.71 GJ

**Comment by DavidGoldwasser** [comment] 2016-10-14 20:18
@kbenne seems to be something here. User posted the OpenStudio 1.12.0 file.

I first ran that in OS 1.12.0 app and got these results

![screenshot 2016-10-14 14 09 14](https://cloud.githubusercontent.com/assets/4857055/19401504/e101194e-9218-11e6-8cb3-1ff211f794a1.png)

Then I quit OpenStudio, Launched OpenStudio 1.13.0 app. Opened file and saved copy as 1.13.0 file and got these results when I re-ran it.

![screenshot 2016-10-14 14 15 14](https://cloud.githubusercontent.com/assets/4857055/19401521/ffc6888c-9218-11e6-9440-a534eebee64c.png)

Both of these were on mac. I'll email you the EnergyPlus HTML files along with the OSM's and the epw file.

**Comment by DavidGoldwasser** [comment] 2016-10-14 20:41
1.12 on left and 1.13 on right. Heating Coils

![screenshot 2016-10-14 14 39 26](https://cloud.githubusercontent.com/assets/4857055/19402081/43084754-921c-11e6-851c-a905cb1ba62b.png)

**Comment by DavidGoldwasser** [comment] 2016-10-14 21:12
Another screenshot from HTML. This time AirTerminal:SingleDuct:VAV:Reheat

![screenshot 2016-10-14 15 11 44](https://cloud.githubusercontent.com/assets/4857055/19402821/9fbe7a78-9220-11e6-9ad1-287d1458c002.png)

**Comment by asparke2** [comment] 2016-10-14 22:50
Ok I think I've found the culprit: [Intelligent Defaults for Minimum Flow Fraction on VAV Terminals](https://github.com/NREL/EnergyPlus/pull/5646)

When you take the E+ 8.5 file and use the Version Translator to convert to E+ 8.6, the field `Damper Heating Action` in `AirTerminal:SingleDuct:VAV:Reheat` changes from `Reverse` to a new 8.6 option `ReverseWithLimits`.  Since `Reverse` is a valid choice in both 8.5 and 8.6, I can only assume that the behavior of `Reverse` in 8.5 is not equal to the behavior of `Reverse` in 8.6.

The problem is that OpenStudio does not translate `Reverse` to `ReverseWithLimits` between 1.12.0 and 1.13.0, which is apparently required to maintain the same simulation results.

The reason this manifests as a difference in loads and heating/cooling energy is that the airflow rates through the VAV terminal are different.

It looks like the [OpenStudio.idd doesnt' have the `ReverseWithLimits` option](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/resources/model/OpenStudio.idd#L10136), so you can't fix this in the GUI.

![image](https://cloud.githubusercontent.com/assets/2009290/19404510/a247f4c6-922b-11e6-8bea-e2021833faf4.png)

@kbenne I'm not sure if you've handled things like this in the version updater in the past?

**Comment by asparke2** [comment] 2016-10-14 23:01
@ethankheil Just read my last comment and you'll see what's going on.

## Workaround
Here is an [EnergyPlus Measure](https://github.com/asparke2/demo-measures/tree/master/vav_terminal_reverse_to_reverse_with_limits) that you can add into your workflow as a temporary fix for this issue.

It simply finds all `AirTerminalSingleDuctVAVReheat` objects where `Damper Heating Action` is `Reverse` and changes it to `ReverseWithLimits`.

It lives on my own repository because I don't think it's something that is generally useful enough to be on BCL.

**Comment by DavidGoldwasser** [comment] 2016-10-17 16:16
Diff of branch object between 8.5 IDF and 8.6 IDF (as generated by OpenStudio 1.12 and 1.13) The Component Branch Control Type field has been removed.

Branch,
   DHW Loop Supply Branch 2,               !- Name
-  ,                                       !- Maximum Flow Rate {m3/s}
   ,                                       !- Pressure Drop Curve Name
   Pipe:Adiabatic,                         !- Component Object Type 1
   Pipe Adiabatic 1,                       !- Component Name 1
   Node 48,                                !- Component Inlet Node Name 1
-  Node 49,                                !- Component Outlet Node Name 1
-  Passive;                                !- Component Branch Control Type 1
+  Node 49;                                !- Component Outlet Node Name 1

**Comment by kbenne** [comment] 2016-10-17 16:28
I think what we should do is add the option to the os idd and then do an os version translation and map all existing "Reverse" fields to "ReverseWithLimits"

**Comment by ethankheil** [comment] 2016-10-17 18:29
Thanks. I'll use the measure for now and I appreciate your help on this issue.

**Closed** 2016-12-05 21:08 UTC
Labels: component - Code, severity - Blocker
