### ISSUE TITLE
ventilation.setOutdoorAirFlowperPerson() accepts bad value in API

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1312] opened 2014-12-18 18:18 UTC
I had a measure where I had a formula to set the setOutdoorAirFlowperPerson. The formula had a divided by 0. The measure appeared to run without issue. But the simulation failed. In the GUI I see "-nan" instead of the double. It was a mistake in my code and I fixed it, but I would assume this would either fail in the measure or leave the value untouched. Seems odd to produce a non-double for the value.

Here is the object in the model

```
OS:DesignSpecification:OutdoorAir,
  {4d0a6dba-6738-4665-9e31-12723669e0ec}, !- Handle
  Office|Elec/MechRoom|DOE Ref 1980-2004|ASHRAE 169-2006-5A|OutdoorAir, !- Name
  Sum,                                    !- Outdoor Air Method
  -nan,                                   !- Outdoor Air Flow per Person {m3/s-person}
  0,                                      !- Outdoor Air Flow per Floor Area {m3/s-m2}
  ,                                       !- Outdoor Air Flow Rate {m3/s}
  0,                                      !- Outdoor Air Flow Air Changes per Hour {1/hr}
  ;                                       !- Outdoor Air Flow Rate Fraction Schedule Name
```

**Comment by asparke2** [comment] 2015-01-31 20:17
@DavidGoldwasser Closing because I could not reproduce this with Ruby 2.0.0:

```ruby
require 'openstudio'
model = OpenStudio::Model::Model.new
oa_spec = OpenStudio::Model::DesignSpecificationOutdoorAir.new(model)
# Tried 3 different ways
# val = Float::NAN
# val = 0.0/0.0
# val = 1/0
oa_spec.setOutdoorAirFlowperPerson(val)
puts oa_spec
```

**Closed by asparke2** 2015-01-31 20:17 UTC
Labels: component - Code, component - Measures, resolution - Can't Reproduce, severity - Normal Bug
