### ISSUE TITLE
with surface selected inspector pulldown for "Outside Boundary Object" shows both surfaces and sub-surfaces (Bugzilla #899)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#182] opened 2013-07-19 20:24 UTC
On 2012-09-13 09:32:56, @DavidGoldwasser wrote:

> Should just show surfaces.
> 
> Similar condition when sub-surface is selected, it should only show sub-surfaces.

**Comment by jmarrec** [comment] 2017-09-29 12:54
Cannot reproduce in OS 2.2.1

**Comment by DavidGoldwasser** [comment] 2017-10-02 23:52
@jmarrec this was just in the SketchUp Plugin, but we can probably close this anyway, since probably should have been minor issue vs nomral

**Closed by DavidGoldwasser** 2017-10-02 23:52 UTC
Labels: component - SketchUp, severity - Normal Bug
