### ISSUE TITLE
Model fails to run first time after loading in app

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#3500] opened 2019-04-22 20:19 UTC
In Mac builds of OS App - 2.8.0

1) Load model
2) Run model
3) Run fails
4) Click the run button a second time
5) Model runs

**Comment by DavidGoldwasser** [comment] 2019-04-22 21:59
I wasn't able to re-create this. In my case the model I loaded was a 2.7.0 model that I ran in 2.7.0 to test, then loaded and ran in 2.8.0

@ljbrackney when the simulation fails to run the first time, what is in the out.osw? I assume it isn't an eplus.out error but failed somewhere else in the workflow?

**Comment by jmarrec** [comment] 2019-05-14 15:49
I cannot reproduce it either. @ljbrackney can you provide more information? Otherwise let's close it

**Comment by ljbrackney** [comment] 2019-05-14 16:19
I think this may have been a result of working with a new OSM and a copy of an old model’s directory structure, which I copied and renamed to maintain measures in the workflow and supporting data.  Kind of a weird corner case, but certainly something triggered by a legit use case.

**Comment by jmarrec** [comment] 2019-05-14 17:53
@ljbrackney thanks for the info. Any chance you still have the offending model and companion directory?

**Comment by jmarrec** [comment] 2019-05-15 07:30
So I got the files from Larry (thank you!) along with instructions to reproduce. Basically:
* You have an old companion directory called `Model_A`
* You have a new model called `Model_B.osm` and which to use the same workflow (with measures, files, etc) as the old `Model_A.osm` did.

Rename directory `Model_A` to `Model_B`. Problem is that the workflow.osw still referenced the old model:

**workflow.osw**
```
{
   "created_at" : "20190306T165759Z",
   "seed_file" : "../Walmart_v17.osm",
   ...
}
```

**Closed** 2019-05-25 16:16 UTC
Labels: component - OS App, severity - Normal Bug
