### ISSUE TITLE
Geometry Editor Units Display

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2836] opened 2017-10-31 19:34 UTC
Geometry Editor seems to always show units as ft vs. m when you first go to the tab independent of what the units are in OS app.

In testing this I launched OS app (which always launches in SI units, but I didn't bother checking) and then I went to the geometry editor, set the grid value and started modeling assuming I was drawing in feet as the GUI showed, but in fact it was modeling meters. We should get the display in sync with what is being drawn, but beyond that might be nice to ask units up front since it can't be changed once you start drawing.

Here is screenshot of GUI showing feet
<img width="1230" alt="screen shot 2017-10-31 at 1 24 06 pm" src="https://user-images.githubusercontent.com/4857055/32244982-ef3d18c4-be3f-11e7-8c49-9a95d55e5ace.png">

Here is the resulting object, once converted to OSM
```
OS:Surface,
  {e6643c2e-4b19-4123-9848-4d574280fac0}, !- Handle
  ,                                       !- Name
  Floor,                                  !- Surface Type
  ,                                       !- Construction Name
  {33d39f15-2d68-482b-8ad5-fa515994e01a}, !- Space Name
  Ground,                                 !- Outside Boundary Condition
  ,                                       !- Outside Boundary Condition Object
  NoSun,                                  !- Sun Exposure
  NoWind,                                 !- Wind Exposure
  ,                                       !- View Factor to Ground
  ,                                       !- Number of Vertices
  0, 20, 0,                               !- X,Y,Z Vertex 1 {m}
  20, 20, 0,                              !- X,Y,Z Vertex 2 {m}
  20, 0, 0,                               !- X,Y,Z Vertex 3 {m}
  0, 0, 0;                                !- X,Y,Z Vertex 4 {m}
```

I had missed this little hint, while actively drawing the area shows unit of m^2
<img width="1226" alt="screen shot 2017-10-31 at 1 23 39 pm" src="https://user-images.githubusercontent.com/4857055/32244979-ec018514-be3f-11e7-8f43-df9b281b4dd7.png">

**Comment by macumber** [comment] 2018-01-18 17:50
Think this is duplicate of https://github.com/NREL/OpenStudio/issues/2731

**Comment by DavidGoldwasser** [comment] 2018-01-18 20:08
They are related but not duplicates. @ljbrackney is saying that OS App units and geometry units are not in sync with each other. I'm saying that even what shows in geometry editor for units (next to "spacing" at the top) isn't in sync with the units being drawn by geometry editor in main window (note the m^2 in area in 20x20 space)

**Closed** 2018-03-09 21:21 UTC
Labels: component - Geometry Editor, severity - Normal Bug
