### ISSUE TITLE
Slab and Basement works in my test, but not in GUI

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#889] opened 2014-03-06 17:35 UTC
When I run my test my IDF ground surfaces look like this.

BuildingSurface:Detailed,
  Surface 25,                             !- Name
  Floor,                                  !- Surface Type
  000 ExtSlabCarpet 4in ClimateZone 1-8,  !- Construction Name
  Thermal Zone: Space 105,                !- Zone Name
  OtherSideCoefficients,                  !- Outside Boundary Condition
  surfPropOthSdCoefBasementAvgFloor,      !- Outside Boundary Condition Object
  NoSun,                                  !- Sun Exposure
  NoWind,                                 !- Wind Exposure
  ,                                       !- View Factor to Ground
  ,                                       !- Number of Vertices
  12.192, 0, 0,                           !- X,Y,Z Vertex 1 {m}
  9.144, -3.048, 0,                       !- X,Y,Z Vertex 2 {m}
  3.048, -3.048, 0,                       !- X,Y,Z Vertex 3 {m}
  0, 0, 0;                                !- X,Y,Z Vertex 4 {m}

When I run the exact same model and measure in PAT it looks untouched

BuildingSurface:Detailed,
  Surface 25,                             !- Name
  Floor,                                  !- Surface Type
  000 ExtSlabCarpet 4in ClimateZone 1-8,  !- Construction Name
  Thermal Zone: Space 105,                !- Zone Name
  Ground,                                 !- Outside Boundary Condition
  ,                                       !- Outside Boundary Condition Object
  NoSun,                                  !- Sun Exposure
  NoWind,                                 !- Wind Exposure
  ,                                       !- View Factor to Ground
  ,                                       !- Number of Vertices
  12.192, 0, 0,                           !- X,Y,Z Vertex 1 {m}
  9.144, -3.048, 0,                       !- X,Y,Z Vertex 2 {m}
  3.048, -3.048, 0,                       !- X,Y,Z Vertex 3 {m}
  0, 0, 0;                                !- X,Y,Z Vertex 4 {m}

In both cases this is being made. Just not used when run through GUI run.

SurfaceProperty:OtherSideCoefficients,
  surfPropOthSdCoefBasementAvgWall,       !- Name
  0.0,                                    !- Combined Convective/Radiative Film Coefficient {W/m2-K}
  1.0,                                    !- Constant Temperature {C}
  1.0,                                    !- Constant Temperature Coefficient
  0.0,                                    !- External Dry-Bulb Temperature Coefficient
  0.0,                                    !- Ground Temperature Coefficient
  0.0,                                    !- Wind Speed Coefficient
  0.0,                                    !- Zone Air Temperature Coefficient
  scheduleOSCBasementWallSurfaceTemp,     !- Constant Temperature Schedule Name
  No,                                     !- Sinusoidal Variation of Constant Temperature Coefficient
  24;                                     !- Period of Sinusoidal Variation {hr}

![3-6-2014 10-31-01 am](https://f.cloud.github.com/assets/4857055/2348254/b4f9adaa-a555-11e3-821a-ee3568abd72f.png)

**Comment by macumber** [comment] 2015-03-18 04:00
@axelstudios this is assigned to you in pivotal, you still able to look at it?

**Comment by macumber** [comment] 2015-03-18 15:55
@axelstudios unless you are working on this i suggest we push it off until 1.8.0 or un-assign milestone

**Comment by axelstudios** [comment] 2015-06-11 17:37
Tested with David, unable to reproduce crash.

**Closed by axelstudios** 2015-06-11 17:37 UTC
Labels: In Progress, severity - Major Bug
