### ISSUE TITLE
Hard to change geometry preview dropdowns

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2994] opened 2018-02-09 17:33 UTC
It's hard to change the Render By and Show Story dropdowns in the Geometry Preview window. When the dropdown is open, I was unable to change the selection until I finally discovered you have to double-click on an item and then press enter. They should simply respond to a single-click.

**Comment by ljbrackney** [comment] 2018-02-09 19:16
Is this a duplicate of https://github.com/NREL/floorspace.js/issues/276?

**Closed** 2020-05-13 20:41 UTC
Labels: component - Geometry Editor, component - OS App, severity - Minor Bug
