### ISSUE TITLE
Update to Ubuntu 16.04

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2929] opened 2018-01-15 18:42 UTC

**Comment by macumber** [comment] 2018-01-15 18:42
Or wait for 18.04?

**Comment by jmarrec** [comment] 2018-01-26 10:30
As an Ubuntu 16.04 user, I can say it compiles just fine. 

The problem is the installer: wrong installation path, and a couple of outdated (or rather just too strict) dependencies. There are dependencies expected such as `libwxgtk3.0-0` (only available in Trusty = 14.04)  but in Xenial = 16.04) you can only find `libwxgtk3.0-0v5` or `libwxgtk3.0-dev` in official sources

Related issues: #2974, #2874

**Comment by jmarrec** [comment] 2019-02-05 21:40
This is fully working now, and will migrate to 18.04 as the preferred plaftorm once develop3 gets merged in (though I keep testing it with 16.04 and it works fine too).

**Closed by jmarrec** 2019-02-05 21:40 UTC
Labels: Developer Issue
