### ISSUE TITLE
Can't remove some SPMs via GUI because icons don't show

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1465] opened 2015-02-13 15:45 UTC
When you have the following SPMs on certain nodes, you can't remove them via the GUI because the icons don't show up:

On any node:
- SetpointManager:MultiZone:Humidity:Minimum
- SetpointManager:MultiZone:MinimumHumidity:Average

On the OA inlet node of the OA system:
- Every SPM type (yes, I know it makes no sense to put these there in the first place, but if you mistakenly drop one you should be able to get rid of it without deleting the whole OA system)

My guess is that the humidity ones don't show because they don't have icons (at least in the library), and that none of them show on the OA system OA inlet node b/c of something in the drawing logic.

Here is a screenshot illustrating the humidity case:
![image](https://cloud.githubusercontent.com/assets/2009290/6189694/d8efa1b6-b359-11e4-877e-acd7c38a3fca.png)

No icons in the library:
![image](https://cloud.githubusercontent.com/assets/2009290/6190055/89c0f01a-b35c-11e4-89d8-3e7f7246c51a.png)

![image](https://cloud.githubusercontent.com/assets/2009290/6190058/934286c6-b35c-11e4-8500-3410ebe7ca68.png)

And the OA system OA inlet node case:
![image](https://cloud.githubusercontent.com/assets/2009290/6190036/62f6f556-b35c-11e4-8bfe-cddc816f6157.png)

**Comment by MatthewSteen** [comment] 2015-07-30 16:27
The SetpointManagerSchedule also might be affected on plant loops...

https://unmethours.com/question/9816/setpoint-manager-symbol-lost-in-openstudio/

**Comment by MatthewSteen** [comment] 2016-06-01 23:02
Experiencing this in 1.11.4. It's also possible to end up with two SPMs on one node.

![image](https://cloud.githubusercontent.com/assets/8397034/15728592/a43610cc-281a-11e6-8c72-2c52f1e0b9ff.png)

**Comment by jmarrec** [comment] 2017-09-29 10:45
Still true OS 2.2.1

**Comment by jmarrec** [comment] 2018-01-12 15:22
Still true in OS 2.4.0

**Comment by jmarrec** [comment] 2018-07-26 10:57
This was clearly originally done by design: only the SPMs with controlVariable = Temperature are being drawn. (see [here](https://github.com/jmarrec/OpenStudio/blob/10b655b3a9cd616da3d36169df3eecf14da29833/openstudiocore/src/openstudio_lib/GridItem.cpp#L123) and [here](https://github.com/jmarrec/OpenStudio/blob/10b655b3a9cd616da3d36169df3eecf14da29833/openstudiocore/src/openstudio_lib/GridItem.cpp#L2463:L2563) for eg)


I'm not sure I understand the original logic behind this decision though, and yes not being able to delete the SPMs is really unfortunate, so I'll enable the drawing/deleting of these.

As far as the not drawing any SPMs on the OA node, I think we shouldn't even allow placing a SPM on the relief and the outdoor air node (when you have an AirloopHVACOutdoorAirSystem), so I'll disallow that too unless someone thinks otherwise.

**Comment by jmarrec** [comment] 2018-07-26 11:10
It just came to my attention that currently the base class method "SetpointManager_Impl::addToNode" only returns true if its basically on the supply side of an AirLoopHVAC, which makes sense since all SPMs are allowed on an AirLoopHVAC, *but only a subset on a PlantLoop.*

SetpointManagerScheduled::addToNode call that one, then check if it's a plantLoop and allow the SPM ANYWHERE on that plantLoop (cf [SetpointManagerScheduled.cpp#L92:L94](https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/model/SetpointManagerScheduled.cpp#L92:L94)). Other SPMs do check if it's at least the supply side of a plantLoop (cf [SetpointManagerOutdoorAirReset.cpp#L90:L9](https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/model/SetpointManagerOutdoorAirReset.cpp#L90:L94))

**I can't think of any applications where we would want a SPM:Scheduled on the demand side of a plantLoop, so I'm going to disallow it too, unless @kbenne or @asparke2 can think of one use case?**

![image](https://user-images.githubusercontent.com/5479063/43258948-f35833e0-90d4-11e8-8a3a-acb03dbd6d58.png)

**Comment by eringold** [comment] 2018-09-14 15:05
Still present in 2.6.0

**Comment by jmarrec** [comment] 2018-09-14 18:44
@eringold fixed in #3200, not merged yet

**Closed** 2018-11-08 18:19 UTC
Labels: component - OS App, severity - Normal Bug
