### ISSUE TITLE
SpaceType tab - Infiltration Design Flow Rate and Infiltration Leakage areas don't show in "My Model" (Bugzilla #1039)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#265] opened 2013-07-19 20:26 UTC
On 2013-01-09 22:03:08, @DavidGoldwasser wrote:

> Design spec outdoor air does show up in MyModel, but not Infiltration Design Flow Rate and Infiltration Leakage area objects. All of these show under "Library" but not "My Model". Seems they should follow the same.
> 
> quite a bit beyond the bug, but Matt felt this should be like other loads, and show up under the "Loads" tab. I know that isn't something we can touch for march.

**Comment by macumber** [comment] 2017-11-28 03:16
@jmarrec you marked this as can close.  The issue is still true, was your recommendation based on idea that these objects should not show up in the My Model section?  e.g. they should not be shared?

**Comment by jmarrec** [comment] 2017-11-28 09:07
@macumber I have to admit I don't know why I flagged this one as "can close". I was bound to make a mistake at some point, I did go through 700 issues at once. Should be an easy fix though, I'm on it.

**Comment by jmarrec** [comment] 2017-11-28 09:45
Yeah, I think it's because right now the SpaceInfiltrationDesignFlowRate is the object that references a Space or Space Type, and not the other way around like DesignSpecificationOutdoorAir.

From the idd

```
OS:SpaceType,
    [...]
    A6, \field Design Specification Outdoor Air Object Name

[...]

OS:Space,
    [...]
    A9, \field Design Specification Outdoor Air Object Name


[...]

OS:SpaceInfiltration:DesignFlowRate,
    [...]
    A3, \field Space or SpaceType Name
```

We could change this, but it wouldn't be a trivial change.

**Closed as completed** 2018-01-12 17:15 UTC
Labels: severity - Normal Bug
