### ISSUE TITLE
Show error or warning when DDY file has no design days

### ISSUE THREAD

**Issue by nealkruis** [NREL/OpenStudio#1672] opened 2015-06-02 20:56 UTC
Possibly related to #1562. @macumber?

See my comment under @asparke2's answer in this [Unmet Hours question](https://unmethours.com/question/1566/severe-error-caused-by-controller-mechanical-ventilation-openstudio-150/?comment=8264#comment-8264).

From a user's perspective, they only see EnergyPlus errors related to mechanical ventilation controllers.

**Comment by asparke2** [comment] 2015-06-02 20:58
@nealkruis You're correct, this is a duplicate of #1562.  We are working on a GUI change that will show all design days that are in the model so you can see when a ddy file is empty.

**Closed by asparke2** 2015-06-02 20:58 UTC

**Comment by nealkruis** [comment] 2015-06-02 21:04
@asparke2 there may be an important distinction between:
 - showing that there are zero design days and 
 - giving a user more information before they encounter the error as a problem with the mechanical ventilation controllers.

Does the GUI change address both of these?
