### ISSUE TITLE
OpenStudio crash with updated BCL measure where name changed

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1310] opened 2014-12-17 15:44 UTC
A user crashed OpenStudio app because they downloaded a updated BCL measure. I don't intentionally change display names of measures on BCL, but this happened because the OS app now changes the "name" field in the XML to a snake_case_name anytime I alter it and then Launch app. I try to fix on BCL by hand, but I missed this one. After the initial crash, the users didn't seem to experience the issue when re-starting.

@macumber I assigned this to you for the snake_case issue. I assume maybe this is related to updates need on BCL for where to get the display name from? Still it seems like OpenStudio shouldn't crash if the name is changed. 

cc: @asparke2 @axelstudios @evanweaver 

Here is the measure in question
https://bcl.nrel.gov/search/site/diagnostic

Here are some screenshots 

![kent_a](https://cloud.githubusercontent.com/assets/4857055/5473708/b44bc3da-85c8-11e4-8553-b380ff527ebe.png)

![kent_b](https://cloud.githubusercontent.com/assets/4857055/5473711/b870bd76-85c8-11e4-97de-8276a695ead4.png)

He saw something similar on AEDG fenestration measure.

**Comment by macumber** [comment] 2015-03-18 03:48
@axelstudios you still working on this for 1.7.0?

**Comment by macumber** [comment] 2015-03-18 15:56
@axelstudios this is probably the most important of the bugs assigned to you for 1.7.0, have you started to look at it?  it seems difficult to test.  if you can't get to it let's move to 1.8.0

**Comment by axelstudios** [comment] 2015-06-11 19:51
Unable to reproduce crash -- I uploaded a new measure, downloaded it, changed the `name` `class_name` & `display_name`, and redownloaded it.  There was no crash after redownloading, nor after relaunching PAT.

If anyone has a workflow to reproduce this, we can reopen.

**Closed by axelstudios** 2015-06-11 19:51 UTC
Labels: component - Measures, component - OS App, In Progress, severity - Blocker
