### ISSUE TITLE
App segfaults when opening a model with missing library data

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#3447] opened 2019-03-11 16:21 UTC
OpenStudio App segfaults when opening a model that relies on additional library data and that library has not been added a priori.  Expected behavior is to report the missing library as an error and halt the load process or open the add library dialog for the user to point to it before continuing.

**Comment by ljbrackney** [comment] 2019-03-11 16:35
![libraries](https://user-images.githubusercontent.com/2230150/54140489-f5f94480-43e0-11e9-961f-9224da852c09.jpg)

**Comment by macumber** [comment] 2019-03-11 17:59
This is odd, @jmarrec can you add this to the top of your 2.8.0 list?

@ljbrackney can you give a bit, more info about what you did?  Did you install 2.7.1 and these files were not there?  You added them manually and the crash went away?  I don't think you can configure libraries on a per OSM level.  I believe they are set in user preferences or suggested by the app.  There might be issues if you move back in version (e.g. from 2.7.2 to 2.7.1) because future OSM versions could not be opened.

**Comment by ljbrackney** [comment] 2019-03-11 18:02
1) Did a 2.7.1 install
2) Updated RUBYLIB in my .profile
3) Started App
4) Went to preferences and reset to standard libraries
5) Was able to load and run some old models
6) Received new model that was built with DEER 1985 and 2007 library definitions
7) App crashed on multiple load attempts
8) Added DEER 1985 and 2007 libraries in preferences
9) Model loads and simulates

**Comment by macumber** [comment] 2019-03-11 18:04
That is very odd, can you send the OSM via email?

**Comment by jmarrec** [comment] 2019-03-11 20:34
That's super strange. No model should rely on libraries, since what's happening when you drag from library to model is that the object is cloned to the user's model... it could be that one object doesn't correctly clone its resources though I don't see why it wouldn't segfault when libraries and readded.

I can investigate this first thing in the AM, please do send your offending OSM via private email @ljbrackney

**Comment by jmarrec** [comment] 2019-03-12 08:31
I'm going to need @ljbrackney 's file: I tried reproducing the above steps on my Ubuntu machine, but couldn't reproduce any segfault.

Also, what platform are you using? Mac if I remember correctly?

**Comment by DavidGoldwasser** [comment] 2019-04-19 19:08
Wondering step 7 (loading the model) could be crashing because of issue #3435. This will crash with otherwise valid models, if you try to open it too soon.

**Comment by jmarrec** [comment] 2019-05-13 09:11
@ljbrackney Could you send your file please?

**Comment by jmarrec** [comment] 2019-05-14 11:12
Can't reproduce on Ubuntu, tried 2.8.0 and 2.7.1.

Will try on mac.

**Comment by jmarrec** [comment] 2019-05-14 12:06
I am closing this issue since I cannot reproduce it.
We can reopen it if a new occurrence is found in the future.

**Closed by jmarrec** 2019-05-14 12:06 UTC
Labels: component - OS App, severity - Major Bug
