### ISSUE TITLE
Geometry Intersection Issue - Surface Shattering

### ISSUE THREAD

**Issue by Mkellyeng** [NREL/OpenStudio#3424] opened 2019-02-14 05:04 UTC
Summary: Intermittent intersection problem that erroneously subdivides many surfaces, and can cause parts of a surface to effectively be deleted.

If the intersection process would result in a surface having a hole, it uses some special logic to subdivide the surface, and thus avoid creating surfaces which otherwise couldn't be represented in EnergyPlus's coordinate format.
![hole_exception_demo](https://user-images.githubusercontent.com/46730121/52763025-2bbf3d80-306e-11e9-9be7-8e423d7726ae.PNG)

This works well in simple cases, however in larger buildings it can quickly cause some serious problems.
![shattertest_example](https://user-images.githubusercontent.com/46730121/52762991-0f230580-306e-11e9-9886-2cf1e64ebe0b.PNG)

Intersections can have this special logic applied even when they wouldn't result in holes being created in the surface.

Attached are a series of testing files, a simple geometry was created in Floorspace and imported into OpenStudio. This was repeated twice with identical inputs and process. The result was two different .osm's, that when viewed in sketchup are seen to have different intersecting patterns. It seems as though what's happening is the two top level surfaces are being intersected in different orders each time. If the middle surface is checked first, we have a hole formed, like in the initial test case. However, if the edge surface is checked first, it is correctly intersected, after which point the middle surface will no longer create a hole. 

ShatterTest01.png
![shattertest01](https://user-images.githubusercontent.com/46730121/52763218-0aab1c80-306f-11e9-8ea0-31b36d6f1514.PNG)

ShatterTest02.png
![shattertest02](https://user-images.githubusercontent.com/46730121/52763220-0bdc4980-306f-11e9-80d0-2b6b62d54ab7.PNG)

In practice, this issue causes some serious problems. In addition to bloating the model with tonnes of unnecessary surface, this problem has, in the past, completely roadblocked the geometry creation process by creating geometries that could not be imported (hanging forever on import)

Would it be possible to have the intersection process resolve hole-creating surfaces last?
That is to say, before executing the special logic that protects against forming holes, take a note of the surface, and move on, then come back to it later after all other intersections are resolved?

[Geometry Intersection Issue - Surface Shattering.zip](https://github.com/NREL/OpenStudio/files/2863377/Geometry.Intersection.Issue.-.Surface.Shattering.zip)

**Comment by jmarrec** [comment] 2021-06-08 10:36
Trying to reproduce with 3.2.0 (OS App v1.2.0-rc6, more or less)

Importing ShatterTest.json: empty model, go to Geometry Tab > Editor > FloorSpace > New > Open existing floorplan. THen just click "merge with current OSM" and look at results, showing story 1 only.

For reference, Json looks like this:

![image](https://user-images.githubusercontent.com/5479063/121170630-c2265700-c855-11eb-883e-7afdc71c3708.png)

## Test 1

![Test4](https://user-images.githubusercontent.com/5479063/121170912-20ebd080-c856-11eb-93fb-f3303a73e8e6.gif)

## Test 2

![image](https://user-images.githubusercontent.com/5479063/121170500-97d49980-c855-11eb-8078-8fb66707d6ae.png)


## Test 3

![image](https://user-images.githubusercontent.com/5479063/121170553-aae76980-c855-11eb-83ad-e82a9fb04923.png)

## Test 4

![image](https://user-images.githubusercontent.com/5479063/121170666-ce121900-c855-11eb-96e4-e2253ddb693b.png)


Probably fixed via #4221

**Closed by jmarrec** 2021-06-08 10:36 UTC
Labels: component - Utilities Geometry, severity - Normal Bug

**Comment by Mkellyeng** [comment] 2021-06-10 01:30
This ticket touched on two issues, the surface 'shattering' behaviour, and the inconsistent geometry generation.
Based on your 4 tests, it looks like the inconsistency has been resolved (awesome!), but the shattering behaviour is still present.

Reading through #4221 there's a lot of great and interesting detail on resolving the shattering issue, but it seems to still be present, according to the above?

**Comment by jmarrec** [comment] 2021-06-10 11:02
@Mkellyeng I don't have your "large model" shown above AFAIK. Try it out with 3.2.0 and see if it improved.

**Comment by Mkellyeng** [comment] 2021-06-18 04:03
I dug up that original model and imported it into Open Studio 3.2, reran it. Still getting similar shattering behaviour.
![image](https://user-images.githubusercontent.com/46730121/122503623-260e0400-d03c-11eb-9295-26fc278032e9.png)

Interestingly you tell a few of the first spaces to be intersected, based on the intersection pattern (red circles)
![image](https://user-images.githubusercontent.com/46730121/122504355-82bdee80-d03d-11eb-8eda-899accc9fd79.png)

For reference I've attached the original json file, and the 3.2.0 .osm
[Uploading Shattering Test - Large Model.zip…]()
