### ISSUE TITLE
EnergyPlus object "TableMultivariableLookup" deprecated in EnergyPlus v9.2.0, but not in OpenStudio v2.9.0

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/OpenStudio#3748] opened 2019-10-30 15:43 UTC
OpenStudio v2.9.0 API documents the "TableMultivariableLookup" object as still available in OS v2.9.0. It appears the forward translator (osm to idf) method does not produce idf files compatible with EnergyPlus v9.2.0, which must translate this object to the more generalized and new EnergyPlus supported object "TableLookup".

Related to this [EnergyPlus issue](https://github.com/NREL/EnergyPlus/issues/7588), the .osc files representing performance data associated with indoor and outdoor VRF units that are currently stored on the BCL represent this data using the Table:MultivariableLookup OS object, which cannot be correctly translated into a suitable form by the .osm to idf  forward translator, for use by EnergyPlus v9.2.0.

**Comment by jmarrec** [comment] 2019-11-05 17:15
This is the same issue as the #3742 one. Basically it was decided that OS would keep its existing API and handle writing the new TableLookup objects during FT. The problem is that one enum value appears wrong which was E+ fatal out as reported in #3742. 

Closing this one in favor of #3742, feel free to reopen @chrisbalbach if I have missed part of your question there.

**Closed by jmarrec** 2019-11-05 17:15 UTC
