### ISSUE TITLE
Bug Report - Thermostat

### ISSUE THREAD

**Issue by lrebello** [NREL/OpenStudio#1917] opened 2015-10-23 14:08 UTC
Today I was running a simulation on OpenStudio and I faced a bug when I removed one of the thermostats from a specific thermal zone. OpenStudio took out all the thermostats that had the same name, eventhough they were in different thermal zoner.<br><br>To fix that, I had to open the SketchUp file and select all thermal zones I wanted the thermostat back, click on the tab Set Attributes for Selected Spaces, and then change the Set Parent Thermal Zone's - Thermostat to the thermostat I wanted. Hopefully it worked.<br>
<br><br>
<a href="http://img.gforum.tv/ver.php?i=09e4a555b9d9464c1390fd199729a9a6415ead57.jpg"><img src="http://img.gforum.tv/img/09e4a555b9d9464c1390fd199729a9a6415ead57.jpg" border="0" /></a>
<br><br>
<a href="http://img.gforum.tv/ver.php?i=1b6e89d0b54641324275e4bec3b1d296b858088f.jpg"><img src="http://img.gforum.tv/img/1b6e89d0b54641324275e4bec3b1d296b858088f.jpg" border="0" /></a>

**Comment by DavidGoldwasser** [comment] 2015-10-23 14:53
Will close this as a duplicate of issue #123

**Closed** 2015-10-23 14:53 UTC
Labels: resolution - Duplicate

**Comment by lrebello** [comment] 2015-10-24 17:28
Understood. Thanks for letting me know

2015-10-23 12:53 GMT-02:00 David Goldwasser <notifications@github.com>:
