### ISSUE TITLE
Files won't open with OS App 1.8.3

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1783] opened 2015-08-19 16:01 UTC
These files open fine with 1.8.0, but won't open in 1.8.3.  The final.osm model was created using the prototype measure, so it might be an issue with the measure code.  The other model is a user model from unmet hours, and appears to have been created with 1.8.1.  The app just crashes with no message.

**Comment by asparke2** [comment] 2015-08-19 16:10
Files are [here](https://github.com/NREL/OpenStudio-files/tree/master/Git%20Issue%20Files/Issue%201783)

**Comment by asparke2** [comment] 2015-08-19 16:11
@evanweaver not sure if you or @macumber are the right person to figure this one out.

**Comment by evanweaver** [comment] 2015-08-19 16:12
@asparke2 does the app just lock up, or does it seg fault?

**Comment by evanweaver** [comment] 2015-08-19 16:13
@asparke2 @macumber this is very similar to one that I am currently looking at from Matt Steen.

**Comment by asparke2** [comment] 2015-08-19 16:15
It does this:

![image](https://cloud.githubusercontent.com/assets/2009290/9361943/2897b3a4-465b-11e5-8d28-2babca60d6ac.png)

**Comment by evanweaver** [comment] 2015-08-19 16:15
OK, looks to be the same as Matt's bug.

**Comment by axelstudios** [comment] 2015-08-19 20:11
Duplicate of #1767

**Closed by axelstudios** 2015-08-19 20:11 UTC
Labels: severity - Blocker
