### ISSUE TITLE
Copy Selected Object Disabled in Schedules - 1.4.0

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#1214] opened 2014-09-25 21:37 UTC
![os 140 schedules](https://cloud.githubusercontent.com/assets/8397034/4412735/0d6b5272-44fc-11e4-8980-773d56c93585.jpg)

**Comment by asparke2** [comment] 2015-01-31 21:08
Closing as duplicate of https://github.com/NREL/OpenStudio/pull/1371

**Closed by asparke2** 2015-01-31 21:08 UTC
Labels: component - OS App, severity - Major Bug
