### ISSUE TITLE
Open in ResultsViewer doesn't work on mac

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#1725] opened 2015-07-15 18:52 UTC
The _Open ResultsViewer for Detailed Reports_ button in OpenStudio doesn't correctly launch ResultsViewer on mac - the app launches, but the sql data doesn't load.
@macumber

**Comment by DavidGoldwasser** [comment] 2015-08-12 17:18
You can still manually load the SQL file on mac, it just doesn't load for you.

**Comment by axelstudios** [comment] 2015-08-12 17:38
I think the problem is [here](https://github.com/NREL/OpenStudio/blob/3afb112b5ec80e791583c51be16121405eaff99b/openstudiocore/src/openstudio_lib/ResultsTabView.cpp#L153).

It has something to do with the command that is passed to ResultsViewer, and the temporary copy argument.  IIRC, passing the command on the command line worked, but that needs to be reverified

**Comment by amirroth** [comment] 2016-07-28 14:09
The problem is that the eplusout file doesn't have the .sql extension on it. If you go into the temp folder and rename the file manually, it works.

**Comment by kbenne** [comment] 2017-04-11 16:17
This was supposed to be addressed in [this commit](https://github.com/NREL/OpenStudio/commit/be6d336926fe9d45f48ecf80bd02cce1bf98bd7e). 

The work was done under a duplicate issue number [here](https://github.com/NREL/OpenStudio/issues/2525)

Rumor has it that the issue is still lurking for someone, so the fix needs more verification.

**Comment by macumber** [comment] 2018-01-13 17:13
Closed as we moved to DView

**Closed by macumber** 2018-01-13 17:13 UTC
Labels: component - OS App, severity - Normal Bug
