### ISSUE TITLE
No example model or measures in installer for users to play with

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#918] opened 2014-03-20 16:44 UTC
This came up with Stephen Roth, seems like a user should get some models and an measures in the installer that they can play with right away

**Comment by pachi** [comment] 2015-11-15 16:02
It also allows to check if everything works ok even at a very basic level with a model that is supposed to work.
Having a set of examples that could be made to work like a test suite would be even better.

**Comment by jmarrec** [comment] 2017-09-29 11:40
duplicate of #1431

**Closed** 2018-01-13 20:59 UTC
Labels: Enhancement Request, component - Installer/Platform
