### ISSUE TITLE
1.10.5 closes after apply measure now

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#2155] opened 2016-03-16 15:52 UTC
Steps to reproduce:

1. Navigate to Thermal Zone tab
2. Apply Measure Now
3. Accept Changes
4. Click a string field, e.g. thermal zone name or zone equipment

Model will unexpectedly close. May be related to the measure I ran which renames zone equipment based on zone name, which I can provide if needed.

**Comment by ljbrackney** [comment] 2016-03-16 16:00
I don't believe this is a general issue w/ apply now, as I've been successfully using it with the AEDG measures on my test models.  It might be specific to your zone equipment measure.

**Comment by kbenne** [comment] 2016-03-16 16:02
Send the measure and the model and I'll see if i can get a call stack.

**Comment by MatthewSteen** [comment] 2016-03-16 16:06
Also, the changes do not appear in the Thermal Zone tab until navigating to another one and returning to it.

**Comment by kbenne** [comment] 2016-03-16 18:30
Weird. I was able to reproduce this and get a call stack. Switching tabs and coming back to the zones tab avoids the issue, but what is weird is why this works, because the whole model reloads after the apply measure now anyway. I'm still trying to work this out.

**Comment by MatthewSteen** [comment] 2016-03-16 18:33
Yeah, seems like the AMN function broke somehow.

**Comment by macumber** [comment] 2016-03-16 19:14
Might be related to https://github.com/NREL/OpenStudio/issues/2005 or https://github.com/NREL/OpenStudio/issues/1956

**Comment by kbenne** [comment] 2016-03-16 19:26
I wont go into the details of the call stack, but what I see gives me reason to believe this will impact any tab that has an inspectable item that changes in the measure.

**Comment by kbenne** [comment] 2016-03-16 19:27
I'm evaluating our reload code. I think that has the answer because switching tabs or closing and reopening the model goes fine.

**Closed** 2016-03-17 19:42 UTC
Labels: In Progress
