### ISSUE TITLE
SketchUp Inspector does not properly create ThermalZone

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#1667] opened 2015-05-27 17:32 UTC
https://unmethours.com/question/8069/openstudio-application-crash-when-clicking-on-facility-tab/

ThermalZone instances created in SektchUp do not have the required ZoneHVACEquipmentList or PortList that are normally created by the ThermalZone constructor.

**Comment by macumber** [comment] 2015-05-27 17:35
Changed to blocker since this causes a crash when clicking on facility tab

**Comment by macumber** [comment] 2015-05-27 17:35
Adding user file to files repo

**Comment by macumber** [comment] 2015-06-02 19:42
@kbenne here is the magic that fixes up zones added using the plugins inspector:

https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/ThermalZone.rb#L62

**Comment by kbenne** [comment] 2015-06-02 19:44
@macumber  Who calls ```check_model_object``` and when?  It seems like one explanation might be that events to trigger that method are not happening deterministically.

**Comment by macumber** [comment] 2015-06-02 20:02
It's quite a call stack:

Kicked off here:
https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/ruby/openstudio/sketchup_plugin/lib/watchers/PluginModelWatcher.rb#L55

Goes here:
https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/ModelInterface.rb#L1026

Then here:
https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/ThermalZone.rb#L39

Then I think this gets called when the object is drawn:
https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/ruby/openstudio/sketchup_plugin/lib/interfaces/ThermalZone.rb#L62

So yes it is possible something goes wonky

**Comment by DavidGoldwasser** [comment] 2015-06-15 15:49
On a fresh model check_model_object does appear to get called. (I checked making new zone via the inspector, a user script, and the space attributes dialog). Here is the resulting model object. 

OS:ThermalZone,
  {bebcb225-dd00-41b1-afd9-2b9bc502c121}, !- Handle
  Thermal Zone 1,                         !- Name
  ,                                       !- Multiplier
  ,                                       !- Ceiling Height {m}
  ,                                       !- Volume {m3}
  ,                                       !- Floor Area {m2}
  ,                                       !- Zone Inside Convection Algorithm
  ,                                       !- Zone Outside Convection Algorithm
  ,                                       !- Zone Conditioning Equipment List Name
  {b2b6486b-3838-42c2-bb22-e2ad587fcd3a}, !- Zone Air Inlet Port List
  {f9529e71-c875-467f-aca0-026cb3dec628}, !- Zone Air Exhaust Port List
  {88cc17b4-44f1-400c-8e4c-c7247ed12586}, !- Zone Air Node Name
  ,                                       !- Zone Return Air Node Name
  ,                                       !- Primary Daylighting Control Name
  ,                                       !- Fraction of Zone Controlled by Primary Daylighting Control
  ,                                       !- Secondary Daylighting Control Name
  ,                                       !- Fraction of Zone Controlled by Secondary Daylighting Control
  ,                                       !- Illuminance Map Name
  {39a4ca5a-8bb6-4bb6-bf95-933428c2a4e4}, !- Group Rendering Name
  ,                                       !- Thermostat Name
  No,                                     !- Use Ideal Air Loads
  ;                                       !- Humidistat Name

OS:Node,
  {376d54f6-bea4-4b1f-8f7a-32926035ba86}, !- Handle
  Node 1,                                 !- Name
  {88cc17b4-44f1-400c-8e4c-c7247ed12586}, !- Inlet Port
  ;                                       !- Outlet Port

OS:Connection,
  {88cc17b4-44f1-400c-8e4c-c7247ed12586}, !- Handle
  {fed54bd8-57ba-4dff-91a5-ca6dcbea7c5f}, !- Name
  {bebcb225-dd00-41b1-afd9-2b9bc502c121}, !- Source Object
  11,                                     !- Outlet Port
  {376d54f6-bea4-4b1f-8f7a-32926035ba86}, !- Target Object
  2;                                      !- Inlet Port

OS:Rendering:Color,
  {39a4ca5a-8bb6-4bb6-bf95-933428c2a4e4}, !- Handle
  Rendering Color 59,                     !- Name
  147,                                    !- Rendering Red Value
  112,                                    !- Rendering Green Value
  219;                                    !- Rendering Blue Value

OS:PortList,
  {b2b6486b-3838-42c2-bb22-e2ad587fcd3a}, !- Handle
  Port List 1,                            !- Name
  {bebcb225-dd00-41b1-afd9-2b9bc502c121}; !- HVAC Component

OS:PortList,
  {f9529e71-c875-467f-aca0-026cb3dec628}, !- Handle
  Port List 2,                            !- Name
  {bebcb225-dd00-41b1-afd9-2b9bc502c121}; !- HVAC Component

OS:Sizing:Zone,
  {31200c6e-a696-4ba9-91a2-e55a405cb31d}, !- Handle
  {bebcb225-dd00-41b1-afd9-2b9bc502c121}, !- Zone or ZoneList Name
  14,                                     !- Zone Cooling Design Supply Air Temperature {C}
  40,                                     !- Zone Heating Design Supply Air Temperature {C}
  0.0085,                                 !- Zone Cooling Design Supply Air Humidity Ratio {kg-H2O/kg-air}
  0.008,                                  !- Zone Heating Design Supply Air Humidity Ratio {kg-H2O/kg-air}
  ,                                       !- Zone Heating Sizing Factor
  ,                                       !- Zone Cooling Sizing Factor
  DesignDay,                              !- Cooling Design Air Flow Method
  ,                                       !- Cooling Design Air Flow Rate {m3/s}
  ,                                       !- Cooling Minimum Air Flow per Zone Floor Area {m3/s-m2}
  ,                                       !- Cooling Minimum Air Flow {m3/s}
  ,                                       !- Cooling Minimum Air Flow Fraction
  DesignDay,                              !- Heating Design Air Flow Method
  ,                                       !- Heating Design Air Flow Rate {m3/s}
  ,                                       !- Heating Maximum Air Flow per Zone Floor Area {m3/s-m2}
  ,                                       !- Heating Maximum Air Flow {m3/s}
  ,                                       !- Heating Maximum Air Flow Fraction
  ,                                       !- Design Zone Air Distribution Effectiveness in Cooling Mode
  ;                                       !- Design Zone Air Distribution Effectiveness in Heating Mode

OS:ZoneHVAC:EquipmentList,
  {8f45e834-3bff-45d6-9172-3d8d0342215b}, !- Handle
  Zone HVAC Equipment List 1,             !- Name
  {bebcb225-dd00-41b1-afd9-2b9bc502c121}; !- Thermal Zone

**Comment by DavidGoldwasser** [comment] 2015-06-15 15:55
Deleting a thermal zone via the inspector does seem to orphan an OS:Connection object

OS:Connection,
  {88cc17b4-44f1-400c-8e4c-c7247ed12586}, !- Handle
  {fed54bd8-57ba-4dff-91a5-ca6dcbea7c5f}, !- Name
  ,                                       !- Source Object
  11,                                     !- Outlet Port
  ,                                       !- Target Object
  2;                                      !- Inlet Port

**Comment by DavidGoldwasser** [comment] 2015-06-15 16:13
@macumber and @kbenne Below is what the thermal zone looks like in the user file. I can't reproduce this in a new file. @macumber my only thought is that SketchUp was in a bad state where observers were not working as expected (e.g. failed intersect)? Does that seem possible.

I could disable the new and delete feature for thermal zones in the inspector, but I have my doubts that is the cause. There are 185 spaces in the model and they are all assigned to the one zone in the model. That was likely done with the space attributes tool and not the inspector.

@macumber,if we do want to disable adding zones can you point me to the file to alter visibility of inspector objects? I've edited that before but it's been a long time. I assume I should also disable deleting zone due to the orphan objects left behind. Purge unused is already disabled. 

OS:ThermalZone,
  {5c338323-97c4-4c01-b63a-60d4eb353905}, !- Handle
  Thermal Zone 1,                         !- Name
  ,                                       !- Multiplier
  ,                                       !- Ceiling Height {m}
  ,                                       !- Volume {m3}
  ,                                       !- Floor Area {m2}
  ,                                       !- Zone Inside Convection Algorithm
  ,                                       !- Zone Outside Convection Algorithm
  ,                                       !- Zone Conditioning Equipment List Name
  ,                                       !- Zone Air Inlet Port List
  ,                                       !- Zone Air Exhaust Port List
  ,                                       !- Zone Air Node Name
  ,                                       !- Zone Return Air Node Name
  ,                                       !- Primary Daylighting Control Name
  ,                                       !- Fraction of Zone Controlled by Primary Daylighting Control
  ,                                       !- Secondary Daylighting Control Name
  ,                                       !- Fraction of Zone Controlled by Secondary Daylighting Control
  ,                                       !- Illuminance Map Name
  ,                                       !- Group Rendering Name
  ,                                       !- Thermostat Name
  ,                                       !- Use Ideal Air Loads
  ;                                       !- Humidistat Name

**Comment by DavidGoldwasser** [comment] 2015-06-15 18:48
@kbenne I'll close this and then assign story in Pivotal and Git pull request to you.

**Closed by DavidGoldwasser** 2015-06-15 18:48 UTC
Labels: component - SketchUp, In Progress, severity - Blocker
