### ISSUE TITLE
Can't add OS:MaterialRoofVegitation to a construction (Bugzilla #562)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#82] opened 2013-07-19 20:22 UTC
On 2012-03-05 10:28:06, @DavidGoldwasser wrote:

> User identified this, I confimred it as well. Thought maybe had restrictions on outside layer, or single layer construction, but didn't ever see this in the material pulldown.
> https://openstudio.nrel.gov/forums/openstudio-plug-google-sketchup/general-discussion/green-roof-material-vegetation-constructio#comment-1061
> 
> I would assume this bug extends outside of the plugin to other apps.

**Comment by DavidGoldwasser** [comment] 2015-02-01 22:44
duplicate of #1317

**Closed by DavidGoldwasser** 2015-02-01 22:44 UTC
Labels: component - OS App, component - SketchUp, severity - Major Bug
