### ISSUE TITLE
Cloning ScheduleRule results in odd behavior

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1279] opened 2014-11-06 22:51 UTC
Need to add some tests around this

**Comment by asparke2** [comment] 2015-01-31 20:52
@macumber is this only an issue when cloning a rule independently of cloning a schedule?  If so, please change severity to Normal.  If it affects cloning a schedule, keep at Major because it will show up in 1.7.0 when schedule copying is enabled in GUI.

**Comment by jmarrec** [comment] 2021-06-07 09:19
I'm going to close this for lack of information to reproduce. (I suspect the behavior is that if you clone a scheduleRule and then try to assign it to another scheduleruleset, then it is cloned a second time)

**Closed by jmarrec** 2021-06-07 09:19 UTC
Labels: component - Model, severity - Normal Bug
