### ISSUE TITLE
Control For Outdoor Air Field Not Initialized In AirTerminal Causes Crash

### ISSUE THREAD

**Issue by pflaumingo** [NREL/OpenStudio#1985] opened 2015-12-03 18:47 UTC
When creating a new Empty Air Loop in the OpenStudio app and adding an OS:AirTerminal:SingleDuct:VAV:Reheat the Control For Outdoor Air field is not defaulted to Yes or No. When attempting to run it fails almost instantly, but no error is given and there is nothing in the output files, however, when clicking on the measures tab an unhandled exception is thrown pointing to the issue as pictured:

![outdoorairexception](https://cloud.githubusercontent.com/assets/15233892/11570125/73a7d340-99aa-11e5-8c0e-e21f94dbbbd8.PNG)

The issue is that the GUI displays a default value, but the .osm file does not have a value:

![outdoorairfield](https://cloud.githubusercontent.com/assets/15233892/11570249/0f4cf9b0-99ab-11e5-847c-7cbcb4118487.PNG)

Manually setting the Control For Outdoor Air Field fixes the issue

**Comment by kbenne** [comment] 2015-12-03 18:50
What is the OS version your model started as and the version you are running it in? This is a new features and there is supposed to be a version translator rule populating this required field to a default value. Apparently it isn't working in your case. I'll definitely need to identify the cause and fix this for 1.10. In the mean time edit your osm file directly.

**Comment by pflaumingo** [comment] 2015-12-04 19:18
It was started in version 1.9.3 and upgraded to 1.9.5. I edited the .osm directly and it worked fine. What I did notice is that if I create an air loop, add a thermal zone and an air terminal without manually setting the control for outdoor air then each subsequent air terminal also won't have a default value. However, if I manually change the first air terminal to set the control for outdoor air before adding additional air terminals then when I do add the subsequent air terminals they will have the control for outdoor air field defaulted to the value of the first air terminal. I'm guessing this is intentional behaviour, but thought adding a bit of behavioral detail may help figuring out the root cause.

**Comment by kbenne** [comment] 2015-12-04 19:23
yes the behavior you see is intentional. OS is guessing that you want the same kind of terminal serving all of the zones so it clones the one you have.

I've got this figured out. I put the version translation logic in the wrong version translate function therefore the newly required field is not inserted properly. A fix is in process.

**Comment by kbenne** [comment] 2015-12-04 20:27
@pflaumingo I'd like to use you to verify this fix by sending you an installer package. Will that work for you?

**Comment by pflaumingo** [comment] 2015-12-04 21:18
Yup, that's fine. Send over a download link and I'll check it out.

**Comment by kbenne** [comment] 2015-12-04 22:43
@pflaumingo sent you a link.

**Comment by pflaumingo** [comment] 2015-12-07 17:18
@kbenne the installer package received fixed the above issue. The 'Control For Outdoor Air' field defaults to 'No' on AirTerminals.

**Closed** 2015-12-07 17:27 UTC
Labels: In Progress, severity - Blocker
