### ISSUE TITLE
Simulation Settings Tab - Minor bugs (Bugzilla #997)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#235] opened 2013-07-19 20:26 UTC
On 2012-12-11 09:18:26, @DavidGoldwasser wrote:

> I haven't done much with this yet but did notice a few things.
> 1. When you first make a new file and go to the "Run Period Date Range" for the start date where it says "January 1st"; and click the pulldown it takes you to December vs. January. If you cancel out without choosing a date, you end up with Dec 31st for start and finish. If then go and change the month and pick a date, and repeat the process, the month and day sticks to what I chose vs. jumping to December 31st.
> 2. EnergyPlus lets me span January 1st on a run (for example using a start date of July 1st, and a finish date of June 1st. The GUI here doesn't let me do that, is that by design?
> 3. When you click the start or end date to bring up a calendar I can see an up/down arrow for the year but it doesn't function.
> 4. When you click the start or end date to bring up a calendar, there is a functioning pulldown area for the month, but the arrow blocks some of the text for the name of the month.
> 5. Under the "Simulation Control" section it would be great to have a pulldown for "Solar Distribution" with the allowable terms. This would be consistent with other areas in the app where the user must choose from a list. (more enhancement than bug, but thought I would document here.)

On 2012-12-11 09:21:22, @DavidGoldwasser wrote:

> 1. one more small thing. Under "Sizing Parameters" the term I'm use to heating that also matches the object name would be "Heating Sizing Factor" and "Cooling Sizing Factor". Someone could be confused that this is some sort of hard sizing vs. a safety factor applied to calculated sizing.

On 2012-12-12 08:19:36, @macumber wrote:

> I can confirm that 2) in David's list is a valid thing to do in E+.  However, I'm not sure we want to try to support that yet (e.g. make sure our whole tool chain supports it).  Maybe this is a future enhancement rather than part of this bug?
> 
> Number 5) does seem like a serious bug to me and should be fixed.

On 2012-12-13 10:32:35, @DavidGoldwasser wrote:

> Created an attachment (id=242)
> screenshot showing overlapping text
> 
> Just did a new build and saw items 5 & 6 were fixed. Although it looks like fix to item 6 produced overlapping text where it previously had been truncated. There is a lot of real-estate to the right, maybe just space out 2nd column of text. I see this in the "Simulation Control" and "Heat Balance Algorithm" sections.

On 2012-12-13 10:35:17, @DavidGoldwasser wrote:

> Sorry, one more thing. On the fix for item 5, the field is so narrow that you can't really see enough to know what you picked. Making that wider (maybe twice as wide as it is now, or as long as longest option) would be good.

On 2012-12-17 08:46:07, @DavidGoldwasser wrote:

> https://www.pivotaltracker.com/story/show/40397991
> 
> The ticket above addresses items 1,5, and 6.
> 
> 2,3, & 4 are still valid, but can be fixed post 0.10.0.

On 2012-12-17 13:12:18, @DavidGoldwasser wrote:

> Just as a note, when we do fix/add item # 2 bug 78 may rear its head. This is results viewer bug for spanning a year on a simulation. Ran across this on the release notes.

Original attachments:
- SimSettings1213_a.png (ID 242)

**Comment by evanweaver** [comment] 2015-03-10 15:56
@DavidGoldwasser your original attachment is not available, so I am unable to compare it to the GUI's current state. Please verify that you still have the above concerns. If you still have a desire for some GUI changes, we need to have @marj-schott review and approve them, prior to me working on them.

**Comment by DavidGoldwasser** [comment] 2015-03-11 18:36
@evanweaver the three listed below are still valid, although I will admit 3 and 4 are super trivial as far as importance. @macumber is there any reason we are not supporting item 2 (wrap around year)?

2. EnergyPlus lets me span January 1st on a run (for example using a start date of July 1st, and a finish date of June 1st. The GUI here doesn't let me do that, is that by design?

3. When you click the start or end date to bring up a calendar I can see an up/down arrow for the year but it doesn't function.

4. When you click the start or end date to bring up a calendar, there is a functioning pulldown area for the month, but the arrow blocks some of the text for the name of the month.

**Comment by evanweaver** [comment] 2018-01-12 17:35
Closed as remaining issues are "super trivial". Please open a new bug if warranted.

**Closed by evanweaver** 2018-01-12 17:35 UTC
Labels: component - OS App, severity - Minor Bug
