### ISSUE TITLE
OpenStudio CLI measure update xml error

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/OpenStudio#3790] opened 2019-11-26 19:25 UTC
When I try to use the openstudio measure -u command, I get the following error:

```
'Unable to extract OpenStudio::Measure::OSMeasure object from
 C:/Users/mdahlhau/Documents/GitHub/NREL/la100-comstock/resources/measures/set_service_water_heating_template/measure.rb.
The script should contain a class that derives from OpenStudio::Measure::OSMeasure 
and should close with a line stating the class name followed by .new.registerWithApplication.'
```

The measure is of class `OpenStudio::Measure::ModelMeasure`, which isn't recognized.  I've encountered this many times since the v2.9.0 release.  @DavidGoldwasser have you encountered it too?

**Comment by DavidGoldwasser** [comment] 2019-11-26 21:19
I have not seen that specific error before but I have seen other xml update failures. My not very elegant solution has been to make a new clean measure. Take the UUID from your measure and past it in the new XML. Then copy all of the XML code from the new measure into your measure. Throw away the new measure you made, and try to update the measure.xml again.

@mdahlhausen have you just seen this in the com_stock measure repo, or somewhere else as well?

**Comment by mdahlhausen** [comment] 2019-11-26 21:58
@mdahlhausen I've seen it in many measures in many repos with the newer release.

**Comment by jmarrec** [comment] 2019-12-02 14:32
@mdahlhausen Could you point to somewhere where we could find a non updated file that would reproduce this error please?

**Comment by tijcolem** [comment] 2019-12-13 17:28
Closing and will reopen if we can obtain a supporting file to reproduce the error.

**Comment by mdahlhausen** [comment] 2020-04-27 23:34
I'm still having this error.  I can't give a specific file it occurs in, because it occurs in all my measures - old and new.
[Here are some measure files](https://github.com/NREL/ComStock/tree/develop/resources/measures)

Some more information:
- I get this error in the .xml.  When I delete the error line in the .xml and run it a second time it is fine.
- possibly related to the README?  README changes erase anything in the README and if I discard those changes, the error shows up again when I run the .xml updater
- Note that the warning is referring to a missing OSMeasure class.  These are from class ModelMeasure.  So perhaps this .xml updater was made before the measure class updates, and doesn't recognize the new naming convention?

**Comment by DavidGoldwasser** [comment] 2020-11-11 02:25
I just saw this on mac on two new measures I made. Once I cleared the error out, it seems fine for now.

**Comment by DavidGoldwasser** [comment] 2021-02-02 17:27
@mdahlhausen I can't reproduce this anymore with 3.1.0. If you see this again can you let me know. I was going to test the measure in your link but it isn't there anymore. I did only test on model measure (not E+ or reporting) but I would expect similar behavior across those. I tried introducing error to arguments method, outside of methods or just a fake error added ot the XML by hand. In all cases running `openstudio measure -u` cleared the error once the measure code was corrected.

**Closed by DavidGoldwasser** 2021-02-02 17:27 UTC
Labels: component - CLI, severity - Normal Bug

**Comment by mdahlhausen** [comment] 2021-02-02 17:55
yeah, I'm not seeing it anymore either.
