### ISSUE TITLE
Install C++ SDK

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#3729] opened 2019-10-14 17:17 UTC
The purpose of this task is to make the relationship between the OpenStudio and OpenStudioApplication projects as frictionless as possible. To accomplish this goal we want to develop a formal openstudio C++ SDK. Here are specific tasks:

1. Create a single openstudio.dll that has all of the C++ API, including OS Model and OS utilities to name a few. Refer to the none ruby objects linked into the openstudio.exe for a complete list.
2. Create install commands for the openstudio.dll as well as all "public" header files. This will be challenging because there are a lot of header files and it is not clear which should be public. We probably need to start with all of them and then reduce from there.
3. Generate a cmake exports file that is both installed and is also available from the openstudio build tree so that consuming projects like OpenStudioApplication can use the exported openstudio dll target. https://cmake.org/cmake/help/v3.0/command/export.html
4. Create an example project that uses the OpenStudio SDK. Compile and link a simple command line program that links the OpenStudio dll.

Ultimately we want the OpenStudioApp project to use this new capability. We can either extend this ticket to update the OS app project, or open a separate ticket when the time comes.

**Comment by lefticus** [comment] 2019-10-30 14:33
Current status for building DLL:

# Naive Approach "just link all '.a''s into a '.dll'

 * Doesn't work because the linker will automatically strip all unused symbols, leaving an empty '.dll'.

Why does this work for the ruby dll?

 * Because the openstudio_ruby library has "init_openstudio" which calls all of the ruby init functions which in turn reference all of the functions in OpenStudio

# Hack Option 1 - Force All Symbols To Be Exported

This option seems to be somewhat problematic, but has promise (I have not yet tried it). The problem is that it requires very careful introduction of specific linker flags to enable and disable linking of all symbols, and is OS specific.

See: 
 * https://stackoverflow.com/questions/11429055/cmake-how-create-a-single-shared-library-from-all-static-libraries-of-subprojec/41854795#41854795
 * https://stackoverflow.com/questions/14347107/how-to-put-compiler-command-line-args-in-specific-places-using-cmake/14347487#14347487

# Hack-ish Option 2 - Use `OBJECT` Libraries as an Intermediary 

It goes something like this:

```
# link cpp files into "OBJECT" library
add_library(${target_name}_objects OBJECT ${${target_name}_src} ${OUTPUT})

# Create static library from OBJECT Library
add_library(${target_name} $<TARGET_OBJECTS:${target_name}_objects>)
```

...

```
add_library(openstudio SHARED
   $<TARGET_OBJECTS:openstudio_airflow_objects>    
   $<TARGET_OBJECTS:openstudio_utilities_objects>
# etc
)
```

Unfortunately due to limitations with CMake this becomes problematic for reasons of properly tracking dependencies of the libraries.

It's possible that requiring CMake 3.14 (untested) would make this better, but only 3.10 is currently shipped with Ubuntu 18.04

# Direction Forward

After typing this all up I'm inclined towards the "Hack Option 1," but am still concerned that it would be too fragile.

The reason I consider this fragility worth considering is that it would be tightly limited to the specific CMake code around the linking of just this one library.

I would prefer "Hackish Option 2" as I think it's the best direction ultimately, but not sure if it's worth the pain of requiring a newer CMake version.


Thoughts @kbenne? Is updating CMake a non-starter, and I need to push forward with something a bit hacky?

**Comment by lefticus** [comment] 2019-10-30 22:52
Upon further review and experimentation, "Hack Option 1" has been chosen. It can be implemented cleanly and in only one location.

**Comment by lefticus** [comment] 2019-11-02 15:18
I have it working with OBJECT libraries (not committed), but it's still not perfect

Cons: 

 * It doesn't track the openstudio_utilities object files as transitive dependencies from openstudio_model through openstudio_gbxml, for example, so dependencies must be manually tracked
 * Build folder seems to be considerably larger

Pros:

 * The process uncovered several little bugs in the handling of libraries

I think it's best to stick with the linking of the `.a` files for now, but the hard work has been done, and it should be possible to make the decision to switch back to OBJECT libs if/when we decide to upgrade CMake and want to give it another go.

**Comment by lefticus** [comment] 2019-11-05 05:35
First attempt of an external project linking to OpenStudioLib is here: https://github.com/lefticus/OpenStudioLibTest

And first major problem hit: Boost is part of the public interface of OpenStudio. So to use OpenStudio we need to ship some portion of Boost that represents the specific version that we built/linked against, to make sure we have the same ABI/API provided to the consumer of the library.

**Comment by lefticus** [comment] 2019-11-05 17:41
Linking to OpenStudioLib from external project working: https://github.com/lefticus/OpenStudioLibTest/commit/5bfc68132e32cfe3639cc18aab2cd1b8009a76e4

Notes:

 * requires that we have and link to our own Boost (need the headers)
 * This is tricky because it needs to be the same version that was linked into the .so

**Comment by lefticus** [comment] 2019-11-07 19:18
To do:

- [ ] Test installed library
- [ ] Test in situ linking of library from a different project
- [ ] Windows/MSVC
   - [ ] Debug
   - [ ] Release
   - [ ] Packaging
- [ ] Linux/GCC
   - [ ] Debug
   - [ ] Release
   - [ ] Packaging
- [ ] MacOS
   - [ ] Debug
   - [ ] Release
   - [ ] Packaging

**Comment by lefticus** [comment] 2019-11-09 14:20
This branch now lives in a world where everything is perfectly parallelizable up until the few executables and DLL's need to be linked.

**Closed** 2020-02-17 22:11 UTC
Labels: Develop3
