### ISSUE TITLE
Unkown iddObjectType: 'OS:ClimateZones' warning on ModelToIdf

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#828] opened 2014-01-29 16:57 UTC
Dan, the model does export to IDF and runs fine, but looking in PAT on the branch I merged to develop I do see this new warning.

**Comment by macumber** [comment] 2015-01-29 07:01
Duplicate of #883

**Closed by macumber** 2015-01-29 07:01 UTC
Labels: component - Code, resolution - Duplicate, severity - Normal Bug
