### ISSUE TITLE
Address approach to ideal air loads

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2384] opened 2016-10-19 16:46 UTC
Relates to this measure
https://github.com/NREL/OpenStudio-measures/commit/b0fbcd04b3153854ba529589d90e13b7898be634

**Comment by macumber** [comment] 2016-11-29 01:13
Sounds like this is due to certain measures creating ideal air loads equipment rather than using the switch on thermal zone, would like to coordinate these two but doubt this will happen for 1.14

**Comment by DavidGoldwasser** [comment] 2016-11-29 17:46
@macumber I agree this isn't for 1.14, but @kbenne and @asparke2 we really should address this after the release. It is pretty messy now.

**Comment by DavidGoldwasser** [comment] 2019-11-04 22:25
@kbenne Any objections to only using one approach for ideal air loads?

**Comment by DavidGoldwasser** [comment] 2020-09-03 00:11
While link to old code at top of this still works, I wanted to provide link to current version of ideal air loads measure which is what we primarily use to add ideal air loads vs the `thermal_zone.setUseIdealAriLoads` method.
https://github.com/NREL/openstudio-common-measures-gem/blob/develop/lib/measures/EnableIdealAirLoadsForAllZones/measure.rb#L91

**Comment by jmarrec** [comment] 2021-04-08 15:51
Duplicate of #3101

**Closed by jmarrec** 2021-04-08 15:51 UTC
Labels: Enhancement Request, component - Model
