### ISSUE TITLE
1.9.0 Turning off "Run for sizing period" yet it still seems to run them

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#1894] opened 2015-09-25 08:05 UTC
I switched off "Run Simulation for Sizing Periods", and yet it still appears like the sizing periods were used.

![2015-09-25 10_00_21-daylight off](https://cloud.githubusercontent.com/assets/5479063/10095771/90bc6866-636c-11e5-9497-3758632c5397.jpg)

    Calculate Air Heat Balance
    Initializing HVAC
    Warming up
    Calculating Detailed Daylighting Factors, Start Date=07/21
    Warming up
    Warming up
    Warming up
    Warming up
    Warming up
    Performing Zone Sizing Simulation
    ...for Sizing Period: #1 NEW YORK J F KENNEDY INTL AR ANN CLG .4% CONDNS DB=>MWB
    Warming up
    Calculating Detailed Daylighting Factors, Start Date=07/21
    Warming up
    Warming up
    Warming up
    Warming up
    Warming up
    Performing Zone Sizing Simulation

One thing to note is that the resulting sql output does not have the Sizing Period output.

Note that I do have an illuminance map, a glare sensor, a daylight sensor, in my model. I think this is automatically causing radiance to be picked as daylight engine? The "Select daylight engine" on the run tab has disapeared in 1.9.0 (why?) so I'm not quite sure.

**Comment by DavidGoldwasser** [comment] 2015-09-25 14:41
@kbenne do you automatically turn on Run Simulation for Sizing Periods even if the user requests it, if we find the necessary object types are in the model.

@jmarrec in 1.9 Radiance is now implemented as a measure, although there are some radiance configuration settings still in OpenStudio. But to run Radiance you grab an OSM measure and put it into your workflow.

**Comment by kbenne** [comment] 2015-09-25 14:51
Something like that but we need to revisit this. I think the logic is trying to be too clever. I believe there might be another issue filed on this but I'll have to look it up when I'm not traveling. This is a good thing to change right after a major release so we have time to work out the consequences.

On Sep 25, 2015, at 9:42 AM, David Goldwasser <notifications@github.com<mailto:notifications@github.com>> wrote:


@kbenne<https://github.com/kbenne> do you automatically turn on Run Simulation for Sizing Periods even if the user requests it, if we find the necessary object types are in the model.

@jmarrec<https://github.com/jmarrec> in 1.9 Radiance is now implemented as a measure, although there are some radiance configuration settings still in OpenStudio. But to run Radiance you grab an OSM measure and put it into your workflow.

-

**Comment by MatthewSteen** [comment] 2015-09-25 15:33
#1472

**Comment by DavidGoldwasser** [comment] 2015-09-25 16:06
Thanks @MatthewSteen, I'll mark this as a duplicate of #1472

**Closed by DavidGoldwasser** 2015-09-25 16:06 UTC
