### ISSUE TITLE
OpenStudio doesn't produce valid strings for XML

### ISSUE THREAD

**Issue by pflaumingo** [NREL/OpenStudio#3949] opened 2020-04-14 20:17 UTC
Issue overview
--------------
OpenStudio can create illegal XML characters when performing validation for EnergyPlus.
Not sure if this is strictly the responsibility of OS or E+.

## Current Behavior
OpenStudio converts `!` to `&#33`

## Expected Behavior
OpenStudio converts `!` to a valid xml character. If the above appended a semi-colon, I believe it would work - `&#33;=`"&#33;"

## Steps to Reproduce
In some editor you can see the conversion with the code below
```ruby
require 'openstudio'
model = OpenStudio::Model::Model.new
t_zone = OpenStudio::Model::ThermalZone.new(model)
puts t_zone

t_zone.setName("Villa ! 102")
puts t_zone
```

or just look here: https://github.com/NREL/OpenStudio/blob/0cb319a4977599dbe3eca55fc39abdfa077aeaa7/src/utilities/idf/IdfObject.cpp#L2008-L2034

## Possible Solution
Escape the encodings with a semi-colon

### Context
When using the eplustbl.xml after the E+ run, the XML can't be parsed because of this encoding issue.

**Comment by pflaumingo** [comment] 2020-04-14 21:10
I should say this was tested with both MSXML and REXML.

**Comment by jmarrec** [comment] 2020-04-19 19:58
Obviously the issue is that `;` itself is encoded to `&#59` so that complicates the implementation.

**Comment by jmarrec** [comment] 2020-04-20 13:31
Also, the name is encoded internally, but that is then decoded when you call the `name()` or `nameString` method. I'm not sure I follow what you're doing / where you're getting that error.

```ruby
[7] gbxml(main)> puts t_zone
OS:ThermalZone,
  {8942a4f3-94f1-4286-afe0-bae152bd1c2e}, !- Handle
  Villa &#33 102,                         !- Name
  [...]
[8] gbxml(main)> puts t_zone.nameString
Villa ! 102
=> nil
[9] gbxml(main)> puts t_zone.name
Villa ! 102
```

**Comment by jmarrec** [comment] 2020-04-20 13:36
Oops, I failed to read your last sentence : `When using the eplustbl.xml after the E+ run, the XML can't be parsed because of this encoding issue.`. So yeah, the issue is that EnergyPlus will never be happy with a semicolor or comma inside a field...

```
[17] gbxml(main)> ft = OpenStudio::EnergyPlus::ForwardTranslator.new()
=> #<OpenStudio::EnergyPlus::ForwardTranslator:0x0000560beee453b8 @__swigtype__="_p_openstudio__energyplus__ForwardTranslator">
[18] gbxml(main)> w = ft.translateModel(model)
[openstudio.energyplus.ForwardTranslator] <0> ThermalZone Villa ! 102 does not have any geometry or loads associated with it.
[openstudio.model.YearDescription] <-1> 'UseWeatherFile' is not yet a supported option for YearDescription
[openstudio.model.YearDescription] <-1> 'UseWeatherFile' is not yet a supported option for YearDescription
[utilities.idf.WorkspaceObject] <0> Object of type 'Schedule:Constant' and named 'Always On Discrete', points to an object named OnOff from field 1, but that object cannot be located.
[utilities.idf.WorkspaceObject] <0> Object of type 'Schedule:Constant' and named 'Always Off Discrete', points to an object named OnOff 1 from field 1, but that object cannot be located.
[utilities.idf.WorkspaceObject] <0> Object of type 'Schedule:Constant' and named 'Always On Continuous', points to an object named Fractional from field 1, but that object cannot be located.
=> #<OpenStudio::Workspace:0x0000560beedf39c8 @__swigtype__="_p_openstudio__Workspace">
[19] gbxml(main)> puts w.getObjectsByType("Zone")
Zone,
  Villa &#33 102,                         !- Name
  ,                                       !- Direction of Relative North {deg}
  ,                                       !- X Origin {m}
  ,                                       !- Y Origin {m}
  ,                                       !- Z Origin {m}
  ,                                       !- Type
  ,                                       !- Multiplier
  ,                                       !- Ceiling Height {m}
  ,                                       !- Volume {m3}
  ,                                       !- Floor Area {m2}
  ,                                       !- Zone Inside Convection Algorithm
  ;                                       !- Zone Outside Convection Algorithm


```

**Comment by tijcolem** [comment] 2020-05-01 16:19
@pflaumingo Are you able to handle these special chars on your end?  This seems like a E+ issue that Julien has already alluded to.

**Comment by pflaumingo** [comment] 2020-05-01 16:54
Yup, I can handle them on my end :)

**Comment by jmarrec** [comment] 2020-05-13 19:44
I'm going to close this then.

**Closed by jmarrec** 2020-05-13 19:44 UTC
Labels: Triage
