### ISSUE TITLE
Improve GUI for humidistat on Thermal Zone Tab

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1121] opened 2014-07-07 20:33 UTC
@asparke2 and @marj-schott Below is a screenshot of what the humidistat looks like in 1.4.0. I'm viewing the test model for the unitary system from the resources folder. My assumption looking at this was that if the air got too dry that humidification would be provided, but that there would be no de-humidification. But what actually happens in OpenStudio (which follows what E+ does) is that if only a single schedule exist for humidistat it serves as hard target that should be used for both humidification and de-humidification. When only a single schedule is used it should be put into the left drop zone.

![7-7-2014 2-10-48 pm](https://cloud.githubusercontent.com/assets/4857055/3501349/a64fb274-0615-11e4-9e81-952c2d9b7d35.png)

@kbenne and I were thinking of possible ways to clarify this. Below are some possible options that could be used individually or combined.
1. Change schedule titles to something like "Low Humidity Setpoint" and "High Humidity Setpoint". 
2. Add below the humidistat object saying something like "When you want to specify a single humidity target without any float please apply the desired schedule to the "Low Humidity Setpoint".
3. When the user drops a schedule in the left drop zone, add a "green" version without the x to the right drop zone to more visually indicate what is happening. If the user manually adds a new schedule to the right it would overwrite the defaulted one.
4. To make things more flexible it would be nice to allow the user to drop the schedule on the left or the right, and have it fix itself.

Not directly related to this, but we have also had a question for a while about modeling systems like Appendex G types 9-10 that are heating only, or in Singapore modeling cooling only systems. Currently people need to supply both a heating and cooling setpoint, so they need to make a dummy cooling setpoint even if they never intend to use it. Maybe that can be addressed at the same time? I don't think this is a critical issue that needs to be in an iteration installer, but maybe we can look at it by 1.5.0?

**Comment by asparke2** [comment] 2015-01-31 21:55
Changing this to a feature request.  It works as designed, but it isn't clear what the behavior is unless you read the E+ documentation.

**Comment by asparke2** [comment] 2017-03-03 23:40
Closing.  This has been fixed since we changed to grid view.

**Closed by asparke2** 2017-03-03 23:40 UTC
Labels: component - OS App, Feature Request
