### ISSUE TITLE
About PAT window hasn't been updated in agest

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2691] opened 2017-07-12 15:49 UTC
The About PAT window on Mac states:

![about](https://user-images.githubusercontent.com/2230150/28126643-e9fee83c-66de-11e7-8a41-018d134fa0b1.png)

This needs to be updated.

**Comment by DavidGoldwasser** [comment] 2017-07-21 18:47
duplicate of issue #2581

**Closed by DavidGoldwasser** 2017-07-21 18:47 UTC
Labels: component - PAT, severity - Minor Bug
