### ISSUE TITLE
[Performance] Running list of improvements for performance reasons

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#4458] opened 2021-10-05 05:42 UTC
Enhancement Request
--------------

This issue is to centralize some (fairly simple) actionable items in order to improve performance. These are basically things that will avoid doing extra work or doing extra copies.

* [ ] Avoid push_backs when possible
     * [ ] by direct initializing vectors that aren't dynamic
         * example: https://github.com/NREL/OpenStudio/blob/65607aefbca49ea71a45bd8fe0180c305a148934/src/model/Space.cpp#L264-L282
         * In some occasion, maybe using a `constexpr std::array` would be better (Need to check impact on ruby code, and also some types like IddObjectType aren't suitable for use in a constexpr context as they aren't 'literal')
     * [ ] by using emplace_back to construct elements in place where possible
         * Lots of that in the FT for eg:
         ```diff
          - IdfObject idealLoadsAirSystem(IddObjectType::HVACTemplate_Zone_IdealLoadsAirSystem);
          - m_idfObjects.push_back(idealLoadsAirSystem);
          + auto& idealLoadsAirSystem = m_idfObjects.emplace_back(IddObjectType::HVACTemplate_Zone_IdealLoadsAirSystem);
          ```

* [ ] Make sure there are no functions left that take `std::string` (or any other non POD types) by value **without reason** (there are a couple of cases where we are mutating the string) to avoid extra copies: for your pImpl case, that's at least TWO extra copies for each call. There are close to a thousand occurrences left in just `model/`
    * https://github.com/NREL/OpenStudio/blob/65607aefbca49ea71a45bd8fe0180c305a148934/src/model/SizingSystem.hpp#L240
    * https://github.com/NREL/OpenStudio/blob/65607aefbca49ea71a45bd8fe0180c305a148934/src/model/SizingSystem_Impl.hpp#L229 
* [ ] Same thing for **setters** taking a `boost::optional<T>` argument and checking if the argument is present... 
    * it's inefficient and doesn't make much sense.  
    * It's actually inconsistent: sometimes we reset sometimes we don't.
    * https://github.com/NREL/OpenStudio/blob/65607aefbca49ea71a45bd8fe0180c305a148934/src/model/ChillerElectricEIR.cpp#L315-L321
    * https://github.com/NREL/OpenStudio/blob/65607aefbca49ea71a45bd8fe0180c305a148934/src/model/CoolingTowerVariableSpeed.cpp#L321-L331
    * This is technically an API break, though most users won't even notice it (I doubt many people actually try to pass optional doubles / strings)
* [ ] Modify all `for (T t : vectorOfTs)` to `for(const T& t: vectorOfTs)` if possible or `for (T& t: vectorOfTs)` if mutating it, to avoid extra copies on loops. The FT is ridden with this for eg: https://github.com/NREL/OpenStudio/blob/65607aefbca49ea71a45bd8fe0180c305a148934/src/energyplus/ForwardTranslator.cpp#L240-L245

**Comment by shorowit** [comment] 2021-11-06 13:17
- [ ] Option 3 from https://github.com/NREL/OpenStudio/issues/4477 ?

**Comment by shorowit** [comment] 2021-11-06 18:39
- [ ] Further enable use of CBOR instead of SQLite? https://github.com/NREL/OpenStudio/issues/4496
- [ ] Connect OpenStudio to the EnergyPlus API instead of calling the EnergyPlus CLI to eliminate I/O (e.g., pass the model in memory to EnergyPlus, retrieve the outputs in memory from EnergyPlus); though it looks like this would require changes to EnergyPlus too?

**Comment by tijcolem** [comment] 2021-11-15 17:25
Add https://github.com/NREL/OpenStudio/pull/4493 to the list.

**Comment by tijcolem** [comment] 2021-11-15 20:50
Before we start to chip away at the this list, we'll want to establish a base test case to measure performance gains and quantify the result in some meaningful way.  @jmarrec Are there some specific regression tests we can use to for this?

**Comment by shorowit** [comment] 2021-12-16 19:10
- [ ] Add [extralite gem](https://noteflakes.com/articles/2021-12-15-extralite) to CLI as an alternative to sqlite3-ruby? (I don't exactly understand the use case for having a sqlite gem in the CLI, since the OS SDK can be used to execute sql statements, but if anyone is using the sqlite3-ruby gem it sounds like they could benefit greatly from using this gem instead.)

**Comment by tijcolem** [comment] 2023-02-28 16:59
Closing as this is complete. https://github.com/NREL/OpenStudio/pull/4532

**Closed by tijcolem** 2023-02-28 16:59 UTC
Labels: Enhancement Request, Performance
