### ISSUE TITLE
IG won't maintain focus 

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#1229] opened 2014-10-02 18:26 UTC
Every time I press enter or move to the next field in IG (thereby committing an IG change), the right column switches over to the library.  Is anyone else seeing this.  @asparke2 @macumber @evanweaver GridView side effects or am I just too trigger happy to assign blame?  In any case this is a major usability issue.  I found this not reviewing GridView, but actually debugging a cbecc model and researching proper inputs for design oa.

**Comment by asparke2** [comment] 2015-01-31 21:05
Closing because @evanweaver fixed this.  Confirmed fix in 1.6.0.

**Closed by asparke2** 2015-01-31 21:05 UTC
Labels: component - OS App, severity - Major Bug
