### ISSUE TITLE
Deselected output Variables in OS Output Variables tab are not deleted from IDF file  

### ISSUE THREAD

**Issue by avicarmeli** [NREL/OpenStudio#3140] opened 2018-05-22 17:27 UTC
Selecting output variables in the Output Variables tab of OS  and running the model yields a in.idf file which includes the entries for the desired output variables. Deselecting some of the output variables in OS and running again the model yields a in.idf file which includes all of the output variables which were selected before the first run of the model.

A work around would be to push the **All Off** button then save the model and only then to select the desired output variables before running the model again.

See discussion in [Unmethhours](https://unmethours.com/question/31624/why-are-the-variables-not-clearing-in-the-openstudio-idf-file/).

**Comment by jmarrec** [comment] 2019-03-18 12:01
@avicarmeli Thanks for opening this issue. Which version did you use to reproduce the issue? And which variables did you check for?

**I have tried reproducing the issue just now with 2.7.1 on Ubuntu, and I couldn't**. 

Here are the steps I followed: I created an empty model, added a thermal Zone, then went to the Output:Variable tab and enabled two random variables:
* `Zone Other Equipment Total Heating Rate`, letting it default to "Hourly"
* `Zone Air CO2 Concentration`, setting it to "Monthly"

Then I went to the run tab, and ran the file (which failed, since it has no geometry) and checked the resulting in.idf. I had 8 variables, including these two.

Went back to the Output:Variables tab, removed them both one by one (not click the "All Off" button), reran the model, checked in.idf. Had 6 variables, these two were gone.

Tried the above all over again a few times, unclicking only one variable for eg, and never could reproduce it. Also tried with a model with geometry that successfully runs through E+, couldn't reproduce it.


Unless you can help me reproduce it on 2.7.1, I will have to close the issue, thanks!

**Comment by jmarrec** [comment] 2019-08-19 12:54
Closing as can't reproduce

**Closed by jmarrec** 2019-08-19 12:54 UTC
Labels: component - OS App
