### ISSUE TITLE
app closes when navigating from Measures tab before measures are finished reloading after sync

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/OpenStudio#3955] opened 2020-04-20 21:21 UTC
Issue overview
--------------
In 2.9.0 the app will close when the user does the steps below.

## Current Behavior
App closes unexpectedly.

## Expected Behavior
App shouldn't close.

## Steps to Reproduce
1. Edit `measure.rb` attached model
2. Measures > `Sync Project Measures with Library` > Update
3. *Before* the model's measures are done loading click another tab (e.g. Run)
4. App will close

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10
 - Version of OpenStudio (if using an intermediate build, include SHA): 2.9.0

**Comment by jmarrec** [comment] 2020-04-21 12:51
Duplicate of #2613, fixed in 3.x via https://github.com/NREL/OpenStudioApplication/commit/7d2875a502ce5bd2f43127e8eab90967bba39923

**Closed by jmarrec** 2020-04-21 12:51 UTC
Labels: Triage
