### ISSUE TITLE
Deleting Schedule Ruleset object leaves Schedule Day objects behind (Bugzilla #662)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#105] opened 2013-07-19 20:22 UTC
On 2012-04-16 10:06:48, @DavidGoldwasser wrote:

> They don't necessarily cause problems, but clutter the file. Ideally we can check if they are used anywhere outside of the deleted schedule ruleset object and if not delete them.
> 
> If someone is working with the OS App GUI we don't even need this check, but seems prudent to do this to protect the model.

On 2012-05-07 11:31:38, @DavidGoldwasser wrote:

> bug 689 is similar bug but for render color objects.

On 2012-05-24 15:31:50, @DavidGoldwasser wrote:

> <re-validated with OpenStudio Trunk 052212>

On 2013-01-10 11:37:02, @DavidGoldwasser wrote:

> <batch comment: added this to Pivotal Epic, https://www.pivotaltracker.com/epic/show/458473>

**Comment by DavidGoldwasser** [comment] 2015-02-01 22:11
related to #118

**Comment by DavidGoldwasser** [comment] 2016-11-28 20:45
Closing this as duplicate of #2376. Seems that this is partially fixed, but summer and winter days are still orphaned.

**Closed by DavidGoldwasser** 2016-11-28 20:45 UTC
Labels: component - OS App, severity - Normal Bug
