### ISSUE TITLE
Building::remove creates invalid HVAC Connections

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#3524] opened 2019-05-06 18:18 UTC
I will link to measure with unit test that demonstrates this. The seed model for the measure test can forward translate fine, and the measure (which reverse translates and imports IDF objects) forward translates fine when added to an empty model, but not when added to the non-empty seed model.

I first saw this in OS app, it had different behavior in workflow vs. apply measures now. In workflow the measure finished and it locked up (not crashed) on forward translation. In apply measure now it locks up in what appears to be during the measure.

```
[BOOST_ASSERT] <2> Assertion result failed on line 350 of openstudio::model::HVACComponent openstudio::model::detail::PortList_Impl::hvacComponent() const in file /Users/tcoleman/git/OpenStudio/openstudiocore/src/model/PortList.cpp.
[BOOST_ASSERT] <2> Assertion result failed on line 350 of openstudio::model::HVACComponent openstudio::model::detail::PortList_Impl::hvacComponent() const in file /Users/tcoleman/git/OpenStudio/openstudiocore/src/model/PortList.cpp.
[BOOST_ASSERT] <2> Assertion m_impl failed on line 2127 of openstudio::IdfObject::IdfObject(const openstudio::IdfObject &) in file /Users/tcoleman/git/OpenStudio/openstudiocore/src/utilities/idf/IdfObject.cpp.
[BOOST_ASSERT] <2> Assertion m_impl failed on line 2127 of openstudio::IdfObject::IdfObject(const openstudio::IdfObject &) in file /Users/tcoleman/git/OpenStudio/openstudiocore/src/utilities/idf/IdfObject.cpp.
[BOOST_ASSERT] <2> Assertion result failed on line 119 of openstudio::model::ThermalZone openstudio::model::detail::PortList_Impl::thermalZone() const in file /Users/tcoleman/git/OpenStudio/openstudiocore/src/model/PortList.cpp.
[BOOST_ASSERT] <2> Assertion result failed on line 119 of openstudio::model::ThermalZone openstudio::model::detail::PortList_Impl::thermalZone() const in file /Users/tcoleman/git/OpenStudio/openstudiocore/src/model/PortList.cpp.
/Users/dgoldwas/Documents/GitHub/NREL/OpenStudio-measures/nrel_published/ImportEnvelopeAndInternalLoadsFromIdf/tests/ImportEnvelopeAndInternalLoadsFromIdf_Test.rb:230: [BUG] Segmentation fault at 0x00000000000000
ruby 2.2.4p230 (2015-12-16) [x86_64-darwin15]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.

-- Control frame information -----------------------------------------------
c:0024 p:---- s:0119 e:000118 CFUNC  :translateModel
```

**Comment by DavidGoldwasser** [comment] 2019-05-06 18:23
https://github.com/NREL/OpenStudio-files/blob/master/Git%20Issue%20Files/issue3524/ImportEnvelopeAndInternalLoadsFromIdf.zip

I'm assuming the reverse translation into non-empty model is maybe making two of object where only one is expected, or something like that.

**Comment by DavidGoldwasser** [comment] 2019-05-06 18:43
I did a little more testing. There is nothing unique about this OSM or IDF. replaced both of them and saw the same thing. So this seems to happen with many non-empty OSM files.

If I used the OS app to create a new model, save that and then use that as the starting model, it doesn't crash. It is something else being added later that create the issue.

**Comment by DavidGoldwasser** [comment] 2019-05-10 14:39
@macumber one thing I can't figure out, why is the OS app in apply measure now even doing post measure forward translation for? Is it I guess running as an OSW that does this even if using measures only flag.

**Comment by jmarrec** [comment] 2019-05-13 14:39
@DavidGoldwasser The problem is that through `m.getBuilding.remove`, you end up with bad connections. I can boil down your problem to this MCVE:

```
include OpenStudio::Model

ft = OpenStudio::EnergyPlus::ForwardTranslator.new

m = Model.new
s = Space.new(m)
z = ThermalZone.new(m)
s.setThermalZone(z)

a = AirLoopHVAC.new(m)
atu = AirTerminalSingleDuctConstantVolumeNoReheat.new(m, m.alwaysOnDiscreteSchedule)
a.addBranchForZone(z, atu)
m.save('dummy.osm', true)
# No Problem
w = ft.translateModel(m)
w.save('dummy.idf', true)

puts "Removing building"
m.getBuilding.remove
m.save('dummy_bldg_remove.osm', true)
# Crash
w = ft.translateModel(m)
w.save('dummy_bldg_remove.idf', true)
```

**Comment by jmarrec** [comment] 2019-05-13 14:43
I guess this is pretty much the same problem as #2449. Just like Building::clone, Building::remove doesn't handle HVAC correctly. Doing a diff between `dummy.osm` and `dummy_bldg_remove.osm` shows that you end up with bad Connections/PortLists:

![image](https://user-images.githubusercontent.com/5479063/57630623-3cfce500-759e-11e9-9bd0-f58e64faf29b.png)

**Comment by jmarrec** [comment] 2019-05-13 15:14
I'm pretty confused about `ParentObject::remove`... I was really expecting it to call remove on each modelObject it should delete, but apparently it isn't... https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/model/ParentObject.cpp#L105. this ends up calling directly Workspace::removeObjects.

The problem here is that the ThermalZone is being deleted as is, instead of actually being disconnected, cleanning up the Nodes, Connections, and PortLists.

So I can see a quick fix for this specific issue, which is to implement an override `Building::remove` and do some cleanup (such as disconnecting every ThermalZone) before deferring to `ParentObject::remove()`. Thoughts anyone?

**Comment by macumber** [comment] 2019-05-13 15:28
Overloading Building::remove seems like the right choice.  Just add a bunch of unit tests.

**Comment by jmarrec** [comment] 2019-05-13 15:29
@macumber Are you ok only disconnecting ThermalZones for 2.8.1 to fix this specific bug? If we want to handle all corner cases it's going to be a lot of effort.

**Comment by macumber** [comment] 2019-05-13 15:30
Sure, if you can think of any other corner cases then it would be good to get those here too.

**Comment by jmarrec** [comment] 2019-05-13 15:57
In a very dumb fashion, I actually think that refactoring Building::remove to do

```
for (const ModelObject mo: this->children()) {
  mo.remove()
}
```

would not produce any side effects and do things a lot better than what's currently done. The larger issue is that currently children (therefore remove and clone methods) are limited to Meters, Building Stories, Shading Surface Groups, Thermal Zones, and Spaces. No HVAC (which is covered in #2449)

**Comment by jmarrec** [comment] 2019-09-25 17:01
@DavidGoldwasser Can you test that https://github.com/NREL/OpenStudio/pull/3534 fixed this? If so, please close.

**Comment by jmarrec** [comment] 2019-11-25 15:09
@DavidGoldwasser I'm closing. Please reopen if you eventually bump into it again, but I think #3534 fixed it, at least with the testing I've done.

**Closed by jmarrec** 2019-11-25 15:09 UTC
