### ISSUE TITLE
Repeatable crash when loading specific seed model

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1617] opened 2015-04-16 14:42 UTC
I'm using develop build. The seed model doesn't have any measures in it, and neither does the PAT project. It is is a freshly made PAT project.

1. Launch PAT and make new project
2. choose "0416_lab_a.osm" as seed

Should crash with error about "Passed in measure does not have primary RubyScript Path set, which is required for RubyJobBuilder. It is an odd message since no measures are involved yet.

![4-16-2015 8-35-29 am](https://cloud.githubusercontent.com/assets/4857055/7183405/8052f170-e414-11e4-8434-21734e56775d.png)

I tried scanning for tools, that didn't fix this. Next I'll try throwing away the database with the osm file. The osm file does open up fine in OpenStudio app.

Here is link to seed file I'm trying to load
https://github.com/NREL/OpenStudio-files/tree/master/Git%20Issue%20Files/Issue1617

**Comment by DavidGoldwasser** [comment] 2015-04-16 14:58
Throwing away the database didn't make a difference. Neither did doing a simulation run in the OSM file (which ran successfully) and then saving the OSM.

I did load another OSM as a seed model to confirm that this doesn't always happen.

**Comment by macumber** [comment] 2015-04-16 15:10
Great, seems related to https://github.com/NREL/OpenStudio/issues/1601

**Comment by DavidGoldwasser** [comment] 2015-04-16 15:57
Also tried changing "My Measures" directory and throwing away my "BCL" directory. Neither of those did anything.

**Comment by macumber** [comment] 2015-08-19 16:05
I think this is a duplicate of https://github.com/NREL/OpenStudio/issues/1617

**Comment by DavidGoldwasser** [comment] 2015-08-19 16:33
I'll confirm if this still happens and assign to @macumber if it does

**Comment by DavidGoldwasser** [comment] 2015-08-20 18:51
@macumber so I confirmed this happens both in 1.8.1 installed version of OpenStudio and in my current development build (from earlier today). Throwing away everything but the OSM doesn't change what happens.

**Comment by macumber** [comment] 2015-08-20 18:55
Last update on this thread had a similar issue, failure when no user defined measures in the workflow:

https://unmethours.com/question/4404/primary-ruby-script-path-not-set-for-passed-in-measure/?comment=10483#comment-10483

User's osm had utility bills in it so it is trying to use calibration measure, maybe your test model had this too @DavidGoldwasser ?

**Closed** 2015-08-25 14:24 UTC
Labels: component - PAT, In Progress, severity - Major Bug
