### ISSUE TITLE
App closes when Air Loop availability schedule is set to blank and the 'Control' button clicked.

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#2034] opened 2016-01-20 21:32 UTC
@kbenne, @macumber 

This isn't likely to come up in usual practice, and will probably be low priority. If you set the AirLoopHVAC Availability Schedule to blank in the edit pane (when clicking the supply/demand dotted line), and then click on the 'Control' button for that loop, the App will close with no warning. Tested with OS v1.10.0, Window 7 x64.

**Comment by macumber** [comment] 2016-01-20 21:46
Sounds pretty bad to me, we usually call anything that crashes the app at least a major bug.

**Comment by kbenne** [comment] 2016-01-21 02:08
It definitely needs to be fixed. I think it might just amount to a small IDD change.

**Comment by DavidGoldwasser** [comment] 2016-03-16 20:21
@kbenne it seems like you hid the availability schedule when in Layout tab, which I assume is by design. so I removed it with a text editor. Then when I open it again and go to Control tab it shows "Always On". If I save the file, and look it didn't actually add that in, is it just some magic where it is blank that it shows always on, and I assume forward translator would write it out as that.

**Comment by kbenne** [comment] 2016-03-16 20:27
Yes this is all expected, but export to idf without running just to confirm I'm not an idiot. You might also set a custom schedule and make sure that works too.

**Comment by DavidGoldwasser** [comment] 2016-03-16 20:45
Looks good on IDF. AirLoop refers to this.

`AvailabilityManagerAssignmentList,
  Packaged Rooftop VAV with PFP Boxes and ReheatAvailability Manager List, !- Name
  AvailabilityManager:Scheduled,          !- Availability Manager Object Type 1
  Packaged Rooftop VAV with PFP Boxes and Reheat Availability Manager; !- Availability Manager Name 1

AvailabilityManager:Scheduled,
  Packaged Rooftop VAV with PFP Boxes and Reheat Availability Manager, !- Name
  Always On Discrete;                     !- Schedule Name`

@kbenne there is one thing that is a bit odd. The dropzone does work, so I can drag a custom schedule on it, like "Deck Temperature", ok that is wrong type, but it takes it. That isn't the issue. The issue is now I'd like to go back to "Always On Discrete' but there isn't a way to do that.  The library form "My Model" has a heading for "Schedules" I assume that is just showing Ruleset or Ruleset and Compact, I don't see the Constant schedules there.

On other tabs in OS app like Schedule tab, I see five kinds of schedules to choose from (the three mentioned above, and Fixed and Variable Interval.

I don't know that we need to fix that for the release, but would be nice to fix at some point. Do you want to squeeze change in for 1.11.0 or leave as is?

Work around for now would be to make a RulesetSchedule with value of one as a custom Always On.

**Comment by kbenne** [comment] 2016-03-16 20:52
I don't think a 1.11.0 issue, but I think this is an issue, and I never thought about it until now.

**Comment by DavidGoldwasser** [comment] 2016-03-16 20:59
Ok, I'll merge pull request, but leave this issue open, unless you want to make that a new issue, and close this. I assume solution is just to offer more schedules in the "My Model" tab?

**Comment by kbenne** [comment] 2016-03-16 21:02
@macumber? this is kind of a global issue. 

I'm fine leaving the issue open but I'm going to move the milestone.

**Comment by DavidGoldwasser** [comment] 2016-03-16 21:10
@kbenne so far other places where we have schedule drop zones don't have this limitation. Tabs I've looked at are Schedule, Loads, Space Types, and Spaces. All of those have schedule drop zones but for "My Model" offer up all schedule types. Not sure if I missed any cases.

**Comment by DavidGoldwasser** [comment] 2016-03-16 21:12
Ahh, looks like I missed Thermal zone. It only offers Ruleset and Compact. Building which uses a schedule for Ext. Equipment is fine.

**Comment by macumber** [comment] 2016-03-16 22:41
I'm not opposed to showing constant schedules in the my model library, I thought they already were.

@DavidGoldwasser can you delete the schedule?  That would put it back to the default value on translation right?

With the changes I just proposed to @evanweaver the user won't be able to rename the always on schedules in the inspector any more either

**Comment by DavidGoldwasser** [comment] 2016-03-17 14:33
@macumber we do already show constant schedules in most tabs, it is only in the Thermal Zone and HVAC Tabs that we don't.

Deleting the schedule to put it HVAC availability back to default is a good work around, but that's only good if you aren't using the schedule somewhere else.

**Comment by kbenne** [comment] 2016-03-17 14:38
I'm going to show the other schedule types for ThermalZones....

**Comment by kbenne** [comment] 2016-03-17 20:35
@DavidGoldwasser See above. I rammed the changed into develop. It would be nice to have you give it a glance.

**Comment by DavidGoldwasser** [comment] 2016-03-17 20:47
@kbenne I'll build and test tonight.

**Comment by DavidGoldwasser** [comment] 2016-03-18 16:15
Looks good @kbenne

**Closed by DavidGoldwasser** 2016-03-18 16:15 UTC
Labels: component - OS App, In Progress, severity - Major Bug
