### ISSUE TITLE
Clicking "Results Summary" crashes OpenStudio

### ISSUE THREAD

**Issue by rishihahs** [NREL/OpenStudio#3151] opened 2018-06-11 18:50 UTC
When I click the "Results Summary" tab, OpenStudio crashes with the following message:

    [0611/034607:FATAL:content_main_runner.cc(735)] Check failed: base::i18n::InitializeICU(). 
    [1]    3195 abort (core dumped)  Products/OpenStudioApp-2.5.1

I am running OpenStudio 2.5.1 on Ubuntu 16.04.

**Comment by jmarrec** [comment] 2018-06-26 15:59
@rishihahs Does this happen on all Models or a specific one? (if one, can you share it?)

Can you try with the latest release please? (2.6.0 release candidate https://github.com/NREL/OpenStudio/releases/tag/v2.6.0)

**Comment by jmarrec** [comment] 2019-05-23 17:30
I'm closing as I can't reproduce with 2.8.0 on either 16.04 nor 18.04

**Closed** 2019-05-23 17:36 UTC
Labels: component - OS App, severity - Major Bug

**Comment by macumber** [comment] 2019-05-23 18:42
This might be the same SSL issue @kbenne was seeing.  It looks like all the JS libraries are loaded over http https://github.com/NREL/OpenStudio-measures/blob/develop/nrel_published/openstudio_results/resources/report.html.erb#L47

There could be different versions of the measure floating around that use https?

**Comment by jmarrec** [comment] 2019-05-23 19:07
The user might have a custom measure too.
In the absence of further information, we can't reproduce. I'm happy to reopen the issue of course if we manage to reproduce!

**Comment by jmarrec** [comment] 2019-05-23 19:08
Also, I don't think it's SSL, the user's message seems to say it's ICU that failed to initialize.

**Comment by macumber** [comment] 2019-05-23 19:19
Possibly they just need to install `libicu` ?

**Comment by jmarrec** [comment] 2019-05-23 19:39
Hum, perhaps we should check with a clean VM then... I'll start one now.

I would find it strange that all this time nobody would have ran into this, but it's possible since the ubuntu user base is probably small.

Currently OS only depends on gtk: https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/CMakeLists.txt#L1606

**Comment by jmarrec** [comment] 2019-05-23 19:51
Fresh 16.04 install:

```
julien@julien-VirtualBox:~$ find /usr -name "*libicu*"
/usr/lib/x86_64-linux-gnu/libiculx.so.55
/usr/lib/x86_64-linux-gnu/libicutest.so.55.1
/usr/lib/x86_64-linux-gnu/libicuio.so.55
/usr/lib/x86_64-linux-gnu/libicui18n.so.55
/usr/lib/x86_64-linux-gnu/libicuio.so.55.1
/usr/lib/x86_64-linux-gnu/libicutu.so.55.1
/usr/lib/x86_64-linux-gnu/libicudata.so.55
/usr/lib/x86_64-linux-gnu/libicuuc.so.55
/usr/lib/x86_64-linux-gnu/libicui18n.so.55.1
/usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
/usr/lib/x86_64-linux-gnu/libicule.so.55.1
/usr/lib/x86_64-linux-gnu/libiculx.so.55.1
/usr/lib/x86_64-linux-gnu/libicule.so.55
/usr/lib/x86_64-linux-gnu/libicutu.so.55
/usr/lib/x86_64-linux-gnu/libicutest.so.55
/usr/lib/x86_64-linux-gnu/libicudata.so.55.1
/usr/share/doc/libicu55
/usr/share/lintian/overrides/libicu55
```

**Comment by jmarrec** [comment] 2019-05-23 20:10
Ok on a clean 16.04 VM, I installed OpenStudio 2.5.1, and I ran the OpenStudio::Model::exampleModel with the OpenStudio Results measure from BCL, and everything worked as intended.
