### ISSUE TITLE
C# OpenStudioModelCorePINVOKE

### ISSUE THREAD

**Issue by MingboPeng** [NREL/OpenStudio#4003] opened 2020-06-22 05:02 UTC
Issue overview
--------------

With the new 3.0 and 3.0.1 version, I am not able to use C# bindings in Rhino/Grasshopper for Ladybug tools. The issue seems to be the broken link between **OpenStudio.dll** and **openstudio_model_csharp.dll**.

## Current Behavior

System.TypeInitializationException: 'The type initializer for 'OpenStudio.OpenStudioModelCorePINVOKE' threw an exception.'

## Steps to Reproduce

1. `var sp = new OpenStudio.SetpointManagerSingleZoneReheat(new Model());`
![image](https://user-images.githubusercontent.com/9031066/85249887-f2959b00-b422-11ea-916c-59f45d207f2b.png)

![image](https://user-images.githubusercontent.com/9031066/85249941-1ce75880-b423-11ea-8d5f-fabb5e243505.png)

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version): Windows 10 (2004)
 - Version of OpenStudio (if using an intermediate build, include SHA): OpenStudio v3.0.1-rc1

### Context

OpenStudio 3.0 doesn't work with Ladybug tools where it uses C# bindings.

I have been seeing @jmarrec  have a lot of commits related to dotnet, not sure if you have any clues.
cc @jmarrec

**Comment by jmarrec** [comment] 2020-06-22 18:34
@MingboPeng The dotnet stuff isn't the culprit if it doesn't work with 3.0.0, since that dotnet stuff just got into 3.0.1-rc1 but wasn't in 3.0.0. I will try to look into it unless @kbenne knows directly what to do?

**Comment by jmarrec** [comment] 2020-06-22 18:53
3.0.0 official works fine here.

```
> #reset 64
Resetting execution engine.
Loading context from 'CSharpInteractive.rsp'.
> #r "C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.dll"
> #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\System.Core.dll"
> #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\System.Xml.Linq.dll"
> #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\System.Data.DataSetExtensions.dll"
> #r "C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Data.dll"
> #r "C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Deployment.dll"
> #r "C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Drawing.dll"
> #r "C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Windows.Forms.dll"
> #r "C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Xml.dll"
> #r "C:\openstudio-3.0.0\CSharp\openstudio\OpenStudio.dll"
> #r "ModelCreateExample.exe"
> using ModelCreateExample;

> using OpenStudio;
> var sp = new OpenStudio.SetpointManagerSingleZoneReheat(new Model());
```

**Comment by jmarrec** [comment] 2020-06-22 19:01
Also works with 3.0.1-rc1.

```
> #reset 64
Resetting execution engine.
Loading context from 'CSharpInteractive.rsp'.
> #r "C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.dll"
> #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\System.Core.dll"
> #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\System.Xml.Linq.dll"
> #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\v3.5\System.Data.DataSetExtensions.dll"
> #r "C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Data.dll"
> #r "C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Deployment.dll"
> #r "C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Drawing.dll"
> #r "C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Windows.Forms.dll"
> #r "C:\Windows\Microsoft.NET\Framework\v2.0.50727\System.Xml.dll"
> #r "C:\openstudio-3.0.1-rc1\CSharp\openstudio\OpenStudio.dll"
> #r "ModelCreateExample.exe"
> using ModelCreateExample;
> using OpenStudio;
> var sp = new OpenStudio.SetpointManagerSingleZoneReheat(new Model());
```

@MingboPeng Not sure how to reproduce your issue. 

I've taken the "ModelCreateExample" folder, and removed then re-added the reference to OpenStudio.dll. Then opened a C# interactive console, right clicked the project and clicked "Initialize Interactive with project".

![image](https://user-images.githubusercontent.com/5479063/85325199-858a1000-b4cb-11ea-9237-b0518656c8b8.png)

**Comment by jmarrec** [comment] 2020-06-22 19:05
@MingboPeng Not sure how to reproduce your issue. Please provide more info as to how you installed it, setup etc, so I can reproduce, or advise if it can be closed.

**Comment by MingboPeng** [comment] 2020-06-22 19:43
@jmarrec thanks for following up.

At beginning I thought it might be related to Rhino/Grasshopper, and I test it with [DotnetConsoleExample ](https://github.com/NREL/OpenStudio/tree/develop/csharp/examples/DotnetConsoleExample ) and I got the same error.

This project doesn't have 'Intialize Interactive with Project' option, so I just created an empty console app with .Net Framework.
C# interactive console outputs looks all fine.
![image](https://user-images.githubusercontent.com/9031066/85328155-3a0d3d00-b49e-11ea-887e-9ad4bef54106.png)

But I got the error when I try to run it:
![image](https://user-images.githubusercontent.com/9031066/85328319-8c4e5e00-b49e-11ea-87dd-a3a70d024e34.png)


I installed the OpenStudio by the regular installer.

**Comment by MingboPeng** [comment] 2020-06-22 20:11
I just did the same on my desktop, and typed following in C# interactive console:
> using OpenStudio;
> var m = new OpenStudio.Model();

I also got the PINVOKE issue here
![image](https://user-images.githubusercontent.com/9031066/85330757-fb2db600-b4a2-11ea-9a62-e902db002249.png)

**Comment by jmarrec** [comment] 2020-06-23 07:42
Thanks for providing more info @MingboPeng.

I redid the steps above and it worked fine for me with 3.0.1-rc1.

I then realized it was probably something with my PATH, and indeed it was: I had the path to my local openstudio build in there, so it was picking up DLLs I had built manually. Clearing that from my `PATH` allowed me to reproduce the issue with **both** 3.0.0 and 3.0.1-rc1.

**Comment by jmarrec** [comment] 2020-06-23 07:49
Well, I can **also** reproduce it by using the **2.9.1** installer...

**Comment by jmarrec** [comment] 2020-06-23 08:41
The only diff for csharp/CMakeLists.txt between 2.9.1 (left) and 3.0.0 (right) is the target_link_libraries call.


![image](https://user-images.githubusercontent.com/5479063/85381220-0eda2a80-b53e-11ea-9ca4-3a68d85fb1e4.png)

**Comment by jmarrec** [comment] 2020-06-23 08:56
Hum, It through me off that it was complaining about `openstudio_model_csharp.dll`, since either adding its location to the PATH or copying it directly to the C# project's bin dir wasn't working while it should have.

Instead, what it couldn't locate was really the `openstudiolib.dll`. Cleared my PATH totally, then copied the CSharp openstudio dll and the openstudiolib.dll to the C# bin directory, and now it works:

![image](https://user-images.githubusercontent.com/5479063/85383351-24505400-b540-11ea-9cf6-8034b91ea025.png)

**Comment by MingboPeng** [comment] 2020-06-23 12:30
Yes, I have tried copying all dll files to build folder, that's how it works with 2.9 and before.

This openstudiolib.dll answers one of my doubts: what makes dlls in CSharp much smaller than those in 2.9. Here now I know it is because of this new openstudiolib.dll in 3.0.

@jmarrec  is it because "lib" path is not added here in CMAKE? 

Since versions before 3.0 has no lib path, and now all c# dlls depends on it.
![image](https://user-images.githubusercontent.com/9031066/85403217-0298a200-b52b-11ea-8dc2-4d31df71b69e.png)

**Comment by arif-hanif** [comment] 2020-07-25 04:29
i am having similar issues in a revit add-in

**Comment by arif-hanif** [comment] 2020-09-04 02:34
@tijcolem  is that package published yet?

**Comment by tijcolem** [comment] 2020-09-04 18:45
@arif-hanif If your referring to the NuGet packages, yes those are posted and can be found here:  https://www.nuget.org/packages/OpenStudio/3.0.1

**Comment by jmarrec** [comment] 2020-09-14 09:49
We need to close this issue or re-title it and add action items. Otherwise it'll stay in limbo for ever.

1) Close
2) Document the need to place libs in the run folder
3) Make the libs go to the run folder automatically via nuspec or other.

Thoughts @kbenne @tijcolem ?

**Comment by tijcolem** [comment] 2020-09-18 16:10
Closed as this is now available via nuget package. https://www.nuget.org/packages/OpenStudio/3.0.1

**Closed by tijcolem** 2020-09-18 16:10 UTC
Labels: component - C#, severity - Minor Bug
