### ISSUE TITLE
insertComponent can create duplicate unique model objects

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#2610] opened 2017-05-11 22:11 UTC
m = OpenStudio::Model::Model.new
m.getSite
m.getSiteWaterMainsTemperature
m.getWeatherFile

remote = OpenStudio::RemoteBCL.new
remote.downloadComponent('f38beff0-edc6-0131-6605-48e0eb16a403')
component = remote.waitForComponentDownload()
component = component.get
osc_path = component.files("osc")[0]
vt = OpenStudio::OSVersion::VersionTranslator.new
component_object = vt.loadComponent(OpenStudio::Path.new(osc_path))
componentData = m.insertComponent(component_object.get)
puts m

**Comment by jmarrec** [comment] 2019-02-27 11:15
Expected behavior would be to only keep the unique objects from the Component being inserted?

**Comment by macumber** [comment] 2019-02-27 14:18
Or somehow merge the new unique object content with existing one, easiest and probably most clear way would be to replace existing unique object with the new one

**Comment by joseph-robertson** [comment] 2020-07-07 15:59
I'm having trouble reproducing this issue because the download for f38beff0-edc6-0131-6605-48e0eb16a403 just hangs (also hangs on manually downloading from bcl.nrel.gov).

@macumber @jmarrec

**Comment by jmarrec** [comment] 2020-07-07 19:51
Make a dummy component with a unique model object (site mains water temperature, building, facility)

**Comment by joseph-robertson** [comment] 2020-07-07 23:34
@jmarrec I was able to do that, and reproduce the issue.

So should the logic be: right before [this line](https://github.com/NREL/OpenStudio/blob/develop/src/model/Model.cpp#L804), remove any unique model objects from the workspace that match types found in `component.objects()`?

If I use `getUniqueModelObject`, this would add them to the workspace if they don't exist. So, is there an alternative method for iterating over unique model objects without adding them to the workspace?

**Comment by jmarrec** [comment] 2020-07-08 05:38
https://github.com/NREL/OpenStudio/blob/93f1c744ee940afd0e7342b3a857a7a0be2adc81/src/model/Model.hpp#L260:L278

But as I notes above, in addObjects we could perhaps do something too.

**Comment by joseph-robertson** [comment] 2021-05-17 14:54
![image](https://user-images.githubusercontent.com/8516790/118509661-1752cb00-b6e5-11eb-95f9-cd0f3c8fbfe0.png)

**Comment by joseph-robertson** [comment] 2021-05-17 15:42
@jmarrec Does this issue pre-date any of the "model merge" methods? Would the best option here be to update `addObjects` such that components get merged into `model`?

**Comment by jmarrec** [comment] 2021-05-18 07:42
Are you referring to ModelMerger ? https://github.com/NREL/OpenStudio/blob/dab86209f90d487f2e79d2212f3d0b00c96ce08f/src/model/ModelMerger.cpp#L90-L110

This is specifically for merging stuff from floorspace json into your model, and it does things that go beyond unique model objects, it tries to merge spaces and co.

**Comment by kbenne** [comment] 2021-07-30 16:36
I couldn't tell from reading through this, is the goal to replace existing unique objects or to merge with them? If that question is still being debated I would like to advocate for doing a clean replace. There always seems to be corner cases, so if folks have some of those in mind I think it would be helpful to identify them.

@joseph-robertson I think the link to code in your comment https://github.com/NREL/OpenStudio/issues/2610#issuecomment-655193700 is out of date. The link takes me to Model_Impl::disconnect which I don't think is what you were referring to. Can you update that link?

**Comment by joseph-robertson** [comment] 2021-07-30 20:39
@kbenne I was originally talking about right before [this line](https://github.com/NREL/OpenStudio/blob/develop/src/model/Model.cpp#L745): `for (const WorkspaceObject& componentObject : component.objects()) {`.

Check out the linked PR to see the start of my implementation (specifically `Model_Impl::insertComponent`). Basically, I create (and some already exist) `model.foo` getters for unique model objects using the `model().getOptionalUniqueModelObject<foo>()` function. Then the approach is to (1) loop thru any new components to be inserted, (2) determine if any are unique model objects, and (3) remove them if they are. The code then goes on to insert the new components, thus avoiding any duplicate unique model objects.

The problem I ran into (and thus sort of halted working on this) was that, for example, if you remove `Building` from the model then a bunch of other stuff gets removed as well. But we don't want that. Seems like we'd want the new `Building` to replace the existing `Building`. This is where the term "merge" came to mind.

@jmarrec

**Comment by kbenne** [comment] 2021-07-30 20:52
Ah yes. I recall some discussion about this. I think you could drop down to some workspace level methods to remove the unique objects, therefore avoiding the virtual ModelObject::remove which is causing the unwanted extra removes. Workspace::removeObject(handle) would probably be what you want. This is taking advantage of the behavior that is causing us pain on https://github.com/NREL/OpenStudio/issues/4241. 

I guess as you may know the wrinkle is fixing up the handles for any objects that reference the (removed) unique object. You either have to ensure that the new object has the same handle or you have to go through and update handle references. I think either can be accomplished with workspace level operations. ie setField.

**Comment by jmarrec** [comment] 2021-08-03 14:02
A crude merge would be something like move every characteristic of the unique modelobject to the target one (except the handle).

```
for i in 1..numFields:
   mo_1.setString(i, mo_2.getString(i).get())
```

**Closed** 2022-06-10 08:25 UTC
Labels: severity - Normal Bug, component - Model
