### ISSUE TITLE
OpenStudio app won't launch after force quit (in some instances)

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1603] opened 2015-04-14 16:48 UTC
So this happened to me yesterday and today. I was working with the App for a few hours, and at some point it's perforce got bad, and appeared to hang. In this case I was reverting changes in a model and it got stock on loading it.

After the force quit when I launch the OS app, it starts a process but not the application. It doesn't affect the PAT or the plugin.

When this happened I tired the following steps
1. Restart computer
2. Rebuild the software (I was using my development build)
3. Throw away my build directory, and do a completely fresh build.

None of those worked. In the end what works, is to launch my 1.7.0 install of OpenStuido, and then quit it. After that my development build exe. works again.

I won't assign it to anyone, but wanted to document it. I can't make it happen anytime I want. For example if I launch OpenStudio, load a modle, make changes, and then force quite, the app will still launch. If I can find any other triggers I'll add it to this ticket. In both cases I didn't run simulations. I was mainly playing with apply measures now and in some cases also adding measures to "Measures" tab

cc: @axelstudios @macumber

**Comment by jmarrec** [comment] 2017-09-29 10:00
This happens to me on macOS Sierra 10.12 with OS 2.2.1, only if I force quit then double click on an OSM file within the finder. If I force quit and launch OS App directly, then load my model I have no problem.

**Comment by macumber** [comment] 2018-01-13 17:34
Duplicate of https://github.com/NREL/OpenStudio/issues/1140

**Closed by macumber** 2018-01-13 17:34 UTC
Labels: component - OS App
