### ISSUE TITLE
OS App 1.9.4 crashes in Apply Now when changing selected measure

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#1956] opened 2015-11-18 18:25 UTC
In `1.9.4` if I go to "Apply Now", then select a measure, it goes fine.

But If I try to go an select another measure after I clicked on the first one, OS App crashes.

I'm on Win-x64 10

**Comment by macumber** [comment] 2015-11-20 16:04
I've been able to reproduce this in Windows 10 but not Windows 7.  @axelstudios @evanweaver could one of you make a debug or release with debug build on Windows 10 and see if we can get a call stack?

**Comment by macumber** [comment] 2015-11-23 16:49
This was possibly fixed by https://github.com/NREL/OpenStudio/commit/12bee679aa4890e5cc5192bd6a80efdba1f1046a

Need to confirm the fix in 1.9.5 build

@evanweaver @axelstudios FYI

**Comment by evanweaver** [comment] 2015-11-24 16:36
Fixed in v1.9.5, as noted above by Dan.

**Closed by evanweaver** 2015-11-24 16:36 UTC
Labels: component - OS App, severity - Normal Bug

**Comment by macumber** [comment] 2015-11-24 17:23
@evanweaver did you test using a 1.9.5 build?

**Comment by evanweaver** [comment] 2015-11-24 17:26
No, v1.9.0.

**Comment by evanweaver** [comment] 2015-11-24 17:26
Yes, of course :)

**Comment by jmarrec** [comment] 2015-11-24 19:50
(When is 1.9.5 due out of curiosity? A link to a schedule of dev and official releases would be welcomed if that exists!)

**Comment by evanweaver** [comment] 2015-11-24 19:56
It will be available tomorrow, unless @macumber @kbenne or @DavidGoldwasser want to push other code changes in. Then, due to a long Thanksgiving weekend, 1.9.5 will not be available until late next week.

**Comment by DavidGoldwasser** [comment] 2015-11-24 20:10
@evanweaver my changes can wait until next iteration.

**Comment by jmarrec** [comment] 2015-11-24 20:23
Do you plan to do a 1.9.6 before 1.10.0 aka "the holiday gift (tm)" then?

Envoyé de mon iPhone

**Comment by evanweaver** [comment] 2015-11-24 20:26
Potentially, but I need to review this with Luigi before I can comment with certainty.

**Comment by ljbrackney** [comment] 2015-11-24 20:28
I believe the next scheduled iteration build will be 1.10.0

On Nov 24, 2015, at 1:27 PM, evanweaver <notifications@github.com<mailto:notifications@github.com>> wrote:


Potentially, but I need to review this with Luigi before I can comment with certainty.

-
