### ISSUE TITLE
OS 1.10.0 Win 64 App does preserve inherited relatonships for constructions assigned to surfaces and sub surfaces

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/OpenStudio#2090] opened 2016-02-23 13:55 UTC
Background of Issue
Simple OS model constructed using a Default Construction Set object applied at the Building Level. No construction set assignments intercept this construction assignment at any other level in the model (Story/Space). 

Unexpected Behavior
When viewing the construction assignments in the Spaces/Surfaces or Spaces/Subsurfaces tabs, users are unable to see the inherited relationships of the constructions and are able to directly modify the properties of individual construction of Surfaces/Subsurfaces using the OS App GUI. These properties are neither colored green nor locked. 

Expected Behavior
Users should be able to visually interpret constructions assigned to surfaces/subsurfaces that are inherited. Users should not be able to edit these constructions unless they directly edit the construction set that was used to assign them.

**Comment by jmarrec** [comment] 2016-02-23 14:06
Should be close and just referenced in https://github.com/NREL/OpenStudio/issues/1946

**Comment by macumber** [comment] 2016-02-23 16:15
This is a duplicate of #1946

**Closed** 2016-02-23 16:15 UTC
