### ISSUE TITLE
Support VRF Terminal Unit placement on air loop/OA systems

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#4242] opened 2021-03-11 16:46 UTC
Enhancement Request
--------------
EnergyPlus 9.3.0 added the ability to connect a ZoneHVAC:TerminalUnit:VariableRefrigerantFlow to AirloopHVAC and AirLoopHVAC:OutdoorAirSystem:EquipmentList in https://github.com/NREL/EnergyPlus/pull/7605. Request that this be added to OpenStudio.

## Detailed Description
The following MCVE in v3.1.0 returns false:
```
require 'openstudio'
include OpenStudio::Model
m = Model.new
ahu = AirLoopHVAC.new(m)
tu = ZoneHVACTerminalUnitVariableRefrigerantFlow.new(m)
tu.addToNode(ahu.supplyOutletNode)
```

## Possible Implementation
The EnergyPlus implementation allows for a Terminal Unit without a Fan or OutdoorAirMixer. Supply Air Fan is currently a required field:
```
  A8 ,  \field Supply Air Fan
        \required-field
        \type object-list
        \object-list FansCVandOnOffandVAV
        \object-list FansSystemModel
        \note Supply Air Fan Object Type must be Fan:SystemModel, Fan:OnOff, or Fan:ConstantVolume
        \note if AirConditioner:VariableRefrigerantFlow is used to model VRF outdoor unit
        \note Supply Air Fan Object Type must be Fan:SystemModel or Fan:VariableVolume if
        \note AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl or
        \note AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl:HR
        \note is used to model VRF outdoor unit
```

**Comment by jmarrec** [comment] 2021-03-12 16:17
Duplicate of https://github.com/NREL/OpenStudio/issues/3905

**Comment by jmarrec** [comment] 2021-03-12 16:18
I'm going to close

**Closed by jmarrec** 2021-03-12 16:18 UTC
Labels: Enhancement Request, Triage

**Comment by eringold** [comment] 2021-03-12 16:27
Sorry I missed the existing issue.
