### ISSUE TITLE
As a user, I want to be able to connect the AirConditionerVariableRefrigerantFlow to a plant loop so that I can model WC-VRF units

### ISSUE THREAD

**Issue by pflaumingo** [NREL/OpenStudio#3604] opened 2019-07-17 20:21 UTC
Currently OpenStudio doesn't support water-cooled VRF units as seen in the code here: https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/model/AirConditionerVariableRefrigerantFlow.cpp#L1925

**Comment by kbenne** [comment] 2019-07-17 20:21
@jmarrec are you available for this, or should I pick it up?

**Comment by jmarrec** [comment] 2019-07-31 11:10
@kbenne here's my initial scoping of this. Can you chime in please?
@pflaumingo if you have a few minutes to spare to think about whether you like the user aspect of this or not, and stuff I might have missed, please do let me know.

## Revamp of the VRF object:

* Condenser Type should be exposed
    * `OpenStudio.idd` should uncomment the `! \key EvaporativelyCooled`
    * `AirConditionerVariableRefrigerantFlow::setCondenserType`
        * should allow only "AirCooled" or "EvaporativelyCooled", and only if VRF isn't connected to a PlantLoop already
        * If already connected to a PlantLoop it would warn user that `WaterCooled` is the only possible choice while connected to a PlantLoop, and should disconnect it first
             * The alternative is to have `setCondenserType("AirCooled")`(or evap) disconnect the VRF from its plant loop, but I like that less as I could see users toying with the dropdown in the OS App and ending up making mistakes
* Implement the override `AirConditionerVariableRefrigerantFlow::addToNode`
    * Only accept a node that's on the demand side of a plant loop (cf CoilHeatingWaterBaseboard for an example).
    * If so, call `StraightComponent::addToNode`, if returns true, then set the condenser type to `WaterCooled`. Add Info.
* Similarly, implement an override `removeFromLoop()` which should reset the condenser type to `AirCooled` (and issue a Warn (or Info?) about it).
     * cf: `ChillerElectricEIR` for `addToNode` and `removeFrom(Secondary)PlantLoop` [ChillerElectricEIR.cpp#L783:L803](https://github.com/jmarrec/OpenStudio/blob/develop/openstudiocore/src/model/ChillerElectricEIR.cpp#L783:L803)

* Handle these changes in FT
* Probably adjust the "My Model" and "Library" lists in the Main Right Column Controller to allow dragging and dropping an AirConditionerVRF into a plant loop in OS App.
* Probably adjust the OpenStudioPolicy.xml to show these fields in the OS App. Note: I'm not sure how the dropdown with 3 selections will play out given that we want to restrict the choices in setCondenserType...
* Add unit tests

----

Notes:

* IDD for `AirConditioner:VariableRefrigerantFlow` looked a bit surprising to me. Some field are required in OpenStudio, while they are only used if condenser type is EvaporativelyCooled (which if you read carefully above isn't actually an option in OpenStudio today...). But actually it makes sense, since these fields are either autosizable or hard-set to their default value in the Ctor

**Comment by kbenne** [comment] 2019-07-31 21:09
Sounds good to me.

**Comment by pflaumingo** [comment] 2019-08-13 21:47
Sorry, I'm late to the party. I agree with most of what is being proposed, however, I actually think your alternative suggested is better for when setCondenserType is called with a PlantLoop connected. Doing the proposed rather than the alternative means that whatever object interacts with the condenser will need to know how to peer into its state and then based off of that decide what to do to that same object. I don't think we want the UI to drive the API design.

**Comment by jmarrec** [comment] 2019-08-14 00:20
@pflaumingo that was one example of why I prefer to just reject setCondenserType("AirCooled") if a plant loop. Others:

* It matches the API behavior for other objects such as ChillerElectricEIR (I haven't searched for other occurrences, and I'm the one who did chiller condenser logic, so that's perhaps not a great argument to be fair...)
* I favor warning user before inducing non reversible changes he perhaps didn't anticipate. If you're allowing a simple change like a choice field update to disconnect the plant loop, you cannot go back to watercooled right after (since there's no storage of which plantloop it was connected to nor how it was connected to it). The UI is one thing, interactive ruby is another one too.
* (I've already done it this way is the PR i opened (that's not a valid argument))

@kbenne, can we get the HVAC guru's opinion here?

**Comment by pflaumingo** [comment] 2019-08-14 16:23
I agree with the first point if it's the common implementation throughout the API, but would consider making a breaking change for 3.0 if it results in better API design.

For the second point, I think whether its UI or interactive Ruby its coupling a potential user facing issue for a specific user with the API design and that should be avoided. They are separate concerns even though that specific user is using the API. We could do more to support the interactive scripting user (i.e wrap all method calls in transactions so they can be undone) rather than push the needs for that one user into the API design. Here are some additional counter arguments:
- When setCondenserType returns false, as a user I am unaware if that is because I passed in an invalid string (i.e. "MagicallyCooled") or because it was attached to a PlantLoop and I attempted to set it to AirCooled.
- If I have to check the return type of setCondenserType afterwards then couldn't I just check condenserType before hand? That way setCondenserType will have more of a single responsibility?
`
set? = vrf_cond.setCondenserType('AirCooled')
unless set?
  vrf_cond.disconnect
  vrf_cond.setCondenserType('AirCooled')
`
vs.
`
vrf_cond.disconnect if vrf.condenserType == 'WaterCooled'
vrf.setCondenserType('AirCooled')
`
- Every object that interacts with an object that implements setCondenserType needs to be aware of how to peer into that objects state and decide how to alter it based on said state. If I have 4 classes that alter that condenser object then I have 4 objects that need to know how to alter it. If there are 100 people each with 4 classes then it's the same code in 400 places to alter that one object. Alternatively, given the condenser object has all the information it needs from either it's own state or the arguments passed in from the method, if the condenser object is in charge of altering it's own state related to condenser type then that code only needs to exist once.

I agree that the third point isn't the most valid argument :)

**Comment by jmarrec** [comment] 2019-08-14 21:57
My current PR would return false if connected to a plant loop but also issue a warning saying you need to disconnect it first.

You can already write both versions of your code, checking condenserType before being my preferred option rather than checking the return type, disconnect, then try again.

I guess I can follow your last point (we have different usage of the API for sure so not 100% sure I completely get it).

I don't feel extremely strongly about this, so I have no problem getting behind the consensus. I'd still like to get a third opinion from @kbenne or @macumber ideally.

**Comment by kbenne** [comment] 2019-08-21 19:31
@jmarrec I think it is safe to say we have all been wrestling with figuring out the right way to go. The comments here are just a sample of the discussion that has been elaborated offline. All of it has been very well thought out and considerate so thanks to everyone for fostering a good community. 

I'm personally landing on something that I think and hope is a compromise. The OpenStudio Doctrine if you will.

In other places we have an emerging pattern where if a user does not provide information we wait until idf "translation time" to fill in the details, but if a user does provide information we respect it even if it could result in a bad or failing simulation. In these cases models are default created with a lot of missing details, and if those details have not been filled in at the very last moment (aka translation time) we (OpenStudio) will fill in the details. 

The most famous example is probably set point managers. Where if a component set point manager is provided we respect it no matter what, but on the other hand if the client signals that they know what they are doing and place a setpoint manager we keep it no matter what. This pattern is also found in plant operation schemes and I think even some field level inputs although I cannot point to a specific example off hand.

I propose that we continue this pattern with this current decision on how to handle set/get condeserType. Default construct the object with an empty condenser type. If at translation time the field is still empty, then do topology analysis to provide a reasonable default. If on the other hand a user has provided condenser type input, then respect it even if it might result in bad or even failing simulations. 

Translation time logic to provide a default is probably relatively simple. might I suggest if no plant -> air cooled. if plant with tower -> evap cooled, else water cooled.

We might go as far as to hide the condenser type field in the OS App.

We have had something like this in the past, although @jmarrec moved the logic out of the translator into the model with this commit https://github.com/NREL/OpenStudio/commit/62a1c191505edb8f6e24d085d7c272c11a6fdb1c. I propose we move back to dumb setters and smart translation in an attempt to respect our power users, while still keeping our novice users' models running with good defaults.

The actual logic to determine condenser type from topology could be a method in the model, that is merely called from the idf translator, or any other client who wants to use it.

**Comment by eringold** [comment] 2019-08-21 22:07
Ahem, just chiming in uninvited to note that this:
> if plant with tower -> evap cooled

is not how I understand the evaporatively-cooled condenser option to work. See inputs [Evaporative Condenser Effectiveness](https://bigladdersoftware.com/epx/docs/9-1/input-output-reference/group-variable-refrigerant-flow-equipment.html#field-evaporative-condenser-effectiveness-002), and [Evaporative Condenser Air Flow Rate](https://bigladdersoftware.com/epx/docs/9-1/input-output-reference/group-variable-refrigerant-flow-equipment.html#field-evaporative-condenser-air-flow-rate-002). In particular: 
> If the user wishes to model an air-cooled condenser that has evaporative media placed in front of it to cool the air entering the condenser coil, then the user should specify Condenser Type = EvapCooled.

Any plant connection should cause condenserType -> WaterCooled.

**Comment by jmarrec** [comment] 2019-08-21 22:40
Yes, @eringold. Watercooled if plant. Aircooled or evaporatively cooled if no plant.

I don't like moving that stuff back at FT for ChillerElectricEIR (which behaves exactly the same way as the aircondVRF with respect to condenser type). I like having a getter that would tell me what's the current situation.
My take is to let plant connection/disconnection drive the condenser type with two main (most common) options: aircooled and watercooled.
Power users can switch to evaporatively cooled, if no plant loop.

I'll fall in line anyways like I said earlier. I can move things back to FT if that's the final decision

**Comment by jmarrec** [comment] 2019-08-28 13:30
@kbenne what is the final decision please?

**Comment by kbenne** [comment] 2019-08-30 20:23
@eringold thank you for the correction. 

@jmarrec  My vote is still put logic in FT and no fancy logic in the model's setter / getter. default to empty string and preferably hide in the app. If the field is populated by user then no change in FT. I've convinced myself this is a compromise that is digestible if not great for everyone.

**Comment by jmarrec** [comment] 2019-09-02 09:58
@kbenne Not sure you foresaw this API breaking change: AirConditionnerVariableRefigerant::condenserType will have to become optional.

**Comment by jmarrec** [comment] 2019-09-25 14:25
Fixed via https://github.com/NREL/OpenStudio/pull/3613

**Closed by jmarrec** 2019-09-25 14:25 UTC
Labels: Enhancement Request, component - HVAC

**Comment by MingboPeng** [comment] 2019-10-14 03:18
Thanks everyone for making this work.
But just letting you know, in current 2.9.0 release, adding the VRF to a plantloop demand side crashes the APP right the way.
Please let me know if I am doing anything wrong.
Thanks.

**Comment by jmarrec** [comment] 2019-10-14 05:38
@MingboPeng what plateform are you using? Windows?

Are you dragging from library or "my model". I basically am looking for minimal steps I can do to reproduce

**Comment by jmarrec** [comment] 2019-10-14 08:08
It's a missing icon problem. I know I tested it, found the bug, and fixed it, but I think I did that on another PR, which didn't make it into develop...

**Comment by jmarrec** [comment] 2019-10-14 08:12
Yeah I did it in https://github.com/NREL/OpenStudio/pull/3687.

This is the commit that actually fixes it: https://github.com/NREL/OpenStudio/pull/3687/commits/335ab90e3cca3d0939a68a5cd18a08851db6fbb5
