### ISSUE TITLE
Fwd translation of EMS:InternalVariable does not sub UIDs w/ object names

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#2598] opened 2017-05-06 16:09 UTC
When you create an `EnergyManagementSystemInternalVariable`, the UID of the object that it references does not get converted to the object name in the IDF during forward translation.  I suspect that the solution is to put something like [this code](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateEnergyManagementSystemSensor.cpp#L69-L95) into [the forward translator for `EnergyManagementSystemInternalVariable`](https://github.com/NREL/OpenStudio/blob/develop/openstudiocore/src/energyplus/ForwardTranslator/ForwardTranslateEnergyManagementSystemInternalVariable.cpp#L66-L69).

Here's the code that isn't working correctly:

```Ruby
    fan_pres_var = OpenStudio::Model::EnergyManagementSystemInternalVariable.new(model, 'Fan Nominal Pressure Rise')
    fan_pres_var.setName("#{snc}FanDesignPressure")
    fan_pres_var.setInternalDataIndexKeyName("#{fan.handle}")
```

Results in this object in OSM:

```
OS:EnergyManagementSystem:InternalVariable,
  {23e831e6-5583-408e-8057-7c3db2249ce0}, !- Handle
  CafeteriaZN1FLR1ZNPSZAC27FanDesignPressure, !- Name
  {412f2f6b-f826-481f-bdc3-7fb51f9a7ab6}, !- Internal Data Index Key Name
  Fan Nominal Pressure Rise;              !- Internal Data Type
```

But when it is translated to IDF, the UID is not replaced with the object name:

```
EnergyManagementSystem:InternalVariable,
  CafeteriaZN1FLR1ZNPSZAC27FanDesignPressure, !- Name
  {412f2f6b-f826-481f-bdc3-7fb51f9a7ab6}, !- Internal Data Index Key Name
  Fan Nominal Pressure Rise;              !- Internal Data Type
```

**Workaround**
If you know that the object name will not change after the `EnergyManagementSystemInternalVariable` object is created, you can go ahead and put the object name (instead of the handle) in the call.  For example, you could use:

```Ruby
fan_pres_var.setInternalDataIndexKeyName("#{fan.name}")
```

**Comment by brianlball** [comment] 2017-05-08 14:52
This was a design decision to leave that field as just an /alpha and it doesnt not do any UID substitution since that field can be really anything.  Its similiar to the Actuator Component type and Control Type fields or the Sensor Index Key Name.  Its just too hard to figure out what the "right" values are so its up to the user to put in the right /alpha.

The solution is as you said, the end user should use "name" instead of "handle" in their measure

**Comment by jmarrec** [comment] 2017-09-20 09:55
Seems like this is a "won't fix" issue, so perhaps it should be closed (@macumber)

**Comment by brianlball** [comment] 2017-09-22 14:42
yeah, this is not a bug.  The API functions as designed.  To do whats been requested is a pretty big lift and would need to get funded and prioritized, etc.

**Closed by brianlball** 2017-09-22 14:42 UTC
Labels: component - Code, severity - Normal Bug
