### ISSUE TITLE
MeasureNameTest < MiniTest::Test fails on 64 bit Ruby 200 on Windows

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1345] opened 2015-01-15 18:58 UTC
The default `measure_name_test.rb` file that gets created by the New Measure Wizard uses:

`MeasureNameTest < MiniTest::Test`

When the test is run, you get the following ruby error:

`C:/Ruby200-x64/lib/ruby/2.0.0/minitest/unit.rb:28:in const_missing: uninitialized constant MiniTest::Test (NameError)`

Switching to this seems to do the trick:

`MeasureNameTest < Minitest::Unit::TestCase`

Found this solution [here](https://github.com/seattlerb/minitest/issues/280)

Not sure if this solution will still work with 32bit Ruby 200, but since our default OpenStudio download uses 64-bit Ruby on Windows, we should probably change the code in the New Measure Wizard.

@nllong might want to weigh-in on this since it's a Ruby thing.

**Comment by macumber** [comment] 2015-01-15 20:00
This should be fixed in 1.6.0

https://github.com/NREL/OpenStudio/commit/10635ea7cf9d3a064695e06c4bc84c3b257fa224

**Comment by asparke2** [comment] 2015-01-15 21:44
Sorry, should have checked the code and seen that you addressed it already.  I'm closing this issue.

**Comment by kbenne** [comment] 2015-05-27 15:29
On my Mac, using the system's ruby 2.0, I have exactly the reverse problem.  This change breaks the test for me.

```
Running measure test /Users/kbenne/Development/OpenStudio/build/OSCore-prefix/src/OSCore-build/resources/ruleset/PATMeasures/CalibrationReports//tests/CalibrationReports_Test.rb
MiniTest::Unit::TestCase is now Minitest::Test. From /Users/kbenne/Development/OpenStudio/build/OSCore-prefix/src/OSCore-build/resources/ruleset/PATMeasures/CalibrationReports/tests/CalibrationReports_Test.rb:12:in `<top (required)>'
```

**Comment by macumber** [comment] 2015-05-28 15:22
The version of Ruby built on Windows and Unix for super build is ruby-2.0.0p594, I found [this link](http://apple.stackexchange.com/questions/107853/which-versions-of-mac-os-x-has-ruby-installed-on-default) which says OS X10.9 uses ruby 2.0.0p247.  @kbenne does that match your system?

@axelstudios FYI

**Comment by kbenne** [comment] 2015-05-28 15:23
no i have...

**Comment by kbenne** [comment] 2015-05-28 15:23
```
kbenne-27067s:OpenStudio kbenne$ ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
```

**Comment by macumber** [comment] 2015-05-28 15:24
Well it seems that we need to find a solution that works for all of these versions.

**Comment by kbenne** [comment] 2015-05-28 15:30
Pretty crappy that ruby would have such a breaking change in a build revision.  Not even a minor version increment!  Are we doing it wrong?  Is Apple using some non standard crap?

**Comment by macumber** [comment] 2015-05-28 15:50
Looks like:

    require 'test/unit'
    MiniTest::Unit::TestCase 

is what I found to work for all the cases I tested, https://github.com/NREL/OpenStudio/commit/10635ea7cf9d3a064695e06c4bc84c3b257fa224.  But in 594 it seems to want:

    require 'minitest/autorun'
    MiniTest::Unit::TestCase 

I tested that in several versions and it seems to work.  @kbenne can you fire up irb and see if that works for you?

**Comment by kbenne** [comment] 2015-05-28 15:57
The second one works, the first one does not.

**Comment by kbenne** [comment] 2015-05-28 16:00
you can also just require minitest.  the whole thing.

**Comment by macumber** [comment] 2015-06-18 20:03
@kbenne seems like you have to require 'minitest/autorun' if you want tests to automatically run when loading the test file (which we do)

**Comment by jmarrec** [comment] 2018-01-31 09:24
I got annoyed of having this warning on Ubuntu when running regression tests (Openstudio-resources)

    MiniTest::Unit::TestCase is now Minitest::Test. From model_tests.rb:542:in `<main>'

Google got me to the other github issue asparke linked to, noticed it was a familiar name, and ended up here...

Was there any resolution on this? It runs just fine, just annoying to see it over and over again.

**Comment by asparke2** [comment] 2018-01-31 21:59
I just tested and the following works and removes the annoying message in Windows 7, using Ruby 2.2.4 x64:

`require 'minitest/autorun'`
`class CreateDEERPrototypeBuildingTest < Minitest::Test`

However, I tried running the same measure test using the OpenStudio 2.4.0 CLI and it does not work.  The output error below looks to me like the class `Minitest::Test` does not exist in the version of Ruby that's inside the CLI.

```
> "C:\openstudio-2.4.0\bin\openstudio"  "C:\measures\tests\a_measure_test.rb"
Error: superclass must be a Class (NilClass given)
Backtrace:
	C:\measures\tests\a_measure_test.rb9:in `<top (required)>'
	eval:76:in `require'
	eval:76:in `require'
	:/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	:/openstudio_cli.rb:1312:in `execute'
	:/openstudio_cli.rb:620:in `execute'
	:/openstudio_cli.rb:1547:in `<main>'
	eval:85:in `eval'
	eval:85:in `require_embedded_absolute'
	eval:70:in `block in require'
	eval:64:in `each'
	eval:64:in `require'
	eval:2:in `<main>'
Exception: superclass must be a Class (NilClass given)
<main>: unexpected return
```
Changing back to `Minitest::Unit::TestCase` makes the measure test work in both the CLI and with Ruby 2.2.4 x64 on Windows.  Interestingly, when run from the CLI, `Minitest::Unit::TestCase` doesn't show the annoying message.

@jmarrec can you test this using Ruby directly and the CLI on Mac?

`require 'minitest/autorun'`
`class CreateDEERPrototypeBuildingTest < Minitest::Test`

**Comment by jmarrec** [comment] 2018-02-01 14:38
On Ubuntu 16.04, using the CLI, `Error: superclass must be a Class (NilClass given)`

I cannot use the ruby -i thingy... Because the installation path is so broken on Linux, I actually never really installed openstudio, and just use a local build of mine. never understood why it doesn't work:

```
ruby -I /home/julien/Software/Others/OS-build/Products/ruby/openstudio model_tests.rb -n /baseline_sys06/
/usr/share/rvm/rubies/ruby-2.2.7/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- /usr/Ruby/openstudio.so (LoadError)

```

Typing `irb` then `require /home/julien/Software/Others/OS-build/Products/ruby/openstudio` works just fine...

**Comment by shorowit** [comment] 2018-06-12 16:53
With OpenStudio 2.5.1, `Minitest::Unit::TestCase` appears to work on both Windows and Mac. Though it does give that annoying warning message.

**Comment by jmarrec** [comment] 2021-04-08 13:37
@shorowit do you still see the warning with ruby 2.7.2 ?

**Comment by jmarrec** [comment] 2021-06-07 07:28
I'm closing this one. I don't think there's much to do but provide some backward compat helper like this

```
require 'minitest/autorun'
# Backward compat
Minitest::Test = MiniTest::Unit::TestCase unless defined?(Minitest::Test)

class XXX < Minitest::Test
  ....
end
```

We can reopen if there's more info to reproduce something specific.

**Closed by jmarrec** 2021-06-07 07:28 UTC
Labels: component - Measures, severity - Normal Bug

**Comment by nllong** [comment] 2021-06-07 14:05
I love that they are updating their namespace to be more consistent, but man, these little tweaks get annoying.
