### ISSUE TITLE
openstudio measure --run_tests fails in some situations

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#4035] opened 2020-08-10 17:23 UTC
Issue overview
--------------
I'm running this on a private repository, and it fails to complete for this specific repository. There is something in one or more measures that creates the issue, but I have not identified what.

## Current Behavior
 ========================= Starting Run for Minitest (and coverage) ============================
Current directory is /Users/dgoldwas/Documents/GitHub/NREL/OpenStudio-measures/lib/measures
Pre-processed tests run data in /Users/dgoldwas/Documents/GitHub/NREL/OpenStudio-measures
Test results will be stored in: /Users/dgoldwas/Documents/GitHub/NREL/OpenStudio-measures/lib/measures/test_results
Emptying /test/reports
Error executing argv: []
Error: Read-only file system @ dir_s_mkdir - /test in :/ruby/2.5.0/fileutils.rb:232:in `mkdir'

## Expected Behavior

I ran the exact same command on same computer on other repositories, and it successfully ran and produced a dashboard html.

## Steps to Reproduce

1.
2.
3.
4.

### Environment

I'm on a mac using OpenStudio 3.0.1

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
 - Version of OpenStudio (if using an intermediate build, include SHA):

**Comment by tijcolem** [comment] 2021-04-02 03:23
We should re-test once https://github.com/NREL/OpenStudio/pull/4221 is merged in.

**Comment by jmarrec** [comment] 2021-05-18 10:05
@DavidGoldwasser can you try to reproduce your initial issue. If so, please provide steps so I can reproduce to investigate. Thanks!

**Comment by jmarrec** [comment] 2021-06-07 14:46
I'm closing this one as can't reproduce. We can always reopen later if found again.

**Closed by jmarrec** 2021-06-07 14:46 UTC
Labels: component - Measures, severity - Normal Bug
