### ISSUE TITLE
PAT 1.9.4 crashes when creating a new project or opening an existing one

### ISSUE THREAD

**Issue by pachi** [NREL/OpenStudio#1951] opened 2015-11-15 15:37 UTC
The PAT interface opens OK, but trying to create a new project or opening an existing one (just tried with the files of a failed new one) crashes the application due to an unhandled exception.

Pat.exe fails with Qt5Core.dll (v. 5.3.2.0) and the exception code is c0000005
My operating system version is 6.1.7601.2.1.0.768.3 (Window 7 home premium 32bit with Service Pack 1).

    Unhandled exception at 0x5A17FFC0 (Qt5Core.dll) in Pat.exe: 0xC0000005: Access violation reading location 0x00000004.

**Comment by macumber** [comment] 2015-11-16 16:07
@evanweaver can you take a look on a clean test machine?

**Comment by jmarrec** [comment] 2015-11-17 17:13
Ditto. I have a completely fresh install of windows 10 Pro x64 (after I ran into #1949 I had to reinstall windows), and I can't create a PAT project either, it crashes after I select where I want to

**Comment by evanweaver** [comment] 2015-11-17 17:22
This is a verified issue. Root cause of the Pat crash appears to be the unexpected passing, and subsequent usage, of a null pointer.

**Comment by DavidGoldwasser** [comment] 2015-12-04 06:10
@evanweaver assume this is fixed, but issue just didn't get closed?

**Comment by evanweaver** [comment] 2015-12-04 15:10
Fixed in 1.9.5

**Closed by evanweaver** 2015-12-04 15:10 UTC
