### ISSUE TITLE
Missing components in the app, and duplicate of same object types.

### ISSUE THREAD

**Issue by muh182** [NREL/OpenStudio#1964] opened 2015-11-20 19:32 UTC
@kbenne I just updated my build to 1.9.5. I still see these bugs for the HVAC components.

1- Couple of components for the Fan Constant Volume object
![constantvolumefan](https://cloud.githubusercontent.com/assets/2249257/11309663/1fcf0cd2-8f93-11e5-8ac4-901a2962e258.JPG)

2- Setpoint Manager Humidity Minimum is missing its component. 
![setpoint manager minimum](https://cloud.githubusercontent.com/assets/2249257/11309680/3fa7b194-8f93-11e5-8ee4-d1953dacce56.JPG)

3- The Water Heater - Heat Pump is missing its icon.
![water heater - heat pump](https://cloud.githubusercontent.com/assets/2249257/11309697/526bdf12-8f93-11e5-9983-1cab7b9448f4.JPG)

**Comment by kbenne** [comment] 2015-11-20 19:34
ok thanks for the report. I'll try to squeeze fixes into 1.10.

**Comment by muh182** [comment] 2016-01-29 16:59
@kbenne this is the four pipe fan coil that I showed

![four pipe fan coil](https://cloud.githubusercontent.com/assets/2249257/12682020/826469f0-c67f-11e5-99c3-ca40a44088a5.JPG)

Also, these are the coil cooling and heating that have the component coils exposed in the library.

![coil cooling](https://cloud.githubusercontent.com/assets/2249257/12682045/95a9c186-c67f-11e5-95fd-d189583cbba2.JPG)
![coil heating](https://cloud.githubusercontent.com/assets/2249257/12682049/99211c10-c67f-11e5-941d-e76f3faea964.JPG)

**Comment by DavidGoldwasser** [comment] 2016-04-25 21:33
The multiple constant speed fan objects was confusing for trainings. It would be nice to hide all of the ones except what we want users to see by default. Similar for other objects.

**Comment by macumber** [comment] 2016-11-29 01:57
@kbenne @DavidGoldwasser is this still valid?

**Comment by DavidGoldwasser** [comment] 2016-11-29 17:28
Yes still valid.

**Comment by jmarrec** [comment] 2017-09-29 08:13
Duplicate of #2252

**Comment by jmarrec** [comment] 2019-02-05 22:50
Closed by #3246

**Closed by jmarrec** 2019-02-05 22:50 UTC
Labels: component - OS App, severity - Normal Bug
