### ISSUE TITLE
PAT thinks cluster is running (but it's not)

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio#2721] opened 2017-08-17 15:02 UTC
1 of my 4 PAT projects (which are all very similar) was exhibiting an issue where I open the project in PAT and go to the Run tab, but PAT displays a Connect button instead of a Start button and all of the cluster settings controls are disabled. I could reproduce the issue multiple times by closing PAT and then reopening the project.
![image](https://user-images.githubusercontent.com/5861765/29418625-219d0f0a-832a-11e7-9167-1ac0cf5100b2.png)

Here is the pat.json if it helps:
[pat.json.txt](https://github.com/NREL/OpenStudio/files/1231669/pat.json.txt)

I was able to get around the issue (thanks @kflemin) by clicking the Connect button (I think I had to click it twice actually), which spun up a new EC2 instance (without the prompt asking me to agree that I am responsible, etc.), and then clicking Terminate. Now the Start button appears again and I can edit the cluster settings.

**Comment by rHorsey** [comment] 2017-08-17 21:34
We think this is due to a re-assigned auto AWS IP. The solution will be to parse the below example status.json file.

```
{
"status": {
"awake": "2017-08-16T20:40:57.252+00:00",
"awake_delta": 1490.38
},
"analyses": {
"count": 1,
"na": 0,
"init": 0,
"queued": 0,
"started": 0,
"completed": 1
},
"data_points": {
"count": 36000,
"na": 0,
"queued": 0,
"started": 0,
"completed": 36000
},
"file_systems": []
}
```

**Comment by shorowit** [comment] 2017-08-19 03:39
FYI, it just happened to me again. I was running an analysis in PAT and then Windows decided to restart my machine. (Seriously.) Booted the machine back up, launched PAT, opened the project, and I'm seeing the same thing as the screenshot above. The AWS instance is still running.

**Comment by shorowit** [comment] 2017-08-19 04:10
First time I clicked Connect, it said Error connecting to AWS. Second time I clicked Connect, it launched a new instance without any additional prompt.

**Comment by rHorsey** [comment] 2017-08-24 19:31
This has been resolved by @kflemin - thanks so much! If anyone else can reproduce this post 2.2.1, please reopen the ticket!

**Closed by rHorsey** 2017-08-24 19:31 UTC
Labels: component - PAT, severity - Major Bug
