### ISSUE TITLE
Installing using install.qs script hangs

### ISSUE THREAD

**Issue by IOMadness** [NREL/OpenStudio#3425] opened 2019-02-14 20:48 UTC
Hey, I'm an IT tech at a university, and we're trying to deploy OpenStudio 2.7.0 with Sketchup 2017 to our labs. This is a repost from UnmetHours, as we were trying to deploy this soon. 

I'm running the installer by running OpenStudioInstaller.exe --script=install.qs, and using the install.qs here: https://github.com/NREL/OpenStudio/blob/8c81faf8bc80b0e8f96a4b2764e5958cd060a625/install.qs

I changed it so that all components are selected, and the install directory, however, using the script otherwise as-is, it seems to get stuck after the MaintenanceTool.exe is created, and the installer show, "Installation Complete!", but it hangs at a window waiting for the user to press "next", after which it gets to the final screen where the script takes care of pressing the Finish button.

What I've tried:

Adding a NextButton press in the FinishedPageCallback section a line to the last section:

    Controller.prototype.FinishedPageCallback = function () {
      gui.clickButton(buttons.NextButton);
      gui.clickButton(buttons.FinishButton);
    }

Adding another NextButton press in the ReadyForInstallationPageCallback section:

    Controller.prototype.ReadyForInstallationPageCallbtoack = function () {
      gui.clickButton(buttons.NextButton);
      gui.clickButton(buttons.NextButton);
    }

Adding another NextButton press and changing the Controller.prototype.FinishedPageCallback to Controller.prototype.InstallationFinishedPageCallback:

    Controller.prototype.InstallationFinishedPageCallback = function () {
      gui.clickButton(buttons.NextButton);
      gui.clickButton(buttons.FinishButton);
    }

Nothing seems to take, but interestingly, I've noticed that the installer does not stop at this page when run manually. After creating the maintenance tool, it goes straight to the Install Finished page with the Finish button.

Is there something I'm missing here?

**Comment by macumber** [comment] 2019-02-19 17:10
Closing as duplicate of https://github.com/NREL/OpenStudio/issues/2930

**Closed by macumber** 2019-02-19 17:10 UTC
