### ISSUE TITLE
OpenStudio 2.1.1 Results Tab Unavailable

### ISSUE THREAD

**Issue by johnsontimp** [NREL/OpenStudio#2612] opened 2017-05-17 14:52 UTC
After upgrading to OpenStudio 2.1.0, followed by 2.1.1, I am no longer able to open the "Results Summary" tab in the OS interface on Windows 10 Pro whether I have a model open or not. I am able to run models successfully and view the results in the model folder, but the program locks up after clicking on the "Results Summary" tab. I have tried this with and without the "OpenStudio Results" measure and it does not seem to make a difference. I can access all the files I need, but it is inconvenient to have to dig them up in the folder structure. A coworker is running from the same OpenStudio install file on the same version of Windows and does not have the same issue.  I am running on a Dell M3800 laptop, which has had graphics processor issues in the past, but upgrading drivers did not fix the issue.
![image](https://cloud.githubusercontent.com/assets/22552873/26160258/febe04ec-3add-11e7-8830-d73cc6088282.png)

**Comment by ljbrackney** [comment] 2017-05-17 14:57
Duplicate of Issue 2604

**Closed by ljbrackney** 2017-05-17 14:57 UTC
