### ISSUE TITLE
Effective Air Leakage Area Units Incorrect

### ISSUE THREAD

**Issue by dstuder** [NREL/OpenStudio#1808] opened 2015-08-26 15:34 UTC
In the OS:SpaceInfiltration:EffectiveLeakageArea object, m2 is the listed unit for the "Effective Air Leakage Area" parameter. However, EnergyPlus expects (per the IDD) this to be in units of cm2. I checked the output from my model, and OS is not making this conversion. Seems like the easiest thing to do would be to just relabel this parameter as "cm2".

**Comment by macumber** [comment] 2015-08-26 15:57
Duplicate of https://github.com/NREL/OpenStudio/pull/1575

**Closed by macumber** 2015-08-26 15:57 UTC
