### ISSUE TITLE
Results Summary View Not Working Properly in 1.7

### ISSUE THREAD

**Issue by dstuder** [NREL/OpenStudio#1576] opened 2015-04-06 21:54 UTC
The Results Summary tab in OS 1.7 is not displaying end-use energy consumption properly. Annual values are incorrect and are apportioned oddly over the year. Values were identified as incorrect by converting the OS total kWh to GJ, comparing that value to the energy use shown in the E+ .htm file, and noting that the two do NOT match.

![image](https://cloud.githubusercontent.com/assets/6117383/7013222/8196eeba-dc85-11e4-8035-c3d01bf61055.png)

![image](https://cloud.githubusercontent.com/assets/6117383/7013246/ad2571aa-dc85-11e4-8cc2-8b87c16d182a.png)

**Comment by macumber** [comment] 2015-04-06 21:59
Duplicate of https://github.com/NREL/OpenStudio/issues/1567

 Remove EnergyPlus 8.2.0, installing v8.2.0-Update-1, then running scan for tools

**Closed by macumber** 2015-04-06 21:59 UTC
