### ISSUE TITLE
GridView SpaceTypes - Some strings are right justified vs. left

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1198] opened 2014-09-17 16:32 UTC
This results in the first part of the object name being truncated. I'd generally rather have the end of the name cut off, which is what OS app typically does. See definition name below in screenshot.

![9-17-2014 10-24-46 am](https://cloud.githubusercontent.com/assets/4857055/4307292/379539de-3e88-11e4-9714-d4c9fc3f82c8.png)

**Comment by asparke2** [comment] 2015-01-31 21:21
Closing because @evanweaver fixed this.  Confirmed in 1.6.0 (columns resize so it doesn't truncate.

**Closed by asparke2** 2015-01-31 21:21 UTC
Labels: component - OS App, severity - Minor Bug
