### ISSUE TITLE
Missing EPW in some situations when running slab

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#942] opened 2014-03-26 06:22 UTC
The error shows up on E+ run. This is using Chicago weather file, there is already a know issue with Golden weather file. The two screenshots show the error, and then a crash after I cleared results and tried to re-run. I can' t reproduce this crash. The error finding EPW is repeatable on this file, but works fine with same measure on fresh project. I even tried adding measures in front of the slab program to try to re-produce it.

![3-25-2014 3-18-56 pm](https://f.cloud.github.com/assets/4857055/2521704/ec08ab8a-b4ae-11e3-8aa2-1f4e47f4cbe4.png)

![3-25-2014 11-34-39 pm](https://f.cloud.github.com/assets/4857055/2521705/efeec11c-b4ae-11e3-9365-afbb34a13aff.png)

**Comment by macumber** [comment] 2015-03-18 04:00
@axelstudios this is assigned to you in pivotal, you still able to look at it?

**Comment by macumber** [comment] 2015-03-18 15:55
@axelstudios unless you are working on this i suggest we push it off until 1.8.0 or un-assign milestone

**Comment by axelstudios** [comment] 2015-06-11 17:37
Tested with David, unable to reproduce crash.

**Closed by axelstudios** 2015-06-11 17:37 UTC
Labels: In Progress, severity - Normal Bug
