### ISSUE TITLE
Wrong gbXML import

### ISSUE THREAD

**Issue by nickger** [NREL/OpenStudio#4809] opened 2023-03-02 10:19 UTC
Issue overview
--------------
During import of gbXML geometry a wall is lost.

## Current Behavior
During import of gbXML geometry a wall is lost.

## Expected Behavior
Surfaces should not be removed.

## Steps to Reproduce
The issue exists both in OpenStudio CLI 2.8.1 (comes with Revit) and OpenStudioApplication 3.5 and 2.8.1, so, I believe it is a general API issue. The gbXML is in the attachment.

## Possible Solution
It's been a very long and unsuccessful story, but I do believe it is possible to import gbXML geometry to osm or idf without losses.

### Environment

Windows 10, Revit 2023 to create geometry, OpenStudio CLI 2.8.1, OpenStudioApp 3.5 or 2.8.1

### Context
Without correct import of gbXML it is hardly possible to use OpenStudio in real projects.
[Project1.zip](https://github.com/NREL/OpenStudio/files/10870203/Project1.zip)

**Comment by jmarrec** [comment] 2023-03-07 07:18
@nickger thanks for the report. More information would be welcome so we don't have to spend a lot of time trying to reproduce. 

* Which wall is missing? 
* Sample code to reproduce would be a nice plus
* A screenshot showing the wall in Revit and the missing one in OpenStudioApplication/openstudi-sketchup-plugin would be helpful too probably.

**Comment by jmarrec** [comment] 2023-03-07 07:43
Can't see any wall missing...

```ruby
rt = OpenStudio::GbXML::GbXMLReverseTranslator.new
m = rt.loadModel('Project1.xml').get
model_sfs = m.getSurfaces.map(&:nameString) + m.getShadingSurfaces.map(&:nameString)

require 'nokogiri'
doc = File.open("Project1.xml") { |f| Nokogiri::XML(f) }
sfs = {}
doc.xpath('//xmlns:Surface').each do |s|
  sfs[s.attributes['id'].name] = s.attributes['surfaceType'].value
end
```

```ruby
[1] temp(main)> sfs.size
=> 16
[2] temp(main)> model_sfs.size
=> 17
[3] temp(main)> sfs.keys - model_sfs
=> []
[4] temp(main)> model_sfs - sfs.keys
=> ["aim0223 Reversed"]
```

**Comment by jmarrec** [comment] 2023-03-07 07:52
Side note: the gbxml validation shows these

```
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1868: Element '{http://www.gbxml.org/schema}Transmittance': The attribute 'surfaceType' is required but missing.
    at /Users/julien/Downloads/temp/Project1.xml:1387 while processing "surfaceType"
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1866: Element '{http://www.gbxml.org/schema}WeekSchedule', attribute 'type': The attribute 'type' is not allowed.
    at /Users/julien/Downloads/temp/Project1.xml:1487 while processing "type"
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1868: Element '{http://www.gbxml.org/schema}WeekSchedule': The attribute 'scheduleType' is required but missing.
    at /Users/julien/Downloads/temp/Project1.xml:1487 while processing "scheduleType"
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1866: Element '{http://www.gbxml.org/schema}WeekSchedule', attribute 'type': The attribute 'type' is not allowed.
    at /Users/julien/Downloads/temp/Project1.xml:1491 while processing "type"
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1868: Element '{http://www.gbxml.org/schema}WeekSchedule': The attribute 'scheduleType' is required but missing.
    at /Users/julien/Downloads/temp/Project1.xml:1491 while processing "scheduleType"
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1866: Element '{http://www.gbxml.org/schema}DaySchedule', attribute 'type': The attribute 'type' is not allowed.
    at /Users/julien/Downloads/temp/Project1.xml:1495 while processing "type"
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1868: Element '{http://www.gbxml.org/schema}DaySchedule': The attribute 'scheduleType' is required but missing.
    at /Users/julien/Downloads/temp/Project1.xml:1495 while processing "scheduleType"
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1866: Element '{http://www.gbxml.org/schema}DaySchedule', attribute 'type': The attribute 'type' is not allowed.
    at /Users/julien/Downloads/temp/Project1.xml:1522 while processing "type"
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1868: Element '{http://www.gbxml.org/schema}DaySchedule': The attribute 'scheduleType' is required but missing.
    at /Users/julien/Downloads/temp/Project1.xml:1522 while processing "scheduleType"
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1871: Element '{http://www.gbxml.org/schema}DesignHeatRH': This element is not expected.
    at /Users/julien/Downloads/temp/Project1.xml:1552
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1871: Element '{http://www.gbxml.org/schema}DesignHeatRH': This element is not expected.
    at /Users/julien/Downloads/temp/Project1.xml:1560
```

**Comment by nickger** [comment] 2023-03-07 07:55
Here are the pictures:
![gbXML](https://user-images.githubusercontent.com/74200801/223359066-61f67e71-bad7-4b2f-b108-2f4eac3494b6.PNG)
![OSM](https://user-images.githubusercontent.com/74200801/223359101-6d0270ed-0e1c-4b26-8fed-4d77e9181498.PNG)
Is it a viewer issue? How can I check surfaces in osm model? Any import report?

**Comment by jmarrec** [comment] 2023-03-07 11:43
What is the name of the missing Red surface in Revit? And did you check whether it's in the gbXML to begin with.

The Validator happens when you load the gbxml

```ruby
rt = OpenStudio::GbXML::GbXMLReverseTranslator.new
m = rt.loadModel('Project1.xml').get
```

**Comment by nickger** [comment] 2023-03-07 12:49
I don't understand your code, what language is this..? Is it in interactive mode or smthg?
The surface "aim0433"

**Comment by jmarrec** [comment] 2023-03-08 09:08
This is ruby.

I'm using irb/pry interactive interpreter (REPL) in this specific case. Set "Optional - setup ruby" in https://nrel.github.io/OpenStudio-user-documentation/getting_started/getting_started/

But you can throw that code in "test.rb" (next to Project1.xml) and use `openstudio.exe test.rb` without even installing ruby.

```shell
$ ls
Project1.xml
test.rb
$ cat test.rb
rt = OpenStudio::GbXML::GbXMLReverseTranslator.new
m = rt.loadModel('Project1.xml').get
$ openstudio test.rb
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1868: Element '{http://www.gbxml.org/schema}Transmittance': The attribute 'surfaceType' is required but missing.
    at /Users/julien/Downloads/temp/Project1.xml:1387 while processing "surfaceType"
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1866: Element '{http://www.gbxml.org/schema}WeekSchedule', attribute 'type': The attribute 'type' is not allowed.
    at /Users/julien/Downloads/temp/Project1.xml:1487 while processing "type"
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1868: Element '{http://www.gbxml.org/schema}WeekSchedule': The attribute 'scheduleType' is required but missing.
    at /Users/julien/Downloads/temp/Project1.xml:1487 while processing "scheduleType"
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1866: Element '{http://www.gbxml.org/schema}WeekSchedule', attribute 'type': The attribute 'type' is not allowed.
    at /Users/julien/Downloads/temp/Project1.xml:1491 while processing "type"
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1868: Element '{http://www.gbxml.org/schema}WeekSchedule': The attribute 'scheduleType' is required but missing.
    at /Users/julien/Downloads/temp/Project1.xml:1491 while processing "scheduleType"
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1866: Element '{http://www.gbxml.org/schema}DaySchedule', attribute 'type': The attribute 'type' is not allowed.
    at /Users/julien/Downloads/temp/Project1.xml:1495 while processing "type"
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1868: Element '{http://www.gbxml.org/schema}DaySchedule': The attribute 'scheduleType' is required but missing.
    at /Users/julien/Downloads/temp/Project1.xml:1495 while processing "scheduleType"
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1866: Element '{http://www.gbxml.org/schema}DaySchedule', attribute 'type': The attribute 'type' is not allowed.
    at /Users/julien/Downloads/temp/Project1.xml:1522 while processing "type"
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1868: Element '{http://www.gbxml.org/schema}DaySchedule': The attribute 'scheduleType' is required but missing.
    at /Users/julien/Downloads/temp/Project1.xml:1522 while processing "scheduleType"
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1871: Element '{http://www.gbxml.org/schema}DesignHeatRH': This element is not expected.
    at /Users/julien/Downloads/temp/Project1.xml:1552
[openstudio.XMLValidator] <1> xsdValidate.parseFileError: XML error 17.1871: Element '{http://www.gbxml.org/schema}DesignHeatRH': This element is not expected.
    at /Users/julien/Downloads/temp/Project1.xml:1560
```

**Comment by jmarrec** [comment] 2023-03-08 09:10
`aim0433` is NOT inside your `Project1.xml`. Seems like the problem is between Revit > GbXML.

I'm closing this issue, but if you have more questions the comments are still open.

**Closed by jmarrec** 2023-03-08 09:10 UTC
Labels: resolution - Can't Reproduce, component - gbXML

**Comment by nickger** [comment] 2023-03-08 09:14
Now I remember why I gave up with OpenStudio...
Yes it IS inside of Project1.xml!
[Project1.zip](https://github.com/NREL/OpenStudio/files/10919084/Project1.zip)

**Comment by jmarrec** [comment] 2023-03-08 09:33
@nickger I think I'm being more than helpful here, and I'm definitely trying to go the extra mile to provide detailed, helpful answers, so I'd very much prefer if you watched your tone.

Your Original Post has this link: https://github.com/NREL/OpenStudio/files/10870203/Project1.zip  and **NO**, it is not in there. Your new link does **NOT** include the same Project1.xml.

**Comment by jmarrec** [comment] 2023-03-08 09:37
Using the same code as in https://github.com/NREL/OpenStudio/issues/4809#issuecomment-1457698303 with your new XML.

```ruby
[1] temp(main)> sfs.size
=> 16
[2] temp(main)> model_sfs.size
=> 17
[3] temp(main)> sfs.keys - model_sfs
=> []
[4] temp(main)> model_sfs - sfs.keys
=> ["aim0251 Reversed"]
```

Your surface is there

```
puts m.getSurfaceByName('aim0433').get
OS:Surface,
  {f5bd285d-e4f1-4fd0-a538-0d11bb8019bd}, !- Handle
  aim0433,                                !- Name
  Wall,                                   !- Surface Type
  {6418a26c-76a1-41f0-8420-496f4ae07153}, !- Construction Name
  {445626f5-ecb4-4d6b-9043-047b9e1e9c26}, !- Space Name
  Outdoors,                               !- Outside Boundary Condition
  ,                                       !- Outside Boundary Condition Object
  SunExposed,                             !- Sun Exposure
  WindExposed,                            !- Wind Exposure
  ,                                       !- View Factor to Ground
  ,                                       !- Number of Vertices
  2.1702194, 0, 0,                        !- X,Y,Z Vertex 1 {m}
  3.6796699, 0.752727, 0,                 !- X,Y,Z Vertex 2 {m}
  4.5094599, 1.1755261, 3.15,             !- X,Y,Z Vertex 3 {m}
  2.1702194, 0, 3.15;                     !- X,Y,Z Vertex 4 {m}
```

**Comment by nickger** [comment] 2023-03-08 09:40
So, it's the viewer issue?

**Comment by jmarrec** [comment] 2023-03-08 09:49
Your surface is not planar, so the viewer can't display it. Running OSApp with debug messages enabled in console mode:

```shell
OPENSTUDIO_APPLICATION_DEBUG=1 /Applications/OpenStudioApplication-1.5.0/OpenStudioApp.app/Contents/MacOS/OpenStudioApp
```

Then loading the resulting OSM and going to the geometry tab, I see:

```
[utilities.geometry.computeTriangulation] <1> All points must be on z = 0 plane for triangulation methods
[modelToThreeJS] <1> Failed to triangulate surface aim0433 with 0 sub surfaces
```

**Comment by nickger** [comment] 2023-03-08 09:52
Ok, that's better. What tolerance is acceptable for OS and in what metrics? So I can preprocess gbXML to check planarity.
