### ISSUE TITLE
Importing DDY file creates duplicate design days

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2693] opened 2017-07-16 00:38 UTC
Importing one of the stock E+ DDY files into the App produces duplicate copies of both heating and cooling design days in the App.

![ddy](https://user-images.githubusercontent.com/2230150/28243571-4710b846-6984-11e7-92e5-f8aeacef0803.png)

**Comment by MatthewSteen** [comment] 2017-07-16 01:10
I've noticed this happen in previous versions where if the user has already imported a DDY file and imports one again the app will append the design days rather than replace the existing ones, which can add to sim time on the EnergyPlus end.

**Comment by ljbrackney** [comment] 2017-07-16 02:40
This happens with a brand new model.

On Jul 15, 2017, at 6:10 PM, MatthewSteen <notifications@github.com<mailto:notifications@github.com>> wrote:


I've noticed this happen in previous versions where if the user has already imported a DDY file and imports one again the app will append the design days rather than replace the existing ones, which can add to sim time on the EnergyPlus end.

-

**Comment by jmarrec** [comment] 2017-09-20 09:20
@ljbrackney If you could expand your screen you'll probably see that they aren't duplicates, but different peak conditions such as DB=>MWB, DP=>MWB, etc.

![screen shot 2017-09-20 at 11 18 35 am](https://user-images.githubusercontent.com/5479063/30636385-94c096e2-9df5-11e7-8098-833f9178aed1.png)

I cannot reproduce the duplicate behavior that either you or matt are referring to.

I think it lay be ok to close this issue (fyi @macumber)

**Closed** 2017-11-28 04:31 UTC
Labels: component - OS App, severity - Normal Bug
