### ISSUE TITLE
Improve SQL utility method speeds

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/OpenStudio#4386] opened 2021-08-02 22:07 UTC
Enhancement Request
--------------
The default sql methods in OpenStudio are slow at executing SQL calls.  This feature request is to speed up or adopt another SQL engine to make accessing the model sql files faster.

## Detailed Description
For certain OpenStudio measures, it is necessary to add in several time series output variables.  For example, to calculate detailed unmet hours, the measure needs the zone thermostat setpoint, zone air temperature, and zone occupancy for each zone at each timestep.  Running these calls in OpenStudio on a moderately sized models takes several minutes, and can substantially increase runtimes on large run sets.  In particular, these methods in the SQL file class could be sped up:
execAndReturnFirstDouble
execAndReturnVectorOfDouble
execAndReturnFirstString
execAndReturnVectorOfString

Currently OpenStudio uses the sqlite3 engine.  Perhaps there is a more recent, faster version, or there is some issue with how OpenStudio calls this engine that makes it slow.

For ComStock, we implemented a custom readvarseso program to speed up output reporting.  Perhaps there is a similar method that can be included in OpenStudio to allow faster access to output variable/meter data than an SQL database.

@asparke2 may have thoughts on this.

**Comment by shorowit** [comment] 2021-08-02 22:40
"For certain OpenStudio measures, it is necessary to add in several time series output variables. For example, to calculate detailed unmet hours, the measure needs the zone thermostat setpoint, zone air temperature, and zone occupancy for each zone at each timestep."

For this example, you could switch to creating an EMS program that calculates the cumulative unmet hours value from those output variables. Then you wouldn't need any timeseries output at all.

**Comment by shorowit** [comment] 2021-08-02 22:43
You might also look at the [createIndexes constructor argument for the SqlFile object](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-3.2.1-doc/utilities/html/classopenstudio_1_1_sql_file.html#abe638523b97b3d1f82d419cbda459b29). I recall that it can make a significant difference on speed.

**Comment by jmarrec** [comment] 2021-08-03 13:19
@mdahlhausen "Running these calls in OpenStudio on a moderately sized models takes several minute". Could you share some code to reproduce this please? 

If you could prepare a Minimum Complete Verifiable Example (MCVE) of this (eg: an .OSM with some code running queries) that would be great in order to reproduce the slowness and get insight as to how to fix it. I'll save me the trouble of having to first try to reproduce it!

**Comment by mdahlhausen** [comment] 2021-08-04 18:36
Attached is an example script that calculates the time to run several timeseries calls for each zone in a model to calculate detailed unmet hours (existing method in openstudio-standards):
[NREL Sharepoint](https://nrel.sharepoint.com/:u:/s/NRELBuildings/EXQ4m4BAGaBJsFr2_YBJBTcBmGbpeRsdIwJBzYyQDEUnfw?e=ZDTHdi)
[Google Drive](https://drive.google.com/file/d/1lmgGaf9PApD6kSwk561qzndZzLOvIj9K/view?usp=sharing)

**Comment by jmarrec** [comment] 2021-08-05 12:01
@mdahlhausen Thanks. How do I get it to run though? What version of OS are you using?

```
(py39)julien@4386_SqlSpeed (master *%=)$ openstudio --version
3.2.1+bdbdbc9da6

(py39)julien@4386_SqlSpeed (master *%=)$ openstudio sql_call_speed.rb 
require calls: 4.334 seconds
model load: 9.435 seconds
build std: 9.697 seconds
Error executing argv: []
Error: undefined method `model_get_sql_file' for #<DEER2003:0x00005577ea5833d0> in /home/julien/Software/Others/OpenStudio-Issues/2019-11/4386_SqlSpeed/sql_call_speed.rb:172:in `<top (required)>'
eval:131:in `require'
eval:131:in `require'
:/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
:/openstudio_cli.rb:1560:in `execute'
:/openstudio_cli.rb:803:in `execute'
:/openstudio_cli.rb:1797:in `<main>'
eval:185:in `eval'
eval:185:in `require_embedded_absolute'
eval:170:in `block in require_embedded'
eval:164:in `each'
eval:164:in `require_embedded'
eval:123:in `require'
eval:3:in `<main>'
```

**Comment by jmarrec** [comment] 2021-08-05 12:09
I see the method has been renamed since v0.2.14

https://github.com/NREL/openstudio-standards/blob/b6cc7a7f352df5a807bc71eb94f5f959ec4ce40e/lib/openstudio-standards/utilities/sqlfile.rb#L4

versus master:

https://github.com/NREL/openstudio-standards/blob/e5276526c2424d8e4cd2011b6a7446a01e9ff3c5/lib/openstudio-standards/utilities/sqlfile.rb#L9

**Comment by jmarrec** [comment] 2021-08-05 12:40
@mdahlhausen I'm afraid you're not benchmarking what you think you are. Here is a modified benchmarking script.

https://gist.github.com/jmarrec/d3a028b92df5a30898413205240de5d6

So I'm timing each operation individually (how much time it takes to run that step, versus time elapsed since the beginning). First the high level stuff

```
require openstudio: 0.004 seconds
require openstudio-standards: 4.337 seconds
model load: 5.18 seconds
build std: 0.327 seconds
weather run period: 0.0 seconds
basic sql call to one zone: 0.02 seconds
detailed unmet cooling hours method start
load sql and weather run: 0.0 seconds
```


Then, here's an analysis of the timings results for each zone (I loaded the json I output into python)


![image](https://user-images.githubusercontent.com/5479063/128351388-1440b533-6563-4896-95b6-e28bd994c3e7.png)

![image](https://user-images.githubusercontent.com/5479063/128351408-ed027046-1baf-4def-a195-d69e5c6f11cd.png)

**Comment by jmarrec** [comment] 2021-08-05 13:04
Here is a fairer and simpler benchmark. Note that it is necessary to call **different** timeseries on each iterations (which it is doing, since it changes the zone each time), because there is caching involved.

```
require 'openstudio'

osm_path = "#{File.dirname(__FILE__)}/in.osm"
sql_path = "#{File.dirname(__FILE__)}/eplusout.sql"

load_t = Time.now

translator = OpenStudio::OSVersion::VersionTranslator.new
model = translator.loadModel(osm_path).get

# set SQL file
sql_file = OpenStudio::SqlFile.new(OpenStudio::Path.new(sql_path))
model.setSqlFile(sql_file)

load_t = Time.now - load_t
puts "model load: #{load_t.round(3)} seconds"


ann_env_pd = sql_file.availableEnvPeriods()[0]

timings = []

model.getThermalZones.each do |zone|
  zone_name = zone.nameString()
  one_zone_t = Time.now
  zone_temp_timeseries = sql_file.timeSeries(ann_env_pd, 'Hourly', 'Zone Mean Air Temperature', zone_name).get
  #puts zone_temp_vector.length
  one_zone_t = Time.now - one_zone_t
  timings << one_zone_t
end

puts "N=#{timings.size}, Mean: #{timings.sum(0)/timings.size}, Min: #{timings.min}, Max: #{timings.max}"
puts timings
```

```
(py39)julien@4386_SqlSpeed (master *%=)$ openstudio simple_benchmark_from_model.rb 
model load: 5.358 seconds
N=45, Mean: 0.018191096644444443, Min: 0.017904022, Max: 0.018830569

0.018700271
0.01854084
0.018830569
0.018247663
0.018043787
0.018078282
0.018132114
0.018170247
0.018010062
0.018033377
0.01808241
0.01813507
0.018460877
0.018196797
0.018032726
0.018081118
0.018104562
0.018182359
0.018230451
0.017969967
0.017930011
0.018039689
0.017956782
0.018238686
0.018220372
0.018098381
0.017904022
0.01803509
0.01806117
0.018413959
0.018206947
0.018116495
0.018207758
0.018137795
0.018284964
0.018385896
0.01812427
0.018017998
0.018286728
0.018280245
0.018321474
0.018479633
0.018329368
0.018109812
0.018148255
```

**Comment by jmarrec** [comment] 2021-08-05 13:28
This is a lot better than what I can achieve using python directly.

```
import sqlite3
import pathlib
import os
import pandas as pd
import time

sql_query = """
SELECT dt.VariableValue, Time.Year, Time.Month, Time.Day, Time.Interval FROM ReportVariableData dt
INNER JOIN Time ON Time.timeIndex = dt.TimeIndex 
WHERE  dt.ReportVariableDataDictionaryIndex=2060 AND Time.EnvironmentPeriodIndex = 4
"""

abs_sql_path = os.path.abspath('eplusout.sql')
sql_uri = '{}?mode=ro'.format(pathlib.Path(abs_sql_path).as_uri())

raw_timings = []
with sqlite3.connect(sql_uri, uri=True) as con:
    for i in range(0, 45):
        t1 = time.time()
        # df = pd.read_sql(sql_query, con=con)
        cursor = con.cursor()
        r = cursor.execute(sql_query).fetchall()
        raw_timings.append(time.time() - t1)
```

![image](https://user-images.githubusercontent.com/5479063/128357870-fe787368-f457-421d-98bd-d60082a005e3.png)

**Comment by jmarrec** [comment] 2021-08-05 13:37
I'm going to close this one. For the record, what we use is the C/C++ of SQLite itself (https://www.sqlite.org/cintro.html), so you cannot get closer to the metal than that. Any other library would essential be a wrapper around this API designed to make the programmers life easier in terms of C++ constructs (here you have to remember to free the raw C pointers you use etc which is really annoying) as well as linking.

**Closed by jmarrec** 2021-08-05 13:37 UTC
Labels: Enhancement Request, Performance, component - Utilities Other
