### ISSUE TITLE
Minor update issue on Surface sub-tab of Space tab

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1794] opened 2015-08-21 17:35 UTC
Not critical for 1.9.0 but wanted to document this. In the API if you change a surface's Outside Boundary Condition from "Surface" to something else, it clears out the Outside Boundary Condition Object field. In the screesnhot below surface 28 in story 1 core was linked to surface 16 in story 1 east. When I changed it to "Outdoors" it did correctly also change the value to "Outdoors" for surface 16. It didn't clear out the Outside Boundary Condition object. If you switch away and back to this view it is gone, so the model is fine, jsut a display update issue. Again I don't think tons of people are going to mess with this so pretty minor issue.

![8-21-2015 11-29-42 am](https://cloud.githubusercontent.com/assets/4857055/9414838/aba038a4-47f8-11e5-820f-d838d24362e2.png)

**Comment by DavidGoldwasser** [comment] 2015-12-02 17:40
User pointed out that the construction column also doesn't refresh. Note how the construction for Surfaces 28 and 16 still show an interior wall instead of an exterior wall.

**Comment by macumber** [comment] 2018-01-13 17:04
Duplicate of https://github.com/NREL/OpenStudio/issues/2822 ?

**Comment by jmarrec** [comment] 2018-07-13 14:31
This is not the same as #2822 which is about the OS App Crashing (and I can't reproduce this crash on 2.6.0 on Ubuntu).

David's comment about the refresh thing are still true today though. I'd consider that a pretty minor bug.

**Comment by jmarrec** [comment] 2018-09-06 10:13
I guess the update issue is indeed also in #2822 so we should close this one, keep only one issue

**Comment by DavidGoldwasser** [comment] 2018-09-07 03:42
@jmarrec and @macumber this pre-dates the crash issue by a few years, so it is possible the crash can be fixed without this issue also being fixed. I'm fine if you want to close this and track both through #2822, but just wanted to point out that it didn't always crash, even when it didn't refresh.

**Closed** 2018-09-07 14:49 UTC
Labels: component - OS App, severity - Normal Bug
