### ISSUE TITLE
Address changes made to shared thermostats with make unique (Bugzilla #722)

### ISSUE THREAD

**Issue by axelstudios** [NREL/OpenStudio#123] opened 2013-07-19 20:23 UTC
On 2012-06-07 10:38:41, @DavidGoldwasser wrote:

> You can't change one instance of a shared thermostat without changing them all. I think Dan put some logic in construction sets to address this and make unique on the fly. This occurs when making changes to a thermostat or turning it off.
> 
> For example change an interior floor construction in a construction set, and it only changes for that set (makes unique on the fly)

On 2012-09-06 23:18:58, @DavidGoldwasser wrote:

> This ticket may address this?
> https://www.pivotaltracker.com/story/show/32052595

On 2012-12-17 12:59:58, @DavidGoldwasser wrote:

> In going through 0.9.0 release notes, looks like this is still an issue. We don't need to jump in and fix it now, but should address by March

**Comment by DavidGoldwasser** [comment] 2015-02-01 20:33
This is still valid, I had questions about this just a few weeks ago. I'll re-assign to Kyle.

**Comment by DavidGoldwasser** [comment] 2015-03-14 05:24
@kbenne and @macumber it seems this has become more complex with grid view. Users used to be able to turn off the thermostat which deleted the shared connection between zones. Removing that was a good idea but the end result is that you can't remove a shared thermostat. I think the right fix for this is to have a "Make Unique" test done whenever the App tries to change zone heating or cooling set points, much like is done for construction sets for the same reason. Not sure if we are too late for 1.7.0 for this. It is pretty nasty, but if we can't then maybe we can add in 1.7.1

FYI here is a current post on unmet hours
https://unmethours.com/question/3658/openstudio-16-overwriting-setpoint-schedules/?answer=3672

Here are some relevant screenshots.

Make two thermal zones in OS app that share the same thermostat.
![screen shot 2015-03-13 at 11 02 33 pm](https://cloud.githubusercontent.com/assets/4857055/6650442/e5c333fa-c9d7-11e4-8c43-3e6090830f61.png)

Here is what it looks like in app when you open it
![screen shot 2015-03-13 at 11 04 37 pm](https://cloud.githubusercontent.com/assets/4857055/6650444/ef3824b8-c9d7-11e4-87be-0d9c81ef199a.png)

I made a new schedule and dropped it on one zone.
![screen shot 2015-03-13 at 11 06 41 pm](https://cloud.githubusercontent.com/assets/4857055/6650446/fabb7d62-c9d7-11e4-810e-5e62c6e22366.png)

It looks like it did just what I wanted it to
![screen shot 2015-03-13 at 11 08 49 pm](https://cloud.githubusercontent.com/assets/4857055/6650447/01bc6cca-c9d8-11e4-95e2-0c096a78ce57.png)

But when I leave that tab and come back all zones were affected. I confirmed this by inspecting the file
![screen shot 2015-03-13 at 11 09 05 pm](https://cloud.githubusercontent.com/assets/4857055/6650449/164ee06e-c9d8-11e4-8764-22ba375fd9ef.png)

**Comment by DavidGoldwasser** [comment] 2015-06-25 14:46
@kbenne @macumber @lgentile this continues to come up on unmethours. I don't want us to touch this for 1.8.0, but we should fix it for 1.9.0. There isn't any real reason we couldn't put it in a early 1.8.x iteration installer instead of waiting for crunch time when we get close to 1.9.0 release.

**Comment by DavidGoldwasser** [comment] 2015-10-23 14:56
@kbenne and @macumber maybe we can look at this for 1.10? Still coming up
https://unmethours.com/question/12156/bug-report-thermostat/

**Comment by macumber** [comment] 2015-10-23 17:55
Is the proposed fix known or does that still have to be thought through?

**Comment by DavidGoldwasser** [comment] 2015-10-23 18:55
There are a few options that have been discussed
1. Get rid of any concept of thermostats in our templates and in the plugin. The "Space Attributes" dialog would have fields for heating stepping and cooling setpoint in place of a thermostat.
2. In the OS app if you someone tries to alter a shared object we can make it unique. @macumber I think this is what you did for this object (https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-1.9.0-doc/model/html/classopenstudio_1_1model_1_1_default_surface_constructions.html)
3. OS app could treat thermostat like s shared resource, @kbenne I know you don't like this. 
4. We could change the API to make the thermostat a child of a zone (this would break a lot and is probably bad).

I asume 1 and or 2 are the most likely solution. To would add support for all the models that are already out there, while 1 would only work for people making new models, assuming they don't use a measure that creates shared thermostats.

**Comment by macumber** [comment] 2015-11-11 22:18
@kbenne this still sounds like it is in discussion phase, in which case it isn't going to make 1.10, is that right?  If so let's remove the milestone

**Comment by kbenne** [comment] 2016-01-19 21:28
@DavidGoldwasser I think this issue is resolved based on the work over in #985. Do you agree that we can close this one?

**Closed** 2016-01-25 21:34 UTC
Labels: component - OS App, severity - Major Bug
