### ISSUE TITLE
Internal NREL user specific Analysis Error related to Faraday

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#2493] opened 2017-03-01 15:55 UTC
Only get successful runs in PAT if I first shut down server and then choose "Run entire workflow

@asparke2 and @henryHorsey I just wanted to put content of emails in one place here. @kflemin was not able to reproduce this, and I don't think others can either. I'll try 2.0.4 on home mac to see what happens.

This is one type of error
`stderr:  /Users/dgoldwas/Applications/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/ruby/lib/ruby/2.2.0/net/http/generic_request.rb:205:in `write': Broken pipe (Faraday::ConnectionFailed)`

Here is anoter
`stderr:  /Users/dgoldwas/Applications/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-analysis-1.0.0.rc14/lib/openstudio/analysis/server_api.rb:497:in `new_analysis': #<Faraday::Response:0x007f9b32ace408 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:post @body="<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\">\n<HTML>\n  <HEAD><TITLE>Internal Server Error</TITLE></HEAD>\n  <BODY>\n    <H1>Internal Server Error</H1>\n    bad content body\n    <HR>\n    <ADDRESS>\n     WEBrick/1.3.1 (Ruby/2.2.4/2015-12-16) at\n     localhost:8080\n    </ADDRESS>\n  </BODY>\n</HTML>\n" @url=#<URI::HTTP http://localhost:8080/analyses/5355548b-7cf1-42b9-a1ee-2faf9e63c8b9/upload.json> @request=#<Faraday::RequestOptions timeout=1800, boundary="-----------RubyMultipartPost"> @request_headers={"User-Agent"=>"Faraday v0.11.0", "Content-Type"=>"multipart/form-data; boundary=-----------RubyMultipartPost", "Content-Length"=>"2700488"} @ssl=#<Faraday::SSLOptions (empty)> @response=#<Faraday::Response:0x007f9b32ace408 ...> @response_headers={"content-type"=>"text/html; charset=ISO-8859-1", "server"=>"WEBrick/1.3.1 (Ruby/2.2.4/2015-12-16)", "date"=>"Wed, 22 Feb 2017 16:57:15 GMT", "content-length"=>"296", "connection"=>"close"} @status=500 @reason_phrase="Internal Server Error">> (RuntimeError)
from /Users/dgoldwas/Applications/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/gems/gems/openstudio-analysis-1.0.0.rc14/lib/openstudio/analysis/server_api.rb:773:in `run'
from /Users/dgoldwas/Applications/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/bin/openstudio_meta:806:in `execute'
from /Users/dgoldwas/Applications/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/bin/openstudio_meta:205:in `execute'
from /Users/dgoldwas/Applications/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/bin/openstudio_meta:832:in `<main>'

app-daac3224f6.js:6166 exec error:  Error: Command failed: "/Users/dgoldwas/Applications/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/ruby/bin/ruby" "/Users/dgoldwas/Applications/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/bin/openstudio_meta" run_analysis --debug --verbose --ruby-lib-path="/Users/dgoldwas/Applications/openstudio-2.0.3/ParametricAnalysisTool.app/Contents/Resources/OpenStudio/Ruby" "/Users/dgoldwas/Documents/working/PAT_01311341_zedg_test/PAT_01311341_zedg_test.json" "http://localhost:8080" -a batch_datapoints(…)
app-daac3224f6.js:6175 child closed due to receipt of signal null (exit code 1)
vendor-aa1ece4cd9.js:24014 ANALYSIS NOT STARTED, ERROR:  undefined`

I can provide zip file of full logs (floating around somewhere on flash drive but easy to reproduce)

**Comment by DavidGoldwasser** [comment] 2017-03-01 15:57
@kbenne do you think this can have any relation to #2492. Is there an issue with the installer running for my directory vs. default location that causes this. I only ask because both of these issues seem to be unique to my machine.

**Comment by kbenne** [comment] 2017-03-01 16:36
Not sure, but possible. Pat (Rails) is trying to write files next to the installation. If you install OpenStudio anywhere outside of your home directory (places you don't have write access to) then I expect trouble.

**Comment by asparke2** [comment] 2017-03-14 20:49
@evanweaver Can you test this on a clean Mac?  @DavidGoldwasser has seen this, but @ljbrackney has not.  Need to figure out whether it is developer-specific or is going to be a common problem for users.

**Comment by DavidGoldwasser** [comment] 2017-03-21 16:40
@henryHorsey this bug was already logged and open. Behavior is similar to this.

I can generally get clean run by either 

1. Clicking "Run Entire Workflow" prior to the "Server Status" going to green
2. Clicking "Stop Local Server" and then "Run Entire Workflow"
3. Try to run 10 times, and may work one time?

Each failed attempt adds an analysis with no datapoints and unknown status.

- Running while dis-connected from internet didn't didn't change anything
- After good run, I generally have to repeat step 2 (stop server and click "RunEntire Workflow")
- I have seen this happen on local run, NREL24b, and AWS. I have also seen runs work cleanly in all three of these locations.

**Comment by DavidGoldwasser** [comment] 2017-03-21 16:52
Not sure if useful, but when I look at the analysis log on server there are 900 lines of normal looking log

Then this repeats for about 100 lines
```[1] "Check Run Flag run command: ruby /opt/openstudio/R/lib/api_get_status.rb -h http://web:80 -a 4cf17ee8-650b-443d-b634-0e080cff15d6"
[1] "Check Run Flag z: {:submit_simulation=>false, :sleep_time=>5, :host=>\"http://web:80\", :analysis_id=>\"4cf17ee8-650b-443d-b634-0e080cff15d6\"}"
[2] "Check Run Flag z: {\"status\":true,\"result\":true}" 
[1] "run_flag_json: TRUE" "run_flag_json: TRUE"
[1] "run command: ruby /opt/openstudio/R/lib/api_create_datapoint.rb -h http://web:80 -a 4cf17ee8-650b-443d-b634-0e080cff15d6 -v 51.8953452067217,92.6102900783007 --submit"```

Then this repeats for 126k lines (but the id shown change each time)
```
[1] "Create and Run Datapoint 1 z: {\"status\":false,\"id\":\"9a134f7e-3fe2-41b1-8709-4ed2354ed600\"}"
[1] "json: FALSE" 
[2] "json: 9a134f7e-3fe2-41b1-8709-4ed2354ed600"```

**Comment by brianlball** [comment] 2017-03-21 17:05
these are just debugging messages
whats the value of 'debug_messages' in your analysis.json?

**Comment by DavidGoldwasser** [comment] 2017-03-21 17:28
@brianlball when NREL24b is free I can re-send the long was from NREL24b. When I run from PAT app not sure what equivalent file is. 'temp_data just has empty directories and I don't find 'debug_messages' in 'PAT_0321_0809.json' or 'pat.json'

![screen shot 2017-03-21 at 11 26 26 am](https://cloud.githubusercontent.com/assets/4857055/24161275/88fb69c4-0e29-11e7-94b5-23c0738e1592.png)

**Comment by evanweaver** [comment] 2017-03-21 20:45
@asparke2 No problems on my Mac VM currently.

**Comment by asparke2** [comment] 2017-03-23 20:23
We have isolated the cause of this bug.  If one or more of the measures in a project contains a lot of files (or a few large files), creating the `analysis.zip` file takes a while.  There is currently no checking that the `analysis.zip` is complete before it is sent to the server.  On Mac, this manifests as a `Faraday` error in the PAT log and on Windows looks like an `ERROR EOFError: bad content body` error in the rails log.

This has only impacted internal users who had measure test output in the measures they were using, because these output directories often contained .sql files and large .osm files.

**Comment by kflemin** [comment] 2017-03-28 17:17
this should be fixed.

**Closed** 2017-04-14 05:10 UTC
Labels: component - PAT
