### ISSUE TITLE
May be conflict between SkechUp Plugin OpenStudio 1.5.0 and Trane System Analyzer 6.0.0

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1253] opened 2014-10-24 14:59 UTC
Just to clarify System Analyzer doesn't have a SketchUp component but still seemed to interfere with function of the plugin. @macumber I'm not sure we should do anything with this quite yet, but should keep an eye on it and coordinate with Trane if necessary? There is a 6.1 System Analyzer out, not sure if it has same issue. So far there is just a single report of this

Below is the console output when Plugin is launched. Re-installing OpenStudio didn't help. Un-intalling System Analyzer did.

Error Loading File C:/ProgramData/SketchUp/SketchUp 2014/SketchUp/Plugins/OpenStudio/Startup.rb
Error: #<RuntimeError: Unable to initialize OpenSSL: Verify that ruby can access the OpenSSL libraries> C:/Program Files (x86)/OpenStudio 1.5.0/Ruby/openstudio.rb:127:in `<top (required)>'
C:/Program Files (x86)/SketchUp/SketchUp 2014/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:45:in `require'
C:/Program Files (x86)/SketchUp/SketchUp 2014/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:45:in `require'
C:/ProgramData/SketchUp/SketchUp 2014/SketchUp/Plugins/OpenStudio/OpenStudio-config.rb:1:in `<top (required)>'
C:/Program Files (x86)/SketchUp/SketchUp 2014/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:45:in `require'
C:/Program Files (x86)/SketchUp/SketchUp 2014/Tools/RubyStdLib/rubygems/core_ext/kernel_require.rb:45:in `require'
C:/ProgramData/SketchUp/SketchUp 2014/SketchUp/Plugins/OpenStudio/Startup.rb:26:in `<top (required)>'
C:/Program Files (x86)/SketchUp/SketchUp 2014/Tools/extensions.rb:197:in `require'
C:/Program Files (x86)/SketchUp/SketchUp 2014/Tools/extensions.rb:197:in `load'
C:/ProgramData/SketchUp/SketchUp 2014/SketchUp/Plugins/OpenStudio.rb:167:in `register_extension'
C:/ProgramData/SketchUp/SketchUp 2014/SketchUp/Plugins/OpenStudio.rb:167:in `<top (required)>'

**Comment by asparke2** [comment] 2015-01-31 20:57
closing since @axelstudios couldn't reproduce.

**Closed by asparke2** 2015-01-31 20:57 UTC
Labels: component - SketchUp, Low Frequency, resolution - Can't Reproduce, severity - Normal Bug
