### ISSUE TITLE
Segfault in Materials Tab

### ISSUE THREAD

**Issue by ljbrackney** [NREL/OpenStudio#2694] opened 2017-07-20 17:38 UTC
App Segfaults when opening Materials Sub-Tab.  Other Constructions Sub-Tabs are fine.  Model runs okay.

[openstudio.units.QuantityConverter] <1> Cannot convert base unit 'g' to SI because it is not registered with the QuantityConverter.
[BOOST_ASSERT] <2> Assertion test failed on line 65 of openstudio::OSQuantityEdit2::OSQuantityEdit2(const std::string &, const std::string &, const std::string &, bool, QWidget *) in file /Users/lbrackne/GitHub/OpenStudio/openstudiocore/src/shared_gui_components/OSQuantityEdit.cpp.
[BOOST_ASSERT] <2> Assertion test failed on line 65 of openstudio::OSQuantityEdit2::OSQuantityEdit2(const std::string &, const std::string &, const std::string &, bool, QWidget *) in file /Users/lbrackne/GitHub/OpenStudio/openstudiocore/src/shared_gui_components/OSQuantityEdit.cpp.
Assertion failed: (false), function assertion_failed, file /Users/lbrackne/GitHub/OpenStudio/openstudiocore/src/openstudio_app/../model/../utilities/core/Assert.hpp, line 60.
Abort trap: 6

[Case600FF.osm.zip](https://github.com/NREL/OpenStudio/files/1163215/Case600FF.osm.zip)

**Comment by evanweaver** [comment] 2017-07-20 18:45
@ljbrackney are you using a debug build of the current dev tip?

**Comment by ljbrackney** [comment] 2017-07-20 18:56
Current build from Dan's branch.  Please confirm this behavior in release with the model I attached.

**Comment by evanweaver** [comment] 2017-07-20 19:03
@ljbrackney sorry, but we've all made lots of branches. Are you using geometry_editor? That appears to be Dan's currently active branch.

**Comment by ljbrackney** [comment] 2017-07-20 19:05
Yes

**Comment by evanweaver** [comment] 2017-07-21 15:52
@ljbrackney here are my findings:

This particular segfault does not occur in  a release build of geometry_editor nor the 2.2.0 release; no release user will encounter this assert-fail generated segfault.

That said, there was a subtle error made re-implementing units after the demise of Qt: gram (g) was used and for whatever reason that unit is not handled in the units conversion code. The "correct" implementation as found in 1.14.0 is "millikilograms". I've corrected the code and committed it to develop.

An additional note: if you continue to use a debug build with this particular model, you will hit another assert-fail at line 543 of OSConcepts.hpp ( OS_ASSERT(m_choicesMap.find(result) != m_choicesMap.end()); ). The reason for this assert-fail is that the find is case-sensitive, and this model has "AIR", rather than "Air". @kbenne and I had discussion years ago about case-sensitive searches in OSConcepts, but left it as is. Again, a user of our releases will not encounter any segfault here.

Let me know any thoughts or concerns. I've given you the Pivotal ticket for your review.

**Comment by macumber** [comment] 2017-07-21 16:06
Asserts won't be hit in release mode, but asserts should only be used in cases where another error will occur immediately afterwards.  So either these asserts are incorrect and should be removed or they are correct and need to be fixed.

**Comment by evanweaver** [comment] 2017-07-21 16:17
@macumber I agree. The first assert hit using this model was useful and the problem was fixed. The second assert is in place to verify OSConcept templates and related (i.e. GridView) implementation; it's not intended to verify a model. We could remove this assert, but it is useful for future development. We could make the find not case-sensitive, but I believe that encountered unexpected behaviors related to that, which is why we left it case sensitive. We could more vigorously verify model accuracy to idd text strings, but that is beyond that scope of this issue. I think it's a non-issue and I vote for using a release build and moving on. However, if you want me to do more, just let me know :)

**Comment by ljbrackney** [comment] 2017-07-21 22:36
Verified that this specific segfault was fixed in Develop and that tab works correctly in Release

**Comment by evanweaver** [comment] 2017-07-24 14:51
Accepted 7/21/2017 here: https://www.pivotaltracker.com/n/projects/134010/stories/149252651

**Closed by evanweaver** 2017-07-24 14:51 UTC
Labels: component - OS App, severity - Blocker
