### ISSUE TITLE
OpenStudio 2.0.0 path installation on mac

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio#2428] opened 2017-01-09 11:50 UTC
System info:

* Sketchup 2016
* macOS Sierra 10.12.2
* OpenStudio 2.0.0 (47ba3cbe19)

----

I’m installing OpenStudio 2.0.0 on mac

I noticed that it’s trying to install to `/usr/local/openstudio-2.0.0`. Before it went to to `/Applications/openstudio-x-x`.

There’s a cli so I guess it makes sense that one goes to `/usr/local`… but not sure if putting all of it to`/usr/loca/l`makes that much sense. Might be offputing to users who aren’t familiar with Unix systems too.

Another problem is that the `OpenStudioApp.app` and `ParametricAnalysisTool.app`aren't at all simlinked to `/Applications` so I can’t easily find the apps (I have to launch them via a terminal or the Finder > Go To Folder).

I would suggest installing everything to `/Applications` and add the cli to the path or to simlink it to /usr/local instead

**Comment by kbenne** [comment] 2017-01-09 15:38
Yep I agree and pretty much all of this. My plan is to leave the base of the installer in /usr/local, but run a post flight script to move the .app programs into /Applications, link the openstudio cli into the PATH, and put the ruby bindings in the RUBY_PATH.

**Comment by macumber** [comment] 2017-03-07 00:55
@kbenne should this be closed?

**Comment by jmarrec** [comment] 2017-03-28 13:59
It now installs to `/Applications/OpenStudio-2.0.5` and the cli is put in `/usr/local/bin/openstudio`. I cannot see any variable $RUBY_PATH though.

**Comment by kbenne** [comment] 2017-03-28 14:07
The cli in /usr/local/bin/openstudio is actually a symbolic link. I'm glad to know you have confirmed it is working.

The install path in /Applications/OpenStudio-2.0.5. is also according to plan. I would rather have spaces instead of "-", but parts of PAT do not play well with spaces.

The installer is not currently trying to put the ruby bindings in the ruby path. This is 90% by design and maybe 10% lazy. The problem with putting the ruby bindings in the ruby path is that the OS X system ruby is not compatible with the bindings (wrong version). Trying to steer people to the cli anyway. 

FYI if we did put openstudio in the ruby path we would do it with a symbolic link into /Library/Ruby/... or whatever the standard ruby lib path is. This is how we did it in the 1.x series. No $RUBY_PATH vars.

**Comment by kbenne** [comment] 2017-03-28 14:08
I want to close this is @jmarrec gives it a thumbs up.

**Comment by jmarrec** [comment] 2017-03-28 14:12
Yeah I don't think it's necessary to add it to the Ruby path, I use my system ruby for interactive sessions anyways. 

I figured it was a symlink. I'm wondering if the owner shouldn't be the user rather than `root`

    (py36)julien@~$ ls -l /usr/local/bin/open*
lrwxr-xr-x  1 root  staff  45 Mar 16 01:05 /usr/local/bin/openstudio -> /Applications/OpenStudio-2.0.5/bin/openstudio

Other than that, I'd say you can close.

**Comment by kbenne** [comment] 2017-03-28 14:18
root owner is what we want. read / execute everyone. write only if you are God.

**Comment by jmarrec** [comment] 2017-04-04 09:06
@kbenne I installed the os 2.1.0, it didn't update the /usr/local/bin/openstudio symlink

**Comment by kbenne** [comment] 2017-04-04 13:57
didn't "update"

Does that mean you had a link, perhaps to a previous install, but it didn't get updated to point to the new install?

**Comment by jmarrec** [comment] 2017-04-04 14:26
That is correct, it was pointing to openstudio-2.0.5 which I had trashed (didn't use the maintenance tool, I trashed the entire folder)

**Comment by kbenne** [comment] 2017-04-04 14:29
ok. I can fix this. 

The maintenance tool will by the way remove the link.

**Comment by jmarrec** [comment] 2017-05-12 12:01
I installed 2.1.1 and I don't have a symlink to /usr/local/bin/openstudio anymore

**Comment by rHorsey** [comment] 2017-05-12 14:12
Seconded. I had an old 2.0.5, rmrf'ed it, installed 2.1.1, and the old 2.0.5 symlink-to-nowhere persisted. I just assumed rmrf-ing was not supported behavior, but if the installer could overwrite the symlink than that would be very cool.

**Comment by jmarrec** [comment] 2017-08-03 07:59
Don't have a symlink in 2.2.0.

Had to run `ln -s /Applications/OpenStudio-2.2.0/bin/openstudio /usr/local/bin/openstudio`

**Comment by jmarrec** [comment] 2017-10-02 08:07
Still true in 2.3.0

**Comment by macumber** [comment] 2018-01-23 20:53
Is this the root cause of this other bug? https://github.com/NREL/OpenStudio-PAT/issues/52#issuecomment-359920661

**Comment by macumber** [comment] 2018-01-23 20:53
Raising to major as this seems to be causing other issues

**Comment by macumber** [comment] 2018-01-23 20:53
https://github.com/NREL/OpenStudio/issues/2561

**Closed** 2018-03-06 16:53 UTC
Labels: component - Installer/Platform, severity - Major Bug
