### ISSUE TITLE
Fresh develop build Crash "Bad cast" after clicking on "Spaces" tab

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#1836] opened 2015-09-03 22:40 UTC
Is repeatable with this model, but some other models I have seem fine.To reproduce open the linked model and then go to spaces tab. Takes about a minute, then you briefly see grid come up, then just after that the unhanded exception happens. I think model has in neighborhood of 40 spaces.

![9-3-2015 4-33-27 pm](https://cloud.githubusercontent.com/assets/4857055/9672744/735b5c46-525a-11e5-880a-2f2ed92057dd.png)

![9-3-2015 10-36-47 pm](https://cloud.githubusercontent.com/assets/4857055/9676710/2602249c-528d-11e5-9352-2a160e04e8d6.png)

https://github.com/NREL/OpenStudio-files/tree/master/Git%20Issue%20Files/issue1836

**Comment by DavidGoldwasser** [comment] 2015-09-04 05:30
The model in original post was made from AEDG measures with earlier version of OpenStudio. I tried to re-run the measures using 1.8.5 and then open the resulting file in the OS app. I see the same crash. Here is the workflow I'm running
https://github.com/DavidGoldwasser/OpenStudio-programmatic-modeling/blob/nrel_measure_group_testing/projects/workflow_aedg_k12.rb

To make sure the seed model wasn't the issue, I opened the seed, which only has geometry and spaces type assignments, in the OS app and it didn't have a problem on the spaces tab.

**Comment by DavidGoldwasser** [comment] 2015-09-04 05:54
The original file I put up is this
AedgK12HvacFanCoilDoas_ASHRAE 169-2006-5B.osm

I just uploaded another one. This was made with a different seed and a different set of measures (although the AEDG office measures are similar to the AEDG K12 measures). It has similar crash.
AedgOfficeHvacAshpDoas_ASHRAE 169-2006-5B.osm

**Comment by evanweaver** [comment] 2015-09-04 05:54
David,  because you are using a debug build,  you are subject to asserts failing.  These are useful for developers investIgating root cause,  but not always critical and not something users are exposed to with a release build. I'll investigate further tomorrow by clicking the "Retry" button, but from the area that the code failed,  my guess is that you have a slightly malformed model; an IDD key simply has improper capitalization. A release build will not complain a about that,  but a debug build will.

**Comment by DavidGoldwasser** [comment] 2015-09-04 06:00
I have a release build as well. I see the crash in it, and also in 1.8.4 installer.If my measures are making invalid objects then I'll get them updated. I thought that generally the API doesn't accept invalid inputs. I added blocker, but that is really that I feel we need to address for release, not specifically for 1.8.5 unless others are seeing this as well.

**Comment by DavidGoldwasser** [comment] 2015-09-04 15:11
I had my suspicion that there were objects unique to the AEDG models that we just weren't seeing in other models. My first target was fenestration and daylighting controls measure, it does does a number of things that are not common. 
https://github.com/NREL/OpenStudio-measures/blob/develop/NREL%20working%20measures/AedgK12FenestrationAndDaylightingControls/measure.rb

Removing this measure did get rid of the crash. My guess is that one or more of the conditions below is triggering the crash.
- multiple fenestration surfaces in a single base surface
- light shelves
- interior partitions
- skylights (may have 50 or more sub-surfaces in a base surface)
- blinds
- shading controls
- daylighting control points.

@macumber may have some ideas, he made many of the new objects used for the AEDG's.

**Comment by evanweaver** [comment] 2015-09-04 15:16
@DavidGoldwasser, rather than investing more time here, give me a moment to succinctly investigate by using the debugger. I'm balancing a number of things at the moment, and will get to this soon.

**Comment by macumber** [comment] 2015-09-04 15:43
Thanks @DavidGoldwasser, @evanweaver has a lot going on today, he'll take a look at this when he gets a chance and can pull me in if he has any questions.  I'm not opposed to slipping 1.8.5 if we find out that this is a bug that users of the packages would see, we don't want people testing stuff we know is broken.  But let's given Evan some time to trace it down.

**Comment by DavidGoldwasser** [comment] 2015-09-04 15:52
Thanks @macumber and @evanweaver I understand there are a lot off competing needs. I wasn't trying to push but just help narrow down the cause. If it is just specific objects, which it looks like to me, then maybe no need to hold up 1.8.5. I could spend an hour or so to isolate the exact object(s) but if you don't want me to that's fine. 

I do feel good that I can reproduce it entirely from measures, so we know there aren't any GUI or version translation gremlins sneaking in. It's also nice to know the full history of the file for a change. (e.g. you don't have to add something the delete to cause an issue).

**Comment by macumber** [comment] 2015-09-04 16:01
Hey @DavidGoldwasser I just talked with @evanweaver and it is clear he is a machine at squashing these bugs, he knows exactly what is going on and how to fix it, right now he is just waiting on his build to finish.  So this was good testing to find this but at this point Evan has it under control, he just needs time to get to it.

**Comment by evanweaver** [comment] 2015-09-05 02:26
Fixed via https://www.pivotaltracker.com/n/projects/134010/stories/102755696

**Closed** 2015-09-08 16:58 UTC
Labels: component - OS App, In Progress, severity - Blocker
