### ISSUE TITLE
PAT slow switching to tab 3

### ISSUE THREAD

**Issue by macumber** [NREL/OpenStudio#1116] opened 2014-06-30 20:59 UTC
Looks like OSResult::load is called excessively when switching to tab 3

**Comment by asparke2** [comment] 2015-01-31 22:07
@macumber Do you think this is a duplicate of https://github.com/NREL/OpenStudio/issues/1363

**Comment by macumber** [comment] 2015-02-04 20:36
Not a duplicate

**Comment by asparke2** [comment] 2017-05-10 18:59
PAT 1.X issue, no longer relevant.

**Closed by asparke2** 2017-05-10 18:59 UTC
Labels: component - PAT, resolution - Won't Fix, severity - Normal Bug
