### ISSUE TITLE
Measure Manager Crashes with error computing arguments

### ISSUE THREAD

**Issue by anchapin** [NREL/OpenStudio#3326] opened 2018-10-30 03:17 UTC
When I try to add a measure to the measure tab or via the apply measure now window I get the following two error windows. I also can't simulate the model in either PAT or the OS App. I'm using OpenStudio 2.7.0 x64 on Windows. Note that this doesn't happen when attempting to either add a measure to the measure tab or via the apply measure now window with a blank OpenStudio file or one without DX coils.

Note that I didn't get this error with OpenStudio 2.6.0 x64 on Windows. It appears that the issue is due to an assertion curve failure on line 452 of class openstudio::model::Curve __cdecl openstudio::model::detail::CoilHeatingDXSingleSpeed_Impl::energyInputRatioFunctionofFlowFractionCurve(void) const in file C:\Git\OS\openstudiocore\src\model\CoilHeatingDXSingleSpeed.cpp.

![measure manager has crashed](https://user-images.githubusercontent.com/6326294/47693637-d3545500-dbd0-11e8-9b22-aaf16a6c6037.png)
![unhandled exception](https://user-images.githubusercontent.com/6326294/47693641-d5b6af00-dbd0-11e8-9d4e-5ec2b5a2d89e.png)

**Comment by DavidGoldwasser** [comment] 2018-10-30 14:53
Normally this kind of failure is related to problem with forward translation from OSM to IDF, which measure manager initiates. Just to clarify, you can run simulation on this model without any problems? What happens if you export to IDF from the file menu?

**Comment by anchapin** [comment] 2018-10-30 15:08
@DavidGoldwasser I just updated the post above to correct a typo. I can not run the simulation on this model.

Unfortunately, the file is of a sensitive government building, so anything related to the geometry of the building and space/zone names can't be sent online. I'm willing to provide a redacted version of the file, but not sure I have time to do that now, unless you have an idea of a quick way for me to do this. Thanks

**Comment by anchapin** [comment] 2018-10-30 16:32
Do you have an idea for a workaround for this, or if not an estimated time frame for a fix?

Is there a way of easily reverting the file back to version 2.6.0 or do you think trying to use a different type of coil like DX:TwoSpeed might help?

**Comment by anchapin** [comment] 2018-10-30 18:04
Update: I have an older version of this file (main difference is smaller building size) with DX coils and it simulates, can export IDF file, and can have measures added to it even after converting it to version 2.7.0.

Now I'm trying to figure out what else is different which may be leading to this error. Note that both of these files were originally created from the Proposed design model with the "Create Baseline Building" measure and the ones having the problem was created more recently. Therefore, I don't know if any changes have been made to the openstudio-standards code that could be affecting this.

**Comment by DavidGoldwasser** [comment] 2018-10-30 18:46
@anchapin is the `OS:Coil:Heating:DX:SingleSpeed` object in each of the two models. if the object doesn't look the same in both, can you paste the text in this thread. You can open the OSM in a text editor.

**Comment by anchapin** [comment] 2018-10-30 19:01
An example OS:Coil:Heating:DX:SingleSpeed for Bangkok_ASH 2013_rev.osm (the one with the error) is: 
```
OS:Coil:Heating:DX:SingleSpeed,
  {4c3d6945-1dae-4e89-9e3c-91eda1d2f99e}, !- Handle
  00_C_Res_Zn PTHP Htg Coil 12 Clg kBtu/hr 3.1COPH, !- Name
  {6e8dbd76-5254-4c6f-a302-11a185759d64}, !- Availability Schedule Name
  Autosize,                               !- Rated Total Heating Capacity {W}
  3.28845262834006,                       !- Rated COP {W/W}
  Autosize,                               !- Rated Air Flow Rate {m3/s}
  773.3,                                  !- Rated Supply Fan Power Per Volume Flow Rate {W/(m3/s)}
  ,                                       !- Air Inlet Node Name
  ,                                       !- Air Outlet Node Name
  {f3a7395a-7c8b-4a86-b2e0-23bcc8281e2f}, !- Total Heating Capacity Function of Temperature Curve Name
  {e6b8539c-e67f-4103-bfdc-cde72f736e76}, !- Total Heating Capacity Function of Flow Fraction Curve Name
  {629ac452-6de7-4888-b6b1-385febb6bed4}, !- Energy Input Ratio Function of Temperature Curve Name
  {eff6c5e3-2ccc-4179-a3a9-4109cff734ed}, !- Energy Input Ratio Function of Flow Fraction Curve Name
  {7daeea40-053a-40c2-b689-c64f28ca4d3b}, !- Part Load Fraction Correlation Curve Name
  {fba951ee-43b1-433b-9fa0-59449c923572}, !- Defrost Energy Input Ratio Function of Temperature Curve Name
  -7.99999999999994,                      !- Minimum Outdoor Dry-Bulb Temperature for Compressor Operation {C}
  ,                                       !- Maximum Outdoor Dry-Bulb Temperature for Defrost Operation {C}
  ,                                       !- Crankcase Heater Capacity {W}
  ,                                       !- Maximum Outdoor Dry-Bulb Temperature for Crankcase Heater Operation {C}
  ReverseCycle,                           !- Defrost Strategy
  OnDemand,                               !- Defrost Control
  0.166667,                               !- Defrost Time Period Fraction
  2000;                                   !- Resistive Defrost Heater Capacity {W}
```

And the same object in Bangkok_ASH 2013.osm is:
```
OS:Coil:Heating:DX:SingleSpeed,
  {24060dde-2154-42d4-9816-01255478b89b}, !- Handle
  00_C_Res_Zn PTHP Htg Coil 18 Clg kBtu/hr 2.9COPH, !- Name
  {6e8dbd76-5254-4c6f-a302-11a185759d64}, !- Availability Schedule Name
  Autosize,                               !- Rated Total Heating Capacity {W}
  3.10890592129649,                       !- Rated COP {W/W}
  Autosize,                               !- Rated Air Flow Rate {m3/s}
  773.3,                                  !- Rated Supply Fan Power Per Volume Flow Rate {W/(m3/s)}
  ,                                       !- Air Inlet Node Name
  ,                                       !- Air Outlet Node Name
  {1aadce2e-f7f3-4ca3-8894-cc2f5c584844}, !- Total Heating Capacity Function of Temperature Curve Name
  {2477211d-edee-42d6-9a33-6bb217a72d34}, !- Total Heating Capacity Function of Flow Fraction Curve Name
  {fd353fe8-8535-422f-a3e8-54baf0e49c47}, !- Energy Input Ratio Function of Temperature Curve Name
  {42d97a26-ced0-4253-bf6a-74b09fb22de9}, !- Energy Input Ratio Function of Flow Fraction Curve Name
  {1c8a415e-f68b-4723-8148-6c4947478d21}, !- Part Load Fraction Correlation Curve Name
  ,                                       !- Defrost Energy Input Ratio Function of Temperature Curve Name
  ,                                       !- Minimum Outdoor Dry-Bulb Temperature for Compressor Operation {C}
  ,                                       !- Maximum Outdoor Dry-Bulb Temperature for Defrost Operation {C}
  ,                                       !- Crankcase Heater Capacity {W}
  ,                                       !- Maximum Outdoor Dry-Bulb Temperature for Crankcase Heater Operation {C}
  Resistive,                              !- Defrost Strategy
  Timed,                                  !- Defrost Control
  0.166667,                               !- Defrost Time Period Fraction
  2000;                                   !- Resistive Defrost Heater Capacity {W}
```

**Comment by anchapin** [comment] 2018-10-30 19:39
The curve objects are provided below. Note that they are the same between files therefore `{42d97a26-ced0-4253-bf6a-74b09fb22de9}` is the same as `{eff6c5e3-2ccc-4179-a3a9-4109cff734ed}` below.

```
OS:Curve:Cubic,
  {f3a7395a-7c8b-4a86-b2e0-23bcc8281e2f}, !- Handle
  DXHEAT-NECB2011-REF-CAPFT,              !- Name
  0.729,                                  !- Coefficient1 Constant
  0.0319,                                 !- Coefficient2 x
  0.000136,                               !- Coefficient3 x**2
  -8.75e-006,                             !- Coefficient4 x**3
  -20,                                    !- Minimum Value of x
  20;                                     !- Maximum Value of x

OS:Curve:Cubic,
  {e6b8539c-e67f-4103-bfdc-cde72f736e76}, !- Handle
  DXHEAT-NECB2011-REF-CAPFFLOW,           !- Name
  0.84,                                   !- Coefficient1 Constant
  0.16,                                   !- Coefficient2 x
  0,                                      !- Coefficient3 x**2
  0,                                      !- Coefficient4 x**3
  0.5,                                    !- Minimum Value of x
  1.5;                                    !- Maximum Value of x

OS:Curve:Cubic,
  {629ac452-6de7-4888-b6b1-385febb6bed4}, !- Handle
  DXHEAT-NECB2011-REF-EIRFT,              !- Name
  1.2183,                                 !- Coefficient1 Constant
  -0.03612,                               !- Coefficient2 x
  0.00142,                                !- Coefficient3 x**2
  -2.68e-005,                             !- Coefficient4 x**3
  -20,                                    !- Minimum Value of x
  20;                                     !- Maximum Value of x

OS:Curve:Quadratic,
  {eff6c5e3-2ccc-4179-a3a9-4109cff734ed}, !- Handle
  DXHEAT-NECB2011-REF-EIRFFLOW,           !- Name
  1.3824,                                 !- Coefficient1 Constant
  -0.4336,                                !- Coefficient2 x
  0.0512,                                 !- Coefficient3 x**2
  0,                                      !- Minimum Value of x
  1;                                      !- Maximum Value of x

OS:Curve:Cubic,
  {7daeea40-053a-40c2-b689-c64f28ca4d3b}, !- Handle
  DXHEAT-NECB2011-REF-PLFFPLR,            !- Name
  0.3696,                                 !- Coefficient1 Constant
  2.3362,                                 !- Coefficient2 x
  -2.9577,                                !- Coefficient3 x**2
  1.2596,                                 !- Coefficient4 x**3
  0.7,                                    !- Minimum Value of x
  1;                                      !- Maximum Value of x

OS:Curve:Biquadratic,
  {fba951ee-43b1-433b-9fa0-59449c923572}, !- Handle
  00_C_Res_Zn PTHP Htg Coil Defrost EIR Func of Temp Curve, !- Name
  0.297145,                               !- Coefficient1 Constant
  0.0430933,                              !- Coefficient2 x
  -0.000748766,                           !- Coefficient3 x**2
  0.00597727,                             !- Coefficient4 y
  0.000482112,                            !- Coefficient5 y**2
  -0.000956448,                           !- Coefficient6 x*y
  12.77778,                               !- Minimum Value of x
  23.88889,                               !- Maximum Value of x
  21.11111,                               !- Minimum Value of y
  46.11111;                               !- Maximum Value of y
```

**Comment by DavidGoldwasser** [comment] 2018-10-30 19:56
@anchapin it looks like somehow the curve with UUID if `{42d97a26-ced0-4253-bf6a-74b09fb22de9}` has been deleted but is still referred to by the coil. I believe there must be a bug in the OS app or measure that caused this. While that is hard to track down the good news is we should be able to get you up and running again. I would follow these steps.

1. Save OSM as a copy with unique name
2. Delete the parent object that uses this coil. That could be a zone equipment object like PTHP, or could be unitary heat pump on an air loop.
3. Re-add the objet back and modify characteristics to match what was in the old model or what you want them to be.
4. If you intend for this to be a baseline model, you might have to run the baseline measure to get the expected curves for the coil.

Try to export to idf after step 3, and then again after step 4.

**Comment by anchapin** [comment] 2018-10-31 11:50
@DavidGoldwasser thanks for suggesting those steps. That wasn't the problem (coil referencing a deleted curve UUID), but in the process of following those steps I figured out the issue. All of the PSZ HPs (System Type 4 in ASHRAE) were created by the "Create Baseline Building" measure without a UUID for a Energy Input Ratio Function of Flow Fraction Curve Name input field. See below for an example. Therefore, once I put a place holder curve in there, the issue went away (I could add measures, export IDF, etc.).

Therefore, this seems to be an issue with the "Create Baseline Building" measure as I expected.

```
OS:Coil:Heating:DX:SingleSpeed,
  {776f6865-1852-4676-bff0-84bf537884ed}, !- Handle
  07-12_C_IT_Zn HP Htg Coil 426 Clg kBtu/hr 3.2COPH, !- Name
  {6e8dbd76-5254-4c6f-a302-11a185759d64}, !- Availability Schedule Name
  Autosize,                               !- Rated Total Heating Capacity {W}
  3.60026690437399,                       !- Rated COP {W/W}
  Autosize,                               !- Rated Air Flow Rate {m3/s}
  773.3,                                  !- Rated Supply Fan Power Per Volume Flow Rate {W/(m3/s)}
  {d585d277-c98b-48a0-8bb4-28976a9a89d1}, !- Air Inlet Node Name
  {25129ef6-83e4-46a2-9533-5fc6d1670159}, !- Air Outlet Node Name
  {bc8f8221-eff4-4f73-8a4a-2bc3973fa606}, !- Total Heating Capacity Function of Temperature Curve Name
  {cc195893-93ff-4d9b-babf-f147e959acbc}, !- Total Heating Capacity Function of Flow Fraction Curve Name
  {e579bc22-6789-4e64-8d98-3e14056b26bd}, !- Energy Input Ratio Function of Temperature Curve Name
  ,                                       !- Energy Input Ratio Function of Flow Fraction Curve Name
  {c5cfd3ce-0677-4f0f-80df-6c8db152a06f}, !- Part Load Fraction Correlation Curve Name
  {0604b260-f8f0-4a01-a837-cb7513e2a3e7}, !- Defrost Energy Input Ratio Function of Temperature Curve Name
  -12.2,                                  !- Minimum Outdoor Dry-Bulb Temperature for Compressor Operation {C}
  1.67,                                   !- Maximum Outdoor Dry-Bulb Temperature for Defrost Operation {C}
  50,                                     !- Crankcase Heater Capacity {W}
  4.4,                                    !- Maximum Outdoor Dry-Bulb Temperature for Crankcase Heater Operation {C}
  ReverseCycle,                           !- Defrost Strategy
  OnDemand,                               !- Defrost Control
  0.166667,                               !- Defrost Time Period Fraction
  2000;                                   !- Resistive Defrost Heater Capacity {W}
```

**Comment by DavidGoldwasser** [comment] 2018-11-01 15:18
@anchapin can you re-run the baseline measure on your model and see if the coil objects are still invalid. We can't reproduce this kind of corruption with one of our models.

It is clear the missing required curve is why the application is crashing, it isn't clear how the file got corrupted.

**Comment by anchapin** [comment] 2018-11-01 16:32
@DavidGoldwasser I just tried re-running the baseline measure again and this time that issue didn't occur. I'm not sure what's different this time around, I used the same starting file (at least the best that I can tell).

**Comment by jmarrec** [comment] 2019-04-18 14:26
Should we close this since we can't reproduce it?

**Closed** 2019-04-19 19:03 UTC
Labels: component - Model, severity - Major Bug
