### ISSUE TITLE
Simplify findtools in App

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#1396] opened 2015-02-05 15:55 UTC
Now that we are packaging E+, the find tools process should be simplified in OpenStudio Application.  Particularly code in RunTabView.cpp should be reviewed and simplified as needed.  Try to avoid searching entire file system for E+.  Even though find tools now looks in the installed resources path first, it still proceeds to look over the entire system.  Lets have viewer options, simpler code, and better user experience, taking advantage of the fact that we ship e+.   This was considered too much to bundle into the 8.2.0 update.

**Comment by macumber** [comment] 2015-07-28 19:01
duplicate of https://github.com/NREL/OpenStudio/issues/1553

**Closed by macumber** 2015-07-28 19:01 UTC
Labels: component - Code, component - OS App, Feature Request
