### ISSUE TITLE
GridView shows ThermalZone in IG thereby duplicating the functionality of the grid

### ISSUE THREAD

**Issue by kbenne** [NREL/OpenStudio#1230] opened 2014-10-02 18:34 UTC
See the screenshot.  I can't quite follow the input steps that make this happen but it seems to be clicking on any of the line edit fields.  And not just the zone name one.  Clicking on the air loop name seems to inspect the zone too. @asparke2 did you see this too?  Consider adding your issues to github so we can search and track them.

![screen shot 2014-10-02 at 1 33 01 pm](https://cloud.githubusercontent.com/assets/707488/4496177/c08009fa-4a62-11e4-9f46-fb10ad7e6891.png)

**Comment by macumber** [comment] 2015-01-07 05:11
@kbenne can you prioritize and add to pivotal if needed?

**Comment by asparke2** [comment] 2015-01-31 21:03
closing because cannot reproduce in 1.6.0.

**Closed by asparke2** 2015-01-31 21:03 UTC
Labels: component - OS App, resolution - Can't Reproduce, severity - Minor Bug
