### ISSUE TITLE
TimeSeries timestamps made incorrectly using E+ 8.3 sql file

### ISSUE THREAD

**Issue by asparke2** [NREL/OpenStudio#1692] opened 2015-06-19 22:22 UTC
The calibration report was not showing up correctly in 1.7.2 onward (per @brianlball example model).  After some digging into this, it looks like the BillingPeriod::modelConsumptionValues() query was failing with log messages indicating that the time period being asked for was outside of the length of the timeseries itself:  

```
[utilities.TimeSeries_Impl] Cannot compute value 17967600 seconds after first reporting time when duration is 1310400 seconds
```

Digging deeper, it looks like the timeseries constructor? is no longer creating the correct timestamps based on the way the results are stored in E+ 8.3 sql file.  Not sure if this affects all timeseries or just ones with certain timestamps (like daily).  Looking at the eplusout.sql files in sqlite manager, I can see changes in the way timeseries results are being stored, and I assume they are behind the issues.  The pictures below should make the problem easy to see.

All the results below were created by running the same model, once in 1.7.0 (E+ 8.2), and again in 1.7.5 (E+ 8.3).  The pictures below both show Gas:Facility at a Daily resolution.  1.7.0 shows the timestamps correctly.  1.7.5 has the same values, but is giving them incorrect timestamps (notice that the shape is correct, but the max date on the X-Axis is mid-January.

From a query getting the meter from the utility bill, we can see that in 1.7.0, the timeseries correctly identified that the values go through the whole year.  Running the same exact query on the same model in 1.7.5, we can see that the timeseries thinks it only goes though Jan 16th.  Notice that both queries result in 365 values.

## 1.7.0:
  Daily
  TimeSeries for Gas Bill
  Meter = Gas:Facility
  from 2009-Jan-02 00:00:00 to 2010-Jan-01 00:00:00
  for runperiod Run Period 1
  time series has 365 values
![gas facility daily 1 7 0](https://cloud.githubusercontent.com/assets/2009290/8263955/9aba40f2-169d-11e5-9631-5e9988d7d8d9.PNG)

## 1.7.5
  Daily
  TimeSeries for Gas Bill
  Meter = Gas:Facility
  from 2009-Jan-01 01:00:00 to 2009-Jan-16 05:00:00
  for runperiod Run Period 1
  time series has 365 values
![gas facility daily 1 7 5](https://cloud.githubusercontent.com/assets/2009290/8263972/d5722ffc-169d-11e5-8b1f-53365e6e1307.PNG)

I have two test files and ruby tests that replicate the issue when run with 1.7.5 vs. 1.7.0.

**Comment by asparke2** [comment] 2015-06-19 22:23
@kbenne This reinforces the point you made about not having a good method to catch changes in the E+ output file during the migration process.

**Comment by asparke2** [comment] 2015-06-19 22:38
might be related to changes made in https://github.com/NREL/OpenStudio/pull/1659 by @mbadams5 ?

**Comment by macumber** [comment] 2015-06-19 22:44
@jasondegraw should be aware of this too

**Comment by macumber** [comment] 2015-06-19 22:45
I take it this is a show stopper to be fixed for the release?

**Comment by macumber** [comment] 2015-06-19 22:51
The unit test we added on @jasondegraw 's timeseries branch might have caught this (although I don't think we had daily timesteps in there)

**Comment by mbadams5** [comment] 2015-06-19 23:58
@asparke2 So are you saying the timeseries is wrong in EnergyPlus output or in the way OpenStudio reads in the EnergyPlus output?

**Comment by macumber** [comment] 2015-06-20 00:01
@mbadams5 not sure yet, both changed recently, I will look into it

**Comment by macumber** [comment] 2015-06-20 00:01
@axelstudios FYI, we will likely want a fix in the final package.  I'll look into this tonight

**Comment by jasondegraw** [comment] 2015-06-20 01:36
You'll want to check that the best ctor is getting used. It should probably
use one of the interval versions, but if I recall correctly it is not.

**Comment by macumber** [comment] 2015-06-20 06:51
@mbadams5 If you look at the 1ZoneEvapCooler-V8-2-0.sql and 1ZoneEvapCooler-V8-3-0.sql in the test I have been working on (https://github.com/NREL/OpenStudio/commit/50d7a51aa4f5e9ab26bb595d3f9f08f7a23d3ed3) you can see that the issue is that Daily, Monthly, and RunPeriod variables seem to have the interval reported out as 60 minutes in 8.3, in 8.2 and previous versions of E+ the intervals were correct.

you can run this query to verify that there are no intervals > 60 minutes in the 8.3 sql file even though there are daily, monthly, and run period reports:

    select * from time where interval > 60

**Comment by macumber** [comment] 2015-06-20 06:57
I may be able to provide a workaround for existing 8.3 files, but this should get fixed in E+

**Comment by macumber** [comment] 2015-06-21 05:47
@brianlball this fixed the issue
@asparke2 ResultsViewer looks good with all timesteps at first glance
@axelstudios we should run the unit tests and sanity tests, then good to merge and make packages

![6-20-2015 11-40-52 pm](https://cloud.githubusercontent.com/assets/1327850/8270621/eae38922-17a5-11e5-873d-0f37cd221475.jpg)

**Closed** 2015-06-22 14:33 UTC
Labels: component - ResultsViewer, EnergyPlus Issue, In Progress, severity - Major Bug
