### ISSUE TITLE
Failed Simulations for Coil Cooling Water To Air Heat Pump Variable Speed Equation Fit in 2.7.0

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/OpenStudio#3332] opened 2018-11-02 19:51 UTC
Forward translation changed between 2.6.0 and 2.7.0 to automatically add in UnitarySystemPerformance:Multispeed objects, in a way that results in failed simulations with this error.

```
   **  Fatal  ** COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT = COIL COOLING WATER TO AIR HEAT PUMP VARIABLE SPEED EQUATION FIT 28 number of speeds not equal to number of speed specified in UnitarySystemPerformance:Multispeed object.
```
The coil in question above is part of OS:ZoneHVAC:WaterToAirHeatPump object. May be related to this commit.
https://github.com/NREL/OpenStudio/commit/c64af7288a61b62a7e8235b4f2a17baaf0ab4efa

Hit this k-12 net zero project when updated to 2.7.0. The model made from unit test on this measure will exhibit this error when run on EnergyPlus
https://github.com/NREL/OpenStudio-measures/tree/develop/nrel_published/zedgk_12_hvac_gshp_doas

cc @jmarrec @kbenne

**Comment by jmarrec** [comment] 2018-11-05 10:59
Pretty sure that's not what's happening. If you look more closely at the error + the generated IDF, you'll notice that in fact there isn't any `UnitarySystemPerformance:Multispeed` object for the concerned `ZoneHVAC:WaterToAirHeatPump`.

I believe E+ 9.0.0 now makes `UnitarySystemPerformance:Multispeed` mandatory when you use multispeed coils in a heat pump (and I would reckon it wasn't really handling multispeeds before if you were missing some, which would explain the 40% discrepancy in the unitary system regression tests in the newly 9.0.0 release). 

So in the commit you linked I handled that for an extra type, since I had a regression test failing.
I think the same fix and logic would be needed in `ForwardTranslateZoneHVACWaterToAirHeatPump.cpp`: if you detect multispeed cooling and/or heating coils in there, you should create a `UnitarySystemPerformance:Multispeed`

**Comment by DavidGoldwasser** [comment] 2018-11-06 18:07
@kbenne I'm assuming since there isn't a way to access this object in the GUI, we probably want to add to forward translator.

For my use case in measure, I can update the measure to add these. @kbenne or @jmarrec do either of you have an example measure, OSM or IDF that uses these with zone equipment. The example EnergyPlus files for Coil Cooling Water To Air Heat Pump Variable Speed Equation Fit looked like they were on air loops.

**Comment by DavidGoldwasser** [comment] 2018-11-06 18:21
Wondering if I can solve this in measure. While AirLoopHVACUnitarySystem has field to refer to UnitarySystemPerformance:Multispeed object

For zone heat pump I don't see where to refer to UnitarySystemPerformance:Multispeed in either CoilCoolingWaterToAirHeatPumpVariableSpeedEquationFit or 
ZoneHVACWaterToAirHeatPump

Not sure what valid OSM model would look like in 2.7.0.

**Comment by macumber** [comment] 2018-11-08 03:20
@jmarrec are you able to fix this on Thursday?  If so, please do

**Comment by jmarrec** [comment] 2018-11-08 15:52
So to me it's an E+ issue which I've at least partially addressed in https://github.com/NREL/EnergyPlus/issues/7053 (but your test model will still fail to run with the fix, unsure why).

I think a workaround would be to use a `AirLoopHVAC:UnitarySystem` (`AirLoopHVAC:UnitaryHeatPump:WaterToAir` isn't wrapped anyways) and place that in the zone directly, since you'd end up with an actual `UnitarySystemPerformance:Multispeed` object. `AirLoopHVAC:UnitarySystem` should be allowed in zones since at least 8.8.0.

**Comment by DavidGoldwasser** [comment] 2018-12-13 18:56
@jmarrec thanks for looking into this. I couldn't see if there was another EnergyPlus issue filed related to the divide by 0 in sizing manager filed here?
https://github.com/NREL/EnergyPlus/issues/7053#issuecomment-436970871

**Comment by jmarrec** [comment] 2018-12-14 09:40
I haven't opened a separate issue but feel free to.

**Comment by jmarrec** [comment] 2019-09-27 09:10
Fixed on E+'s side via https://github.com/NREL/EnergyPlus/pull/7054.

@DavidGoldwasser If you run into this again, please reopen.

**Closed by jmarrec** 2019-09-27 09:10 UTC
Labels: component - Model
