### ISSUE TITLE
Copying a zone attached to an air loop and attaching the cloned zone to the same air loop breaks the loop

### ISSUE THREAD

**Issue by eringold** [NREL/OpenStudio#3142] opened 2018-05-24 14:27 UTC
Found in v2.5 (Windows):

1. create an air loop and attach a thermal zone: TZ1
2. copy the attached zone (with 'X2' button), creating TZ2
3. attach TZ2 to the air loop containing TZ1 (either by selecting from the splitter, or dragging to the demand side drop zone). TZ1 appears to be removed from the demand side in the air loops tab, but in the zones tab still appears to be connected to the air loop. Attempting to re-add TZ1 to the loop won't work; deleting the TZ1 terminal will still show it as connected to the loop. 

Edit: happens whether or not there is a terminal unit connected.

Possibly related to https://github.com/NREL/OpenStudio/issues/1544

@kbenne  FYI

**Comment by jmarrec** [comment] 2018-09-18 12:41
Confirmed in 2.6.0, where this is happening because the `Zone Return Air Node Name` (2.6.0) isn't cleared so it references the one from the primary zone that is being cloned. So the code: https://github.com/NREL/OpenStudio/blob/v2.6.0/openstudiocore/src/model/ThermalZone.cpp#L2340, you'll find nothing on Zone Return Air Node Name.

I'm 99% sure this is fixed in 2.6.1 though (from reading code, haven't tested), where it's no longer a node but 'Zone Return Air Port List', see https://github.com/NREL/OpenStudio/blob/v2.6.1/openstudiocore/src/model/ThermalZone.cpp#L2341:L2342

**Comment by jmarrec** [comment] 2018-09-18 12:48
Confirmed after installed 2.6.1, it works as expected. This can be closed

**Closed** 2018-09-18 18:59 UTC
